// Brady M210 / M210-LAB. Reference data for Labelarium.
// Source: official M210/M210-LAB User Manual, Firmware 3.0, Rev. B (2022) plus Brady support.
// Notation in steps: [Key] = a key on the device, {Text} = what the LCD shows, → = then.
// Symbol items: [name, keywords, unicode approximation]. Position (1-based) = order in the category on the printed sheet.
// Catalog art is cropped from this manual only. Do not treat Brother P-touch lists as M210 data.
export default {
  id: 'brady-m210',
  brand: 'Brady',
  model: 'M210',
  name: 'Brady M210',
  tagline: 'Portable Industrial Label Printer',
  links: [
    ['Official support, manuals & FAQs', 'https://www.bradyid.com/support/printer/m210'],
    ['Brady technical support (US)', 'https://www.bradyid.com/techsupport'],
    ['Register the printer', 'https://www.bradycorp.com/register'],
  ],
  specs: [
    ['Printers', 'M210 (industrial + lab types) and M210-LAB (laboratory types only). Same hardware; label-type menus differ. A Russian / Cyrillic-keypad M210 also exists.'],
    ['Print', '203 dpi thermal transfer. Max print width 0.75" (19.1 mm). Max alphanumeric length 99.9" (253.7 cm). Max 50 characters. Up to 4 lines.'],
    ['Symbols', 'Official counts: M210 194 · M210 with Cyrillic keypad 218 · M210-LAB 131. This pack lists every filled cell printed in Appendix A of the shared M210/M210-LAB manual (221 glyphs).'],
    ['Typeface', 'One typeface: Brady Fixed Width Condensed. Sizes Auto / 6 / 9 / 14 / 20 / 28 / 40 pt, each with a Bold weight. Default 9 pt. No extra fonts, widths or frames.'],
    ['Media', 'Brady Authentic M21 cartridges, continuous 0.25"–0.75" (6.35–19.1 mm) or pre-sized. Smart-cell sets many format details. No PC port. Cannot print from a computer.'],
    ['Memory', '12 saved files (name up to 11 characters). Files survive battery removal.'],
    ['Barcodes', 'Code 39 and Code 128 (Banner Landscape or Flag). Datamatrix (max 44 chars) and QR (max 50 chars), small/large; 0.75" media and Banner Landscape only.'],
    ['Power', '6 × AA alkaline (not rechargeable AA, not Ultimate Lithium), optional M210-BATTERY Li-ion pack (charges only on the AC adapter, outside the printer), or optional 9 V Brady AC adapter (M210-AC / 110416 / 110417). Auto-off after 10 minutes idle.'],
    ['Size / weight', '243.84 × 63.5 × 124.46 mm (9.6" × 2.5" × 4.9"), 0.75 kg / 1.66 lb with battery pack'],
    ['Environment', 'Operating 4–43 °C (40–110 °F), 20–90% RH non-condensing. Direct sunlight not recommended.'],
    ['Languages', 'M210: 20 (English default, French, Spanish, German, Dutch, Portuguese, Italian, Czech, Danish, Estonian, Finnish, Hungarian, Norwegian, Polish, Romanian, Slovakian, Slovenian, Swedish, Turkish, Croatian). M210-LAB: English, French, Spanish, German, Dutch, Portuguese, Italian. M210 Russian: Russian default + English. Greek letters live under International, not Language.'],
  ],
  tapes: [
    { mm: 6.4, in: '0.25"', lines: 4, note: 'Narrowest M21 width. Panel Residential recommends 9 pt on 0.25" for a residential breaker door. 2D codes will not fit.' },
    { mm: 9.5, in: '0.375"', lines: 4, note: 'Continuous or pre-sized M21. Some symbols cannot print at 6 pt. Use 9 pt or larger.' },
    { mm: 12.7, in: '0.50"', lines: 4, note: 'General industrial / wire. SelfLam and Permasleeve hide several label types (see Label Type).' },
    { mm: 19.1, in: '0.75"', lines: 4, note: 'Maximum width. Required for Datamatrix and QR. Stock cartridge with the M210 is M21-750-499 nylon; M210-LAB ships M21-750-7425.' },
  ],
  keyboard: {
    image: 'img/keyboard.png',
    legend: [
      [1, 'Text lines', 'Line markers on the LCD. Up to four lines. [Enter] starts a new line. A blank line still counts as a line for “Cannot Fit”.'],
      [2, 'Label type', 'Status-bar code for the active application (BAN, GEN, VIAL, W.75, TERM, PORT, FLAG, BRKR, …).'],
      [3, 'Font size', 'Current size in points, or {A} when Autosize is on.'],
      [4, 'Bold', 'Lit when the Bold weight of Brady Fixed Width Condensed is on.'],
      [5, 'Caps lock', 'Lit when Caps Lock is on.'],
      [6, 'Function-key indicator', 'The gold Alt chevron in the status bar while an alternate function is armed.'],
      [7, 'Battery life', 'Battery gauge. Weak cells cause “Error”, freeze-ups and auto power-off.'],
      [8, 'Power', 'On / off. If the UI freezes, hold Power to shut down; if that fails, pull the adapter and batteries and reseat them.'],
      [9, 'Function keys', 'Left column: [Feed] / [Label Type], [Serial] / [Menu], [Caps] / [Font Size]. Gold legends need [Alt].'],
      [10, 'Alphanumeric keypad', 'ABC-style keys. [Alt] + a key types the gold legend (Symbol, Barcode, International, Add Date, Add Time, decimal).'],
      [11, 'Alternate [Alt]', 'Gold function key. Press [Alt] then the key, or hold [Alt] while pressing it. Also used for special characters on letter/number keys.'],
      [12, 'Navigation pad + [Enter]', 'Move the cursor; in menus move up/down through primary items and left/right through a secondary list (Symbols, International). [Enter] accepts a menu choice or adds a blank line.'],
      [13, 'Print / Multi-Print', '[Print] prints the file. [Alt] + [Print] is Multi-Print (copies, then cut between or at end of job).'],
      [14, 'Clear / Backspace', '[Backspace] deletes left of the cursor and walks out of menus one screen at a time. [Alt] + [Backspace] is [Clear] (data gone, format kept).'],
      [15, 'Cutter lever', 'Squeeze to cut after the print icon disappears. Cutting while printing raises “Cut while printing”.'],
      [16, 'Cartridge lock', 'Horizontal = unlocked, vertical = locked. Unlock before ejecting. Leaving it locked when idle can burn a black line onto the next label.'],
      [17, 'Cartridge bay', 'Drop-lock-print M21 cartridge. Authentic A logo required. Eject from the back, then lift out.'],
      [18, 'AC adapter port', '9 V Brady adapter only. Powers the printer; does not charge the Li-ion pack inside the printer.'],
      [19, 'Cartridge eject', 'On the back. Unlock first, then press eject and lift the cartridge.'],
      [20, 'Battery compartment', 'Six AA alkaline or the M210-BATTERY pack. Finger tabs on the door. Li-ion charges only on the adapter, outside the printer.'],
      [21, 'Space / Backlight', '[Space] inserts a space. [Alt] + [Space] toggles the backlight.'],
      [22, 'Symbol', '[Alt] + [1]. Opens the graphics catalog. The printer returns to the last category used.'],
      [23, 'Barcode', '[Alt] + [2]. Code 39 or Code 128 on Banner Landscape or Flag.'],
      [24, 'International', '[Alt] + [6] (or [Menu] → {International}). Accented letters. Greek letters also live here, not under Language.'],
      [25, 'Add Date / Add Time', '[Alt] + [Z] inserts the date; [Alt] + [Y] inserts the time, using [Menu] → {Set Clock} formats.'],
      [26, 'Feed', '[Alt] + [Label Type]. Advances media without printing.'],
      [27, 'Serial', '[Alt] + [Menu]. Start / increment / end for simple 0–9 or A–Z sequences (not mixed). One serialized set per file.'],
      [28, 'Menu', 'Language, Units, Set Clock, Cut Mode, Set Zero Style, Backlight Time, Cartridge supply, About, Symbols, International, Timestamp, File. [Backspace] backs out.'],
    ],
  },
  shortcuts: [
    { keys: '[Alt] + [1]', action: 'Symbols catalog', kw: 'symbol graphic pictograph warning electrical lab' },
    { keys: '[Alt] + [2]', action: 'Barcode (Code 39 or Code 128)', kw: 'barcode code 39 128' },
    { keys: '[Alt] + [6]', action: 'International / accented characters', kw: 'accent international diacritic greek' },
    { keys: '[Alt] + [Z]', action: 'Insert date from the printer clock', kw: 'date timestamp' },
    { keys: '[Alt] + [Y]', action: 'Insert time from the printer clock', kw: 'time timestamp' },
    { keys: '[Alt] + [Label Type]', action: 'Feed media', kw: 'feed advance tape' },
    { keys: '[Alt] + [Menu]', action: 'Serialization', kw: 'serial sequence increment numbering' },
    { keys: '[Alt] + [Print]', action: 'Multi-Print copies', kw: 'copies multi-print duplicate' },
    { keys: '[Alt] + [Space]', action: 'Backlight', kw: 'backlight lamp screen' },
    { keys: '[Alt] + [Backspace]', action: 'Clear all data (keep format)', kw: 'clear erase' },
    { keys: '[Alt] + [Font Size]', action: 'Caps Lock', kw: 'caps lock uppercase' },
    { keys: '[Font Size]', action: 'Size and Bold (Auto, 6, 9, 14, 20, 28, 40 pt)', kw: 'font size bold autosize' },
    { keys: '[Label Type]', action: 'Application templates (banner, vial, wire, flag, …)', kw: 'label type template banner vial wire flag' },
    { keys: '[Print]', action: 'Print the current file', kw: 'print' },
    { keys: '[Enter]', action: 'Accept a menu item, or start a new line (max four)', kw: 'enter newline accept' },
    { keys: '[Backspace]', action: 'Delete left; also cancel menus one screen at a time', kw: 'backspace cancel escape' },
    { keys: '[Menu] → {File}', action: 'Save / Open / Delete one of 12 files', kw: 'file save open memory' },
    { keys: '[Menu] → {Units}', action: 'Inches or millimetres', kw: 'unit inch mm' },
    { keys: '[Menu] → {Language}', action: 'Printer language (6th item; the word itself is already localised)', kw: 'language' },
    { keys: '[Menu] → {Cut Mode}', action: 'Cut between labels, or cut at end of job', kw: 'cut mode between end' },
    { keys: '[Menu] → {Set Zero Style}', action: 'Open zero vs slashed zero', kw: 'zero slashed' },
    { keys: '[Menu] → {Timestamp} → {Insert Date} / {Insert Time}', action: 'Stamp date or time without the dedicated keys', kw: 'timestamp date time' },
  ],
  fonts: [
    ['Brady Fixed Width Condensed', 'brady-fixed.png', 'The only typeface. Condensed industrial sans; size and Bold are changed with [Font Size], not a font menu.', '"Arial Narrow", "Helvetica Neue Condensed", "Helvetica Neue", Arial, sans-serif', 400, 'normal'],
  ],
  sizes: [
    ['Auto', 'size-auto.png', 1],
    ['6 pt', 'size-6.png', 0.15],
    ['9 pt', 'size-9.png', 0.225],
    ['14 pt', 'size-14.png', 0.35],
    ['20 pt', 'size-20.png', 0.5],
    ['28 pt', 'size-28.png', 0.7],
    ['40 pt', 'size-40.png', 1],
  ],
  widths: [['Normal', 'width-normal.png', 1]],
  styles: [['Normal', 'style-normal.png'], ['Bold', 'style-bold.png']],
  alignments: [
    ['Left (prints centered)', 'align-center.png'],
    ['Center', 'align-center.png'],
    ['Right (prints centered)', 'align-center.png'],
  ],
  fontNote: 'Single typeface (Brady Fixed Width Condensed) in Auto plus 6 / 9 / 14 / 20 / 28 / 40 pt, each with Bold. Default is 9 pt. Autosize shows as A in the status bar and scales down until [Enter] or the minimum size. The size applies to the whole label, not per line. Some symbols cannot print at 6 pt (“Cannot Fit”, switch to 9 pt). Left/right justification is not supported; everything prints centered. There is no outline, italic, shadow or vertical font style; Horizontal/Vertical is a Label Type option, not a font style.',

  symbols: {
    howto: [
      'Position the cursor, then press [Symbol] ([Alt] + [1]), or [Menu] → {Symbols} → [Enter].',
      'Use [▲] / [▼] to the category, then [Enter]. The printer always reopens the last category you used.',
      'Use the navigation pad to the glyph, then [Enter]. It inserts at the current font size.',
      'Appendix A of this manual is the printed catalog. Electrical, Home Electrical and DataComm are M210 and Russian only (not M210-LAB). Miscellaneous (Russian) is Cyrillic-keypad only. Greek coverage depends on the printer version. Official counts: M210 194, Cyrillic M210 218, M210-LAB 131.',
      '[Backspace] removes a symbol like any other character. [Backspace] also backs out of the catalog.',
    ],
    categories: [
      { id: 'warning', name: 'Warning', group: 'Pictograph', key: 'Nav', kw: 'safety hazard iso ghs danger', items: [
        ['General warning (exclamation triangle)', 'caution hazard attention iso 7010 W001', '⚠️'],
        ['High voltage (lightning triangle)', 'electric shock electricity W012', '⚡'],
        ['Toxic (skull and crossbones triangle)', 'poison death hazard', '☠️'],
        ['Biohazard', 'biological infection lab', '☣️'],
        ['Radioactive / ionizing radiation', 'trefoil nuclear', '☢️'],
        ['Corrosive', 'acid chemical burns test tubes', '🧪'],
        ['Slip hazard (falling person)', 'wet floor fall', '⚠️'],
        ['Protective earth / ground', 'earth GND down arrow bars', '⏚'],
        ['Non-ionizing radiation', 'antenna radio rf', '📡'],
        ['Explosive', 'blast bursting bomb', '💥'],
        ['Flammable', 'fire flame hot', '🔥'],
        ['Optical radiation / irritant burst', 'bright light laser ozone', '✳️'],
        ['DANGER wordmark', 'danger warning bar', '⛔'],
        ['Penguin (Brady)', 'brady mascot cold', '🐧'],
        ['Brady Authentic mark', 'brady logo authentic A', '🅱️'],
      ]},
      { id: 'electrical', name: 'Electrical (M210 / Russian)', group: 'Pictograph', key: 'Nav', kw: 'iec schematic power wiring', items: [
        ['AC (sine wave)', 'alternating current mains', '∿'],
        ['Earth ground', 'earth GND three bars', '⏚'],
        ['Fuse / circuit breaker (vertical)', 'protection overcurrent', '⎓'],
        ['Capacitor', 'two plates lead', '||'],
        ['Switch (knife / toggle)', 'disconnect', '⏻'],
        ['Transformer', 'two windings coils', '⚡'],
        ['Earth electrode / protective conductor', 'ground rod', '⏚'],
        ['Pilot light / pushbutton', 'lamp indicator ring', '💡'],
        ['Lamp off (slashed)', 'pilot light cancelled', '⊘'],
        ['Capacitor (feed-through / plates)', 'polarized capacitor', '⊣'],
        ['Fuse (cartridge, horizontal)', 'protection', 'fuse'],
        ['Antenna', 'aerial Y', '📶'],
        ['Headphones', 'audio', '🎧'],
        ['Diode', 'semiconductor rectifier', '▷|'],
        ['Satellite dish', 'antenna dish', '📡'],
        ['Speaker', 'audio output', '🔊'],
        ['Capacitor (parallel plates)', 'capacitance', '||'],
        ['Inductor / coil', 'choke winding', '∿'],
        ['Motor (circled M)', 'machine drive', 'M'],
        ['Resistor (zigzag)', 'resistance ohm', 'Ω'],
        ['Fuse (cartridge with leads)', 'protection', 'fuse'],
        ['IP (ingress protection)', 'enclosure rating', 'IP'],
        ['Diameter / empty-set / phase', 'diameter not', '⌀'],
        ['Chassis ground (circle and bar)', 'frame earth', '⏚'],
      ]},
      { id: 'home-electrical', name: 'Home Electrical (M210 / Russian)', group: 'Pictograph', key: 'Nav', kw: 'appliance outlet heater kitchen', items: [
        ['Convector heater', 'baseboard heat', '♨️'],
        ['Freezer / cold cabinet', 'snowflake window', '❄️'],
        ['Water heater / boiler', 'hot water tank', '🚿'],
        ['Washing machine', 'laundry shirt drum', '👕'],
        ['Refrigerator', 'fridge freezer snowflake', '🧊'],
        ['Boiler / furnace', 'flame burner', '🔥'],
        ['Air conditioner', 'snowflake split unit', '❄️'],
        ['Printer', 'paper feed', '🖨️'],
        ['Radiator', 'heat panel', '🌡️'],
        ['Desktop computer', 'monitor keyboard', '🖥️'],
        ['Bell', 'alarm chime', '🔔'],
        ['Heating element / towel rail', 'pipes coils', '♨️'],
        ['Shelves / rack', 'storage server', '🗄️'],
        ['Breaker schedule / circuit list', 'panel legend', '📋'],
        ['Fan', 'blower', '🌀'],
        ['Consumer unit / distribution board', 'breaker box door', '🔌'],
        ['Horn / siren', 'alarm speaker', '📢'],
        ['Light', 'bulb lamp', '💡'],
        ['Socket (3-pin, triangular)', 'outlet receptacle', '🔌'],
        ['Socket (3-pin round)', 'outlet CEE', '🔌'],
        ['Socket (2-pin)', 'outlet euro', '🔌'],
        ['Cooktop', 'hob burners', '🍳'],
        ['Dishwasher', 'sink dishes', '🍽️'],
        ['Washer / dryer (water)', 'laundry wave', '🌊'],
        ['Oven', 'steam heat', '♨️'],
      ]},
      { id: 'arrows', name: 'Arrows', group: 'Pictograph', key: 'Nav', kw: 'direction pointer', items: [
        ['Up arrow', 'north', '↑'],
        ['Down arrow', 'south', '↓'],
        ['Left arrow', 'west', '←'],
        ['Right arrow', 'east', '→'],
        ['Left-right arrow', 'both ways horizontal', '↔'],
        ['Up-down arrow', 'both ways vertical', '↕'],
      ]},
      { id: 'datacom', name: 'DataComm (M210 / Russian)', group: 'Pictograph', key: 'Nav', kw: 'network phone av computer', items: [
        ['Telephone handset', 'phone call', '📞'],
        ['Fax (handset + f)', 'facsimile', '📠'],
        ['Camcorder', 'video camera', '📹'],
        ['Monitor / CRT', 'screen display', '🖥️'],
        ['Handset with cord', 'wall phone', '☎️'],
        ['Camera', 'photo', '📷'],
        ['Printer / fax machine', 'paper output', '🖨️'],
        ['Laptop', 'notebook', '💻'],
        ['Network (three computers)', 'lan ethernet', '🖥️'],
        ['Desk telephone', 'landline', '☎️'],
        ['Play / rewind triangle', 'media pointer', '◀️'],
      ]},
      { id: 'miscellaneous', name: 'Miscellaneous', group: 'Basic', key: 'Nav', kw: 'punctuation currency math', items: [
        ['Question mark', 'help', '?'],
        ['Inverted question mark', 'spanish', '¿'],
        ['Inverted exclamation', 'spanish', '¡'],
        ['Semicolon', 'pause', ';'],
        ['Less than', 'angle left', '<'],
        ['Greater than', 'angle right', '>'],
        ['Left square bracket', 'bracket', '['],
        ['Right square bracket', 'bracket', ']'],
        ['Caret / circumflex', 'hat power', '^'],
        ['Left curly brace', 'brace', '{'],
        ['Right curly brace', 'brace', '}'],
        ['Vertical bar', 'pipe', '|'],
        ['Tilde', 'approx', '~'],
        ['Superscript 2', 'squared', '²'],
        ['Pound sterling', 'gbp currency', '£'],
        ['Euro', 'currency', '€'],
        ['Turkish lira', 'currency try', '₺'],
      ]},
      { id: 'miscellaneous-ru', name: 'Miscellaneous (Russian keypad)', group: 'Basic', key: 'Nav', kw: 'cyrillic punctuation russian', items: [
        ['Hyphen / minus', 'dash', '-'],
        ['Plus', 'add', '+'],
        ['Equals', 'equal', '='],
        ['Exclamation', 'bang', '!'],
        ['At', 'email', '@'],
        ['Hash', 'number pound', '#'],
        ['Dollar', 'currency', '$'],
        ['Percent', 'ratio', '%'],
        ['Ampersand', 'and', '&'],
        ['Asterisk', 'star', '*'],
        ['Left parenthesis', 'paren', '('],
        ['Right parenthesis', 'paren', ')'],
        ['Colon', 'ratio', ':'],
        ['Comma', 'pause', ','],
        ['Period', 'dot', '.'],
        ['Quotation mark', 'quote', '"'],
        ['Slash', 'solidus', '/'],
        ['Backslash', 'reverse solidus', '\\'],
        ['Degree', 'angle temperature', '°'],
        ['Underscore', 'low line', '_'],
        ['Plus-minus', 'tolerance', '±'],
        ['Apostrophe', 'prime', "'"],
        ['Omega', 'ohm greek', 'Ω'],
        ['Cyrillic Yo (capital)', 'russian Ё', 'Ё'],
        ['Cyrillic yo (small)', 'russian ё', 'ё'],
        ['Cyrillic Ya (capital)', 'russian Я', 'Я'],
        ['Cyrillic ya (small)', 'russian я', 'я'],
      ]},
      { id: 'greek', name: 'Greek', group: 'Basic', key: 'Nav', kw: 'alphabet omega mu sigma', items: [
        ['Alpha', 'α', 'α'], ['Beta', 'β', 'β'], ['Gamma (capital)', 'Γ', 'Γ'], ['Upsilon (capital)', 'Υ', 'Υ'],
        ['Delta (capital)', 'Δ', 'Δ'], ['Delta (small)', 'δ', 'δ'], ['Epsilon', 'ε', 'ε'], ['Zeta', 'ζ', 'ζ'],
        ['Eta', 'η', 'η'], ['Theta (capital)', 'Θ', 'Θ'], ['Theta (small)', 'θ', 'θ'], ['Iota', 'ι', 'ι'],
        ['Kappa', 'κ', 'κ'], ['Lambda (capital)', 'Λ', 'Λ'], ['Lambda (small)', 'λ', 'λ'], ['Mu', 'μ micro', 'μ'],
        ['Nu', 'ν', 'ν'], ['Xi (capital)', 'Ξ', 'Ξ'], ['Xi (small)', 'ξ', 'ξ'], ['Pi (capital)', 'Π', 'Π'],
        ['Pi (small)', 'π', 'π'], ['Rho', 'ρ', 'ρ'], ['Sigma (capital)', 'Σ sum', 'Σ'], ['Final sigma', 'ς', 'ς'],
        ['Sigma (small)', 'σ', 'σ'], ['Tau', 'τ', 'τ'], ['Upsilon (small)', 'υ', 'υ'], ['Phi (capital)', 'Φ', 'Φ'],
        ['Phi (small)', 'φ', 'φ'], ['Chi', 'χ', 'χ'], ['Psi (capital)', 'Ψ', 'Ψ'], ['Psi (small)', 'ψ', 'ψ'],
        ['Omega (capital)', 'Ω ohm', 'Ω'], ['Omega (small)', 'ω', 'ω'],
        ['Alpha with tonos', 'ά', 'ά'], ['Epsilon with tonos', 'έ', 'έ'], ['Eta with tonos', 'ή', 'ή'],
        ['Iota with tonos', 'ί', 'ί'], ['Omicron with tonos', 'ό', 'ό'], ['Upsilon with tonos', 'ύ', 'ύ'],
        ['Omega with tonos', 'ώ', 'ώ'],
      ]},
      { id: 'lab', name: 'Lab', group: 'Pictograph', key: 'Nav', kw: 'laboratory iso 15223 sterile ivd medical', items: [
        ['Humidity limitation', 'moisture percent wave', '%'],
        ['Do not reuse', 'single use 2 slash', '🚫'],
        ['Fluid path / bidirectional', 'arrows circle', '↔'],
        ['Temperature limit', 'thermometer', '🌡️'],
        ['Keep frozen / ice pack', 'cold brick', '🧊'],
        ['Keep away from sunlight', 'UV lamp rays', '☀️'],
        ['Keep away from heat / explosive', 'burst heat', '💥'],
        ['Do not get wet (box, rain, slash)', 'keep dry', '🚫'],
        ['Keep dry (umbrella)', 'rain', '☔'],
        ['Fragile', 'wine glass', '🍷'],
        ['Biohazard', 'biological', '☣️'],
        ['Protective footwear', 'boot shoe', '🥾'],
        ['No open flame', 'fire prohibited', '🚫'],
        ['No smoking', 'cigarette slash', '🚭'],
        ['Emergency eyewash', 'eye water plus', '👁️'],
        ['Safety shower', 'person drench plus', '🚿'],
        ['First aid', 'cross', '➕'],
        ['Telephone', 'handset', '📞'],
        ['Eyewash station', 'eye plus fountain', '👁️'],
        ['No eating / drinking', 'hand to mouth slash', '🚫'],
        ['Medical / pharmacy', 'caduceus plus', '⚕️'],
        ['Use a ladder', 'ladder climb', '🪜'],
        ['STERILE', 'sterile', 'STERILE'],
        ['STERILE A (aseptic)', 'sterile a', 'STERILE A'],
        ['STERILE EO (ethylene oxide)', 'eo', 'STERILE EO'],
        ['STERILE R (irradiation)', 'r', 'STERILE R'],
        ['STERILE I (irradiation)', 'i', 'STERILE I'],
        ['CONTROL', 'control', 'CONTROL'],
        ['CONTROL −', 'control minus', 'CONTROL-'],
        ['CONTROL +', 'control plus', 'CONTROL+'],
        ['IVD (in vitro diagnostic)', 'ivd', 'IVD'],
        ['LOT', 'batch lot', 'LOT'],
        ['REF (catalogue number)', 'reference', 'REF'],
        ['SN (serial number)', 'serial', 'SN'],
        ['IN ANALYSIS', 'testing', 'IN ANALYSIS'],
        ['CONFIDENTIAL', 'private', 'CONFIDENTIAL'],
        ['Female', 'venus', '♀'],
        ['Male', 'mars', '♂'],
        ['Batch / recycle arrows', 'circular arrows', '♻️'],
        ['Return / undo', 'arrow back', '↩️'],
        ['Forward / redo', 'arrow next', '↪️'],
        ['Keep frozen (snowflake, box, arrow)', 'cold chain', '❄️'],
        ['Restroom', 'woman man', '🚻'],
        ['Consult instructions for use', 'book i', 'ℹ️'],
        ['Patient number', 'person hash', '#'],
        ['Data / chart', 'graph', '📈'],
        ['Biological substance / culture', 'flask petri', '🧫'],
        ['Plant / environmental', 'leaves', '🌿'],
        ['Magnetic field', 'horseshoe magnet triangle', '🧲'],
        ['Hot surface', 'heat waves triangle', '♨️'],
        ['Laser radiation', 'sunburst triangle', '☢️'],
        ['Recycle', 'möbius loop', '♻️'],
        ['Eye protection', 'goggles', '🥽'],
        ['Respiratory protection', 'gas mask', '😷'],
        ['Face mask', 'surgical mask', '😷'],
      ]},
    ],
    accented: {
      image: 'img/symbols/accented.png',
      howto: [
        'Position the cursor.',
        'Press [International] ([Alt] + [6]), or [Menu] → {International} → [Enter].',
        'Navigate to the character, then [Enter].',
        'The printer does not print a full accent table in this manual. Only the LCD picker (A / a / C rows are shown). Greek letters are also under International, not Language. Coverage depends on printer version.',
      ],
      table: {
        A: 'Á À Â Ä Ã Ą Ă',
        a: 'á à â ä ã ą æ',
        C: 'Ç Č Ć',
      },
    },
  },

  frames: {
    howto: [
      'The M210 has no decorative frame catalog. Labels print without a Brother-style border.',
      'Layout is controlled by [Label Type] (Banner, Flag, WireMarker, …), not a Frame key.',
    ],
    notes: [
      'There are no numbered frames on this printer. The empty “Off” tile is the honest catalog: plain print.',
      'Text is center-justified. Horizontal vs vertical is a Banner / Vial / Flag option, not a frame.',
    ],
    items: [
      ['off', 'No frame (M210 prints plain)', 'none off plain industrial'],
    ],
  },

  templates: {
    notes: [
      'These are Brady Label Types, not Brother text/pattern templates. Press [Label Type], pick the application, then fill its data fields.',
      'M210 / M210-Russian: Banner Portrait, Banner Landscape, Fixed Length, Custom Length, Vial, WireMarker, Terminal Block, Patch Panel, Panel Residential, Flag, Breaker Box.',
      'M210-LAB: Banner Portrait, Banner Landscape, Custom Length, Fixed Length, Vial only.',
      'The menu only lists types that work with the installed cartridge. SelfLam: Banner Landscape, Fixed Length, Wire. Permasleeve: Banner Landscape, Fixed Length. 2D codes need 0.75" media and Banner Landscape.',
      'Clearing data keeps the label type. To return to general editing pick Banner Portrait.',
    ],
    textHowto: [
      'Press [Label Type].',
      'Use [▲] / [▼] to the type, then [Enter].',
      'Fill any data fields (length, vial size, spacing, rotation, …) and press [Enter].',
      'Type the label. [Print]. Cut with the cutter lever after the print icon goes away.',
    ],
    patternHowto: [
      'The M210 has no decorative pattern-tape library.',
      'Repeating content is WireMarker (text repeated down the sleeve) or serialization, not a pattern catalog.',
    ],
    text: [
      [1, 'Banner Portrait', 'banner vertical general editing', 'Default editing mode. Horizontal: max four lines, “Cannot Fit” if a line is too long. Vertical: four lines, 50 characters each. Vertical is the only option on pre-sized labels. Not for SelfLam or Permasleeve.'],
      [2, 'Banner Landscape', 'banner long string wrap', 'Long text string on any media. Fallback type when the cartridge cannot use the previous type. Horizontal: four lines × 50 characters. Vertical: four lines, “Cannot Fit” if a line is too long. Horizontal only on pre-sized labels. Required for Datamatrix / QR.'],
      [3, 'Fixed Length', 'fixed length cannot fit', 'Pick a preset length. Extra text raises {Cannot Fit}. The print-head-to-cutter margin cannot be removed.'],
      [4, 'Custom Length', 'custom length 99.9', 'Type a length up to 99.9" (2537 mm), 50 characters max. Text is centered. Extra text raises {Cannot Fit}.'],
      [5, 'Vial', 'vial tube lab 2d', 'Fixes length from the vial size. Landscape or portrait. Any media except SelfLam / Permasleeve. 2D barcode recommended for dense data. Pre-sized media sets width automatically.'],
      [6, 'WireMarker (M210)', 'wire marker repeat sleeve', 'Repeats the text down the label to match the chosen wire size (W.75, W1.5, W2.0, …). Not on Permasleeve. Repeats do not show on the LCD, only on the print. [Enter] adds a second line; both lines repeat.'],
      [7, 'Terminal Block (M210)', 'terminal block spacing serial', 'Not on SelfLam / Permasleeve. Spacing 0.2"–40", serialization on/off, # of terminations, rotation 0° or 90°. One strip covers the block if spacing is right.'],
      [8, 'Patch Panel (M210)', 'patch panel ports serial', 'Same data fields as Terminal Block, with # of Ports instead of terminations. Landscape or 90° portrait print.'],
      [9, 'Panel Residential (M210)', 'breaker door ac bedroom kitchen', '30 pre-named 15-character labels (A/C, Alarm, Basement, bathrooms, bedrooms, kitchen appliances, …). Best on 0.25" / 9 pt. Print all 30 or pick Yes/No per name. Left-justified, fixed width. Portrait if more than one line.'],
      [10, 'Flag (M210)', 'flag wrap cable', 'Wraps a cable; ends form a flag. Flag length + cable diameter (0.01"–9.99", default 0.25") + one of eight rotations. Not SelfLam / Permasleeve. One-text flags duplicate and rotate the text; two-text flags have Area 01 / Area 02.'],
      [11, 'Breaker Box (M210)', 'breaker panel poles partition', 'Spacing = breaker width, # of breakers, partition on/off, rotation 0° or 90°. Then poles and identifier per breaker. Prints one continuous strip (US vertical / EU horizontal).'],
    ],
    pattern: [],
  },

  howto: [
    { id: 'label-type', title: 'Pick a label type', kw: 'label type template banner vial wire flag',
      steps: ['Press [Label Type].', 'Use [▲] / [▼] to the type that matches the job and the cartridge, then [Enter].', 'Fill data fields if shown, then [Enter].', 'To leave a special type and return to general editing, pick {Banner Portrait}.'],
      notes: ['Types that the cartridge cannot use are hidden. SelfLam → Banner Landscape, Fixed Length, Wire. Permasleeve → Banner Landscape, Fixed Length.'] },
    { id: 'font', title: 'Font size and Bold', kw: 'font size bold autosize 6 9 14 20 28 40',
      steps: ['Press [Font Size].', 'Navigate to Auto, a point size, or the Bold variant, then [Enter].'],
      notes: ['One typeface. Size applies to the whole label. Autosize shows {A} and shrinks until [Enter] or the minimum. Default 9 pt. Some symbols need 9 pt or larger.'] },
    { id: 'symbol', title: 'Insert a symbol', kw: 'symbol graphic warning electrical lab',
      steps: ['Press [Symbol] ([Alt] + [1]).', 'Pick the category → [Enter].', 'Pick the glyph → [Enter].'],
      notes: ['Last category is remembered. See the Symbols section for every printed Appendix A cell.'] },
    { id: 'barcode', title: 'Code 39 / Code 128', kw: 'barcode 39 128 human readable',
      steps: ['Use Banner Landscape or Flag.', 'Press [Barcode] ([Alt] + [2]).', 'Pick {39} or {128} → [Enter].', 'Type the data. [Font Size] scales the bars with the human-readable line (always below, cannot be removed).', 'Move right off the box to stop editing the barcode.'],
      notes: ['Allowed characters are in Appendix B. No checksum. One serialized set can sit inside a barcode.'] },
    { id: '2d', title: 'Datamatrix and QR', kw: 'datamatrix qr 2d square',
      steps: ['Install 0.75" (19.1 mm) media. Set {Banner Landscape}.', 'Press the 2D key (next to Barcode on the pad).', 'Pick Datamatrix or QR, small or large → [Enter].', 'Type up to 44 characters (Datamatrix) or 50 (QR). Sizes are fixed. Font size does not change them.'],
      notes: ['Minimum readable diameter for a Brady scanner is 0.59" (15 mm). Multiple lines of text/codes are not supported.'] },
    { id: 'serial', title: 'Serialization', kw: 'serial sequence increment start end',
      steps: ['Press [Serial] ([Alt] + [Menu]).', 'Enter Start, Increment (not 0; default 1) and End → [Enter].', 'Letters A–Z use alphabetic order; increment is still a number. Do not mix letters and digits in one sequence. Up to three letters (AB…BB rolls the left character).'],
      notes: ['Simple sequences only. One serialized set per file. Edit later with [Serial] from anywhere on the label. [Backspace] on the start value can delete the whole sequence (confirm {Delete Serial?}).'] },
    { id: 'files', title: 'Save, open, delete (12 files)', kw: 'file save open delete memory',
      steps: ['Save: [Menu] → {File} → [Enter] → {Save} → [Enter] → empty slot → [Enter] → name (11 chars) → [Enter].', 'Overwrite: pick an occupied slot → {Yes} → new name.', 'Open: [Menu] → {File} → {Open} → slot → [Enter] (unsaved screen data is lost).', 'Delete: [Menu] → {File} → {Delete} → slot → {Yes}. [Backspace] leaves the list.'],
      notes: ['Files survive battery removal. Two files may share a name; slots 1–12 distinguish them. No PC connection.'] },
    { id: 'print', title: 'Print, Multi-Print and cut', kw: 'print copies cut lever multi-print',
      steps: ['Press [Print]. A print icon and remaining-supply gauge show until the job finishes.', 'Squeeze the cutter levers. Plastic grips hold the label in the chute. Pull it out.', 'Copies: [Multi-Print] ([Alt] + [Print]) → Copies: → [Enter]. Cut between labels or press [Print] again to keep going.', 'Job-wide cut behaviour: [Menu] → {Cut Mode} → {Cut Between Labels} / {Cut at End of Job}.'] },
    { id: 'clear', title: 'Clear vs Backspace', kw: 'clear backspace cancel',
      steps: ['[Backspace] deletes one character to the left and also backs out of menus.', '[Clear] ([Alt] + [Backspace]) wipes data but keeps font size and label type.'] },
    { id: 'lines', title: 'Multiple lines', kw: 'enter line four cannot fit',
      steps: ['[Enter] starts a new line (max four).', 'Do not press [Enter] at the end of a line unless you want another line. A blank line still counts.'],
      notes: ['Pre-sized labels may allow fewer than four. “Cannot Fit” means shrink the font, delete text, or change type/orientation.'] },
    { id: 'units-clock', title: 'Units, clock, zero style, backlight', kw: 'units inch mm clock date time zero backlight',
      steps: ['Units: [Menu] → {Units} → inches or mm.', 'Clock: [Menu] → {Set Clock} → Clock Format (12/24), Date Format (MM/DD/YY or DD/MM/YY, 2- or 4-digit year), Time Format, then Date and Time.', 'Zero: [Menu] → {Set Zero Style} → open 0 or slashed zero.', 'Backlight: [Menu] → {Backlight Time} → 5–30 s, Always On (AC), or Always Off. [Alt] + [Space] toggles the lamp.'] },
    { id: 'language', title: 'Language', kw: 'language setup first run',
      steps: ['On first power-up go to [Menu] → {Language} (6th item; the word is already in the current language).', 'Pick the language → [Enter].'],
      notes: ['If you mash keys during setup and cannot change language, reset language from that same menu (see Troubleshooting).'] },
    { id: 'cartridge', title: 'Change the M21 cartridge', kw: 'cartridge m21 authentic lock eject',
      steps: ['Turn the lock left to horizontal (unlock).', 'Press the rear eject button and lift the cartridge out.', 'Drop a Brady Authentic M21 cartridge in until it snaps. Turn the lock right to vertical.', 'Unlock when you finish a run so the warm head does not burn a line onto the next label.'] },
    { id: 'power', title: 'Batteries and adapter', kw: 'battery aa lithium adapter charge',
      steps: ['Six new AA alkaline in the back compartment (finger tabs). Do not mix used/new, and do not use rechargeable AA or Ultimate Lithium AA.', 'Optional M210-BATTERY: label down, elongated end into the bottom slot. Charge only on the M210-AC adapter outside the printer. To print while charging, put AA cells in the printer.', 'Optional 9 V Brady adapter in the left-side jack powers the printer but does not charge the pack inside.'] },
    { id: 'clean', title: 'Clean print head, roller and sensor', kw: 'clean isopropyl print head platen sensor',
      steps: ['Power off. Unlock and remove the cartridge.', 'Blow the sensor with compressed air or a lint-free swab.', 'Swab the print head and platen with isopropyl alcohol (or Brady PCK-6).', 'LCD: soft cloth, light isopropyl.'] },
  ],

  errors: [
    ['Error', 'Low battery, wrong media, or motor fault.', 'Fit six new AA cells, or recharge the Li-ion pack on the adapter (use AA in the printer while it charges). Fit a Brady Authentic cartridge. If it stays up, send the printer for repair.'],
    ['Cannot Fit', 'Font, lines or length will not fit. Some symbols cannot print at 6 pt. A blank line counts. Wrong type/orientation (e.g. WireMarker instead of Banner).', 'Smaller font, delete text, drop extra [Enter]s, switch to Banner Landscape, or lengthen a fixed/custom label. For symbols use 9 pt or larger.'],
    ['No / Invalid Cartridge', 'Empty bay, non-Authentic cartridge, or damaged smart cell.', 'Fit a cartridge with the Authentic A logo. [CLEAR/ESC] to dismiss.'],
    ['Insert labels', 'Damaged contacts in the receiver slot.', 'Contact Brady Technical Support.'],
    ['Check Cartridge / Lever', 'Lock not engaged, cartridge empty, or jam.', 'Lock vertical. New cartridge. Unlock, pull the cartridge, cut off the damaged leader, reinsert.'],
    ['Cut while printing', 'Cutter used during a job.', 'Finish the cut through the material. [Clear] the error. Reprint.'],
    ['Invalid terminal repeat value', 'Spacing out of range.', 'Enter 0.2" (5.08 mm) to 40" (1016 mm).'],
  ],
  problems: [
    ['Printer does not power up', 'Charge or replace the pack, or install six new AA cells. To print while the Li-ion pack charges on the adapter, put AA cells in the printer.'],
    ['Screen freezes', 'Power off. If Power does nothing, unplug the adapter, pull the pack/cells, reseat, power on.'],
    ['LCD reverts to the previous label', 'Battery is low. Replace or recharge.'],
    ['Printer powers off often', 'Auto-off is 10 minutes idle. Fit fresh AA or the AC adapter. Charge Li-ion outside the printer.'],
    ['Poor print / voids / wrinkles', 'Worn cells, dirty head (clean with alcohol), unusable media, crease in the tape (advance past it), or wrinkled ribbon (unlock, turn the take-up spool clockwise 1–2 turns).'],
    ['Black line on the first label of a run', 'Cartridge was left locked, so the warm head sat on the ribbon. Unlock as soon as you finish printing.'],
    ['Will not feed / Print does nothing', 'Cut a straight leader. Confirm the lock is vertical. Clear the exit chute. Try another cartridge.'],
    ['Compressed print / bad registration', 'Remove the last cut label from the tray. Clean the platen.'],
    ['Cutter does not cut', 'Tweezers or needle-nose pliers for slivers, never fingers. Sharp cutter parts.'],
    ['Jam, cannot feed', 'Unlock (force if needed; unlock retracts the platen), remove the cartridge, clear with tweezers. Do not scratch the print head with metal.'],
    ['Keys stuck or dead', 'Find a key jammed down and press it free.'],
    ['Left/right justification does nothing', 'Not supported. Everything prints centered. No action.'],
    ['Human-readable barcode text cannot move / no checksum', 'Fixed below the bars. Checksum is not offered.'],
    ['Menu hides some label types', 'The cartridge decides. Nylon/vinyl/polyester continuous: all types. SelfLam: Banner Landscape, Fixed Length, Wire. Permasleeve: Banner Landscape, Fixed Length. 2D codes: 0.75" only.'],
    ['Datamatrix / QR will not enter', 'Set Banner Landscape (not Portrait) and 0.75" media.'],
    ['Pre-sized text is shifted', 'Debris on the sensor. Remove the cartridge and blow it off.'],
    ['Cannot change language', 'Wrong key during setup. [Menu] → {Language} and set it again.'],
    ['Want a PC connection', 'There is none. The M210 cannot print PC files. Brady sells other printers that can.'],
  ],
  tips: [
    'Banner Portrait is the escape hatch: pick it to drop another type’s parameters and return to general editing.',
    'Unlock the cartridge when you walk away. A locked warm head burns a vertical line on the next label.',
    'Autosize ({A} in the status bar) is the fastest way to pack a line without hitting Cannot Fit.',
    'WireMarker repeats only on the print, not the LCD. Print a sample before a long run.',
    'One serialized sequence per file; you can drop that sequence into a barcode.',
    'Panel Residential’s 30 names are listed in order under that label type; 9 pt on 0.25" media fits a standard residential door.',
    'Keep AA cells in the printer as a working power source while the Li-ion pack charges on the adapter. The pack will not charge inside the printer.',
  ],
};
