// Brother P-touch PT-D610BT. Reference data for Labelarium.
// Source: official User's Guide (Version A, 2022, 154 pp).
// Catalog counts are from this guide's printed tables (not D210/D220).
// Notation in steps: [Key] = a key on the device, {Text} = what the LCD shows, → = then.
// Symbol items: [name, keywords, unicode approximation]. Position (1-based) = order in the category.
export default {
  id: 'brother-pt-d610bt',
  brand: 'Brother',
  model: 'PT-D610BT',
  name: 'P-touch PT-D610BT',
  tagline: 'Professional Label Maker with Bluetooth',
  links: [
    ['Official support, FAQs & manuals', 'https://support.brother.com/g/b/manualtop.aspx?c=us&lang=en&prod=d610bteus'],
    ['Product support', 'https://support.brother.com/g/b/producttop.aspx?c=us&lang=en&prod=d610bteus'],
  ],
  specs: [
    ['Tape', 'Brother TZe laminated tape, 3.5 / 6 / 9 / 12 / 18 / 24 mm (0.13" / 0.23" / 0.35" / 0.47" / 0.70" / 0.94")'],
    ['Print', 'Thermal transfer, about 30 mm/s (1.18"/s). Max print height 18.0 mm (0.71") on 24 mm tape'],
    ['Text', 'Up to 280 characters per label, 99 file slots. Colour LCD (320 × 120 dpi)'],
    ['Fonts', '17 fonts · 9 sizes (Auto + 6–48 pt) · 5 widths · 17 styles · 4 alignments'],
    ['Decorations', '167 printed frames in 5 categories (Brother lists 160) · 37 Auto Format templates · 43 block layouts'],
    ['Symbols', '26 categories. 702 individually cropped glyphs + circled 1–99 + boxed 1–99 (Brother lists 900)'],
    ['Memory', '99 saved labels, 280 characters each. Symbol History stores the last 30 symbols'],
    ['Power', '6 × AA alkaline (LR6). AC adapter AD-E001A. Batteries back up memory'],
    ['Auto power off', 'Battery: 5 / 10 / 30 min. AC adapter: 1 / 2 / 4 / 8 hr'],
    ['Size / weight', '202 × 87 × 199 mm (7.95" × 3.42" × 7.83"), about 990 g without batteries and cassette'],
    ['Cutter', 'Automatic full cutter. Clean the blade about once a year with isopropyl alcohol'],
    ['Wireless', 'Bluetooth 5.0 (SPP / iAP2). USB 2.0 Full Speed, Micro-B'],
  ],
  tapes: [
    { mm: 3.5, in: '0.13"', lines: 1, note: 'Single line only.' },
    { mm: 6, in: '0.23"', lines: 2, note: 'Up to 2 lines.' },
    { mm: 9, in: '0.35"', lines: 2, note: 'Up to 2 lines.' },
    { mm: 12, in: '0.47"', lines: 3, note: 'Up to 3 lines. Some templates need this width.' },
    { mm: 18, in: '0.70"', lines: 5, note: 'Up to 5 lines. Some templates need this width.' },
    { mm: 24, in: '0.94"', lines: 7, note: 'Up to 7 lines. Full print height 18 mm. Most Auto Format templates.' },
  ],
  keyboard: {
    image: 'img/keyboard.png',
    legend: [
      [1, 'Power', 'On / off.'],
      [2, 'Home / Bluetooth', 'Return to the Home Screen. Shift + Home toggles Bluetooth.'],
      [3, 'Clear', 'Clear all text and print settings. Opens Text Only / Text & Format.'],
      [4, 'Escape', 'Cancel the current operation, leave preview, back out of menus.'],
      [5, 'Cursor', 'Move the cursor. Shift + up/down jumps a block; Shift + left/right jumps to the start / end of the line.'],
      [6, 'OK', 'Confirm a menu choice.'],
      [7, 'Function (Fn)', 'Function menu (Frame, Barcode, Length, Cut Option, Save, Tab Length). Shift + Fn shows character attributes.'],
      [8, 'Preview / Feed & Cut', 'Preview the label. Shift + Preview opens Feed & Cut / Feed Only.'],
      [9, 'Print / Print Options', 'Print. Shift + Print opens Numbering / Mirror.'],
      [10, 'Backspace', 'Delete the character to the left of the cursor.'],
      [11, 'Shift (right)', 'Upper case for one letter, symbols on number keys, and Shift combos.'],
      [12, 'Enter', 'New line (tape width allowing) and confirm in some menus.'],
      [13, 'Accent', 'Cycle accented versions of the letter you typed.'],
      [14, 'Space', 'Space. Inside a setting: return that setting to its default.'],
      [15, 'Symbol', 'Insert a symbol from History or a category.'],
      [16, 'Scale / Zoom', 'Change preview magnification.'],
      [17, 'Shift (left)', 'Same as the right Shift key.'],
      [18, 'Caps', 'Toggle ALL CAPS. Caps indicator on the LCD.'],
      [19, 'Tab', 'Insert a tab.'],
    ],
  },
  shortcuts: [
    { keys: '[Home] → {Create Label}', action: 'Start a new label (up to 280 characters)', kw: 'create new label text' },
    { keys: '[Home] → {Auto Format}', action: 'Templates, Block Layouts and Table Format', kw: 'template block table auto format' },
    { keys: '[Home] → {File}', action: 'Print, Open, Delete or Mark a saved label (99 slots)', kw: 'file memory save open' },
    { keys: '[Home] → {Settings}', action: 'Language, Unit, Auto Power Off, Bluetooth, Tape Colour, Input Mode, Adjustment, Clock, Reset', kw: 'settings language bluetooth' },
    { keys: '[Shift] + [Home]', action: 'Toggle Bluetooth on or off from the Home Screen', kw: 'bluetooth wireless' },
    { keys: '[Shift] + [Fn]', action: 'Character attributes (Font, Size, Width, Style, Alignment)', kw: 'font size width style alignment' },
    { keys: '[Fn] → {Frame}', action: 'Pick a frame by category or by typing its number', kw: 'frame border' },
    { keys: '[Fn] → {Barcode}', action: 'Insert a barcode (CODE39, CODE128, EAN, UPC, ITF, CODABAR, GS1-128)', kw: 'barcode' },
    { keys: '[Fn] → {Length}', action: 'Label length Auto or 30–300 mm (1.2"–12")', kw: 'label length' },
    { keys: '[Fn] → {Cut Option}', action: 'Small Margin / Large Margin / Chain / No Cut / Special Tape', kw: 'cut margin chain' },
    { keys: '[Fn] → {Tab Length}', action: 'Tab length 0–100 mm (0–4.0")', kw: 'tab' },
    { keys: '[Fn] → {Save}', action: 'Save the current label to one of 99 file slots', kw: 'save memory file' },
    { keys: '[Shift] + [Preview]', action: 'Feed & Cut or Feed Only', kw: 'feed tape cut' },
    { keys: '[Shift] + [Print]', action: 'Print Options: Numbering or Mirror', kw: 'numbering serial mirror' },
    { keys: '[Shift] + [◀] / [▶]', action: 'Jump to the start / end of the current line', kw: 'cursor jump' },
    { keys: '[Shift] + [▲] / [▼]', action: 'Jump to the previous / next block', kw: 'block cursor' },
    { keys: '[Space] (inside any setting)', action: 'Return that setting to its default', kw: 'default reset auto' },
    { keys: '[Esc]', action: 'Cancel, leave preview, back out of menus', kw: 'cancel escape' },
    { keys: '[Shift] + digit', action: 'Type the symbol printed above the digit', kw: 'punctuation' },
    { keys: 'letter → [Accent]', action: 'Cycle accented letters, [OK] to insert', kw: 'accent umlaut tilde' },
    { keys: '[Enter]', action: 'New line (up to 7 lines on 24 mm tape)', kw: 'enter newline' },
    { keys: '[Print] → digit', action: 'Set number of copies (up to 99)', kw: 'copies print' },
  ],
  fonts: [
    ['Helsinki', 'helsinki.png', 'Clean sans-serif. LCD: HEL.', '"Helvetica Neue", Helvetica, Arial, sans-serif', 400, 'normal'],
    ['Dortmund', 'dortmund.png', 'Heavy condensed sans. LCD: DTM. Some regions only.', 'Impact, "Arial Narrow", sans-serif', 800, 'normal'],
    ['Brussels', 'brussels.png', 'Classic serif. LCD: BRU.', 'Georgia, "Times New Roman", serif', 400, 'normal'],
    ['Cooperstown', 'cooperstown.png', 'Copperplate-like caps. LCD: COP. Some regions only.', 'Copperplate, "Copperplate Gothic", serif', 600, 'normal'],
    ['Atlanta', 'atlanta.png', 'Humanist sans. LCD: ATL.', 'Optima, Futura, "Gill Sans", sans-serif', 500, 'normal'],
    ['US', 'us.png', 'Light serif. LCD: US. Some regions only.', '"Times New Roman", Times, serif', 300, 'normal'],
    ['Los Angeles', 'los-angeles.png', 'Heavy display sans. LCD: LA. Some regions only.', 'Impact, "Arial Black", sans-serif', 900, 'normal'],
    ['San Diego', 'san-diego.png', 'High-contrast serif. LCD: SGO. Some regions only.', '"Bodoni 72", Didot, Georgia, serif', 400, 'normal'],
    ['Florida', 'florida.png', 'Heavy rounded sans. LCD: FLO. Some regions only.', '"Arial Rounded MT Bold", Helvetica, sans-serif', 800, 'normal'],
    ['Calgary', 'calgary.png', 'Script / handwriting. LCD: CAL. Some regions only.', '"Snell Roundhand", "Brush Script MT", cursive', 400, 'italic'],
    ['Belgium', 'belgium.png', 'Squared technical sans. LCD: BEL. Some regions only.', '"Avenir Next Condensed", "Arial Narrow", sans-serif', 700, 'normal'],
    ['Adams', 'adams.png', 'Narrow bold sans. LCD: ADM. Some regions only.', '"Arial Narrow", Helvetica, sans-serif', 700, 'normal'],
    ['Brunei', 'brunei.png', 'Bold italic display. LCD: BRN. Some regions only.', '"Arial Black", Impact, sans-serif', 900, 'italic'],
    ['Sofia', 'sofia.png', 'Extra-bold condensed. LCD: SOF.', '"Futura Condensed ExtraBold", "Arial Narrow", sans-serif', 900, 'normal'],
    ['Germany', 'germany.png', 'Blackletter. LCD: GER. Some regions only.', '"Old English Text MT", UnifrakturMaguntia, fantasy', 400, 'normal'],
    ['Letter Gothic', 'letter-gothic.png', 'Monospace. LCD: LGO.', '"Letter Gothic", Consolas, "Courier New", monospace', 400, 'normal'],
    ['Istanbul', 'istanbul.png', 'Bold grotesque sans. LCD: IST. Some regions only.', '"Helvetica Neue", Arial, sans-serif', 900, 'normal'],
  ],
  sizes: [['Auto', 'size-auto.png', 1], ['6 pt', 'size-6.png', 0.125], ['9 pt', 'size-9.png', 0.1875], ['12 pt', 'size-12.png', 0.25], ['18 pt', 'size-18.png', 0.375], ['24 pt', 'size-24.png', 0.5], ['36 pt', 'size-36.png', 0.75], ['42 pt', 'size-42.png', 0.875], ['48 pt', 'size-48.png', 1]],
  widths: [['x 1', 'width-x1.png', 1], ['x 3/2', 'width-x32.png', 1.5], ['x 2', 'width-x2.png', 2], ['x 1/2', 'width-half.png', 0.5], ['x 2/3', 'width-x23.png', 0.666]],
  styles: [
    ['Normal', 'style-normal.png'], ['Bold', 'style-bold.png'], ['Underline', 'style-underline.png'], ['Underline Bold', 'style-underline-bold.png'],
    ['Strikeout', 'style-strikeout.png'], ['Outline', 'style-outline.png'], ['Shadow', 'style-shadow.png'], ['Solid', 'style-solid.png'],
    ['Italic', 'style-italic.png'], ['Italic Bold', 'style-italic-bold.png'], ['Underline + Italic', 'style-underline-italic.png'],
    ['Underline + Bold + Italic', 'style-underline-bold-italic.png'], ['Italic Outline', 'style-italic-outline.png'],
    ['Italic Shadow', 'style-italic-shadow.png'], ['Italic Solid', 'style-italic-solid.png'], ['Vertical', 'style-vertical.png'],
    ['Vertical Bold', 'style-vertical-bold.png'],
  ],
  alignments: [['Left', 'align-left.png'], ['Center', 'align-center.png'], ['Right', 'align-right.png'], ['Justify', 'align-justify.png']],
  fontNote: 'When Auto size is selected the text is fitted to the largest size that still works for the tape width. Some fonts are available only in some countries. Auto Fit Style (Settings) can shrink size or width so a fixed-length label still fits.',

  symbols: {
    howto: [
      'Press [Symbol].',
      'Use [▲] / [▼] to choose a category (or {History} of the last 30 symbols), then [OK].',
      'Use [▲] [▼] [◀] [▶] to move to the symbol (positions below count from the left / top), then [OK].',
      'To cancel at any point press [Esc].',
    ],
    categories: [
      { id: "punctuation", name: "Punctuation", group: "Basic", key: "a/b", kw: "period comma colon punctuation",
        items: [
        ["Period", "dot full stop", "."], ["Comma", "comma", ","], ["Colon", "colon", ":"], ["Semicolon", "semicolon", ";"],
        ["Quotation marks", "quotes double quote", "\""], ["Apostrophe", "quote single", "'"], ["Bullet", "dot", "•"],
        ["Question mark", "question", "?"], ["Exclamation mark", "exclamation", "!"],
        ["Inverted question mark", "spanish question", "¿"], ["Inverted exclamation mark", "spanish exclamation", "¡"],
        ["Hyphen / minus", "dash hyphen minus", "−"], ["Ampersand", "and", "&"], ["Tilde", "tilde approximately", "~"],
        ["Underscore", "underline underscore", "_"], ["Backslash", "backslash", "\\"], ["Slash", "slash divide", "/"],
        ["Asterisk", "star times", "*"], ["At", "at email", "@"], ["Hash", "number pound", "#"]
        ],
      },
      { id: "bracketarrow", name: "BracketArrow", group: "Basic", key: "a/b", kw: "brackets arrows parentheses",
        items: [
        ["Left parenthesis", "open paren", "("], ["Right parenthesis", "close paren", ")"],
        ["Left square bracket", "open square", "["], ["Right square bracket", "close square", "]"],
        ["Less-than", "angle left", "<"], ["Greater-than", "angle right", ">"], ["Left guillemet", "quotes french", "«"],
        ["Right guillemet", "quotes french", "»"], ["Left lenticular bracket", "corner black", "【"],
        ["Right lenticular bracket", "corner black", "】"], ["Filled arrow right", "right pointer", "➡"],
        ["Filled arrow left", "left pointer", "⬅"], ["Filled arrow up", "up pointer", "⬆"],
        ["Filled arrow down", "down pointer", "⬇"], ["Arrow right with tail", "right", "↠"], ["Arrow left with tail", "left", "↞"],
        ["Filled up with base", "up", "⬆"], ["Filled down with base", "down", "⬇"], ["Hollow arrow up", "up", "↑"],
        ["Hollow arrow down", "down", "↓"], ["Hollow arrow right", "right", "→"], ["Hollow arrow left", "left", "←"],
        ["Arrow down-right", "diagonal", "↘"], ["Arrow down-left", "diagonal", "↙"], ["Arrow up-right", "diagonal", "↗"],
        ["Arrow up-left", "diagonal", "↖"], ["Arrow both ways horizontal", "left right", "↔"],
        ["Arrows opposite horizontal", "exchange", "⇄"], ["Arrow both ways vertical", "up down", "↕"],
        ["Crossed arrows", "shuffle random", "🔀"], ["Cycle arrows", "refresh reload", "🔄"], ["Section sign", "section legal", "§"]
        ],
      },
      { id: "mathematics", name: "Mathematics", group: "Basic", key: "a/b", kw: "math greek roman fractions",
        items: [
        ["Plus", "add", "+"], ["Minus", "subtract", "−"], ["Multiply", "times", "×"], ["Divide", "obelus", "÷"],
        ["Plus-minus", "plus minus", "±"], ["Equals", "equal", "="], ["Greater than or equal", "gte", "≥"],
        ["Less than or equal", "lte", "≤"], ["Not equal", "inequality", "≠"], ["Therefore", "so thus dots", "∴"],
        ["Alpha", "greek", "α"], ["Beta", "greek", "β"], ["Gamma", "greek", "γ"], ["Delta", "greek", "δ"],
        ["Mu", "micro greek", "μ"], ["Omega", "ohm greek", "Ω"], ["Phi", "greek", "φ"], ["Sigma", "sum greek", "Σ"],
        ["Feminine ordinal", "superscript a", "ª"], ["Masculine ordinal", "superscript o", "º"], ["Subscript 2", "sub two", "₂"],
        ["Subscript 3", "sub three", "₃"], ["Superscript 2", "squared", "²"], ["Superscript 3", "cubed", "³"],
        ["One quarter", "fraction 1/4", "¼"], ["One half", "fraction 1/2", "½"], ["Three quarters", "fraction 3/4", "¾"],
        ["Roman I", "one 1", "Ⅰ"], ["Roman II", "two 2", "Ⅱ"], ["Roman III", "three 3", "Ⅲ"], ["Roman IV", "four 4", "Ⅳ"],
        ["Roman V", "five 5", "Ⅴ"], ["Roman VI", "six 6", "Ⅵ"], ["Roman VII", "seven 7", "Ⅶ"], ["Roman VIII", "eight 8", "Ⅷ"],
        ["Roman IX", "nine 9", "Ⅸ"], ["Roman X", "ten 10", "Ⅹ"]
        ],
      },
      { id: "currencyunit", name: "CurrencyUnit", group: "Basic", key: "a/b", kw: "money currency units temperature",
        items: [
        ["Percent", "percentage", "%"], ["Dollar", "usd money", "$"], ["Cent", "money", "¢"], ["Euro", "money", "€"],
        ["Pound sterling", "gbp money", "£"], ["Yen / yuan", "jpy cny money", "¥"], ["Turkish lira", "try money", "₺"],
        ["Degree", "angle temperature", "°"], ["Feet", "ft foot length", "ft."], ["Inches", "in inch length", "in."],
        ["Square metre", "m2 area", "m²"], ["Cubic metre", "m3 volume", "m³"], ["cc", "cubic centimetre", "cc"],
        ["Litre", "liter l", "ℓ"], ["Ounce", "oz weight", "oz."], ["Pound weight", "lb weight", "lb."],
        ["Degree Fahrenheit", "temperature F", "°F"], ["Degree Celsius", "temperature C", "°C"]
        ],
      },
      { id: "circled-number", name: "(Number)", group: "Basic", key: "a/b", chars: "circled 1-99", kw: "circled numbers 1-99",
        charsNote: "Circled numbers 1 to 99. The sheet prints the range, not each glyph." },
      { id: "boxed-number", name: "[Number]", group: "Basic", key: "a/b", chars: "boxed 1-99", kw: "boxed squared numbers 1-99",
        charsNote: "Boxed numbers 1 to 99. The sheet prints the range, not each glyph." },
      { id: "sign", name: "Sign", group: "Pictograph", key: "a/b", kw: "safety warning restroom",
        items: [
        ["Prohibited (circle with slash)", "no forbidden banned", "🚫"], ["No entry", "do not enter stop bar", "⛔"],
        ["Flammable / fire", "flame hot burn", "🔥"], ["Warning (exclamation triangle)", "caution danger hazard", "⚠️"],
        ["Information", "info i", "ℹ️"], ["Fragile (glass)", "breakable shipping", "🍷"], ["This way up", "arrows up package", "⏫"],
        ["Handle with care (hands and box)", "careful shipping", "📦"], ["Recycle", "recycling eco", "♻️"],
        ["No parking", "parking prohibited", "🅿️"], ["Parking", "car park P", "🅿️"],
        ["Emergency exit", "exit escape running", "🚪"], ["Restroom (woman and man)", "toilet bathroom WC", "🚻"],
        ["Men", "male gents", "🚹"], ["Women", "female ladies", "🚺"], ["Use litter bin", "trash garbage", "🚮"],
        ["Wheelchair accessible", "disabled accessibility", "♿"], ["Elevator", "lift", "🛗"], ["Escalator", "moving stairs", "🚶"],
        ["Stairs", "steps", "🪜"], ["Restaurant (fork and knife)", "food dining", "🍴"],
        ["No mobile phones", "cell phone prohibited", "📵"], ["No smoking", "cigarette prohibited", "🚭"],
        ["No cameras", "photo prohibited", "📷"], ["No insects / moths", "pest prohibited", "🦋"],
        ["No stacking", "boxes prohibited", "📦"], ["No airplanes", "flight prohibited", "✈️"],
        ["No credit cards", "payment prohibited", "💳"], ["Hotel / lodging", "bed sleep", "🛏️"],
        ["Campfire allowed", "fire outdoor", "🔥"], ["Running / sport", "exercise", "🏃"], ["Male sign", "man gender mars", "♂"],
        ["Female sign", "woman gender venus", "♀"], ["Telephone", "phone call", "☎️"], ["Elevator (front)", "lift doors", "🛗"],
        ["Atom / radiation science", "nuclear", "⚛️"], ["Bomb", "explosive", "💣"], ["High voltage", "lightning electric", "⚡"],
        ["Skull", "poison danger", "💀"], ["Skull and crossbones", "poison toxic death", "☠️"]
        ],
      },
      { id: "electronics", name: "Electronics", group: "Pictograph", key: "a/b", kw: "devices gadgets tech",
        items: [
        ["Laptop", "computer notebook", "💻"], ["Desktop computer", "monitor tower PC", "🖥️"], ["Calculator", "math", "🧮"],
        ["Printer", "print", "🖨️"], ["Fax machine", "fax", "📠"], ["Desk telephone", "landline", "☎️"],
        ["Office phone", "handset keypad", "📞"], ["Mobile phone", "cell feature phone", "📱"], ["Smartphone", "touch phone", "📱"],
        ["Tablet with stylus", "drawing pad", "🖊️"], ["Compact camera", "photo", "📷"], ["Camera", "photo digital", "📷"],
        ["SLR camera", "photo dslr", "📷"], ["Camcorder", "video camera", "📹"], ["Movie camera", "film cinema", "🎥"],
        ["Music player", "ipod walkman", "🎧"], ["Stereo / boombox", "hi-fi audio", "📻"], ["Microphone", "mic recording", "🎤"],
        ["Game console", "gaming", "🎮"], ["Headphones", "audio music", "🎧"], ["Monitor / TV", "screen display", "🖥️"],
        ["Mouse", "computer pointer", "🖱️"], ["Keyboard", "typing", "⌨️"], ["Disc player", "DVD CD", "📀"],
        ["USB stick / dongle", "flash drive", "💾"], ["Tape / disc deck", "VCR player", "📼"], ["Disc (CD / DVD)", "CD DVD", "💿"],
        ["Antenna", "aerial", "📡"], ["Satellite dish", "satellite TV", "📡"], ["Speaker", "volume sound", "🔊"],
        ["Power plug", "mains cable", "🔌"], ["Battery", "power charge", "🔋"], ["Signal bars", "reception cellular", "📶"],
        ["Wi-Fi", "wireless internet", "📶"], ["RSS / feed", "broadcast", "📡"], ["Smartphone with arrow", "share send", "📱"],
        ["Incoming envelope", "mail download", "✉️"], ["Chat bubbles", "message SMS", "💬"], ["Projector", "beamer", "📽️"],
        ["Studio light", "spotlight", "💡"], ["Inbox / download tray", "receive", "📥"], ["Outbox / upload tray", "send", "📤"],
        ["Cloud download", "cloud receive", "☁️"], ["Cloud upload", "cloud send", "☁️"], ["Fast forward", "skip media", "⏩"],
        ["Skip to end", "next track", "⏭️"], ["Play", "start media", "▶️"], ["Reverse", "back media", "◀️"],
        ["Skip to start", "previous track", "⏮️"], ["Rewind", "back media", "⏪"]
        ],
      },
      { id: "business", name: "Business", group: "Pictograph", key: "a/b", kw: "office work finance",
        items: [
        ["Check mark", "tick done ok", "✔️"], ["Checked box", "checkbox ballot", "☑️"], ["Empty box", "checkbox empty", "☐"],
        ["Highlighter", "marker", "🖍️"], ["Pencil", "write", "✏️"], ["Scissors", "cut", "✂️"],
        ["Ruler and set square", "geometry measure", "📐"], ["Compass", "drawing geometry", "🧭"], ["Stapler", "office", "📎"],
        ["Utility knife", "cutter boxcutter", "🔪"], ["Document", "page paper", "📄"], ["Documents (stack)", "pages", "📑"],
        ["Folder with tab", "file", "📁"], ["Envelope", "mail letter", "✉️"], ["Folder", "directory", "📂"],
        ["Calendar", "date schedule", "📅"], ["Briefcase", "bag work", "💼"], ["Open book / notebook", "notes", "📓"],
        ["Alarm clock", "time wake", "⏰"], ["Globe", "world earth", "🌍"], ["Paperclips", "clip", "📎"],
        ["Push pins", "thumbtack", "📌"], ["Hourglass", "timer", "⏳"], ["Clock", "time", "🕒"], ["Open book", "read", "📖"],
        ["Key", "lock access", "🔑"], ["Padlock", "lock secure", "🔒"], ["Credit card", "payment", "💳"],
        ["Fire extinguisher", "safety fire", "🧯"], ["Faucet / tap", "water plumbing", "🚰"], ["Reception / counter", "desk", "🛎️"],
        ["Traffic cone", "caution", "🚧"], ["Delivery truck", "shipping", "🚚"], ["Fuel pump", "gas petrol", "⛽"],
        ["Security camera", "cctv", "📷"], ["House", "home", "🏠"], ["Office building (grid)", "company", "🏢"],
        ["Life vest", "safety jacket", "🦺"], ["Filing cabinet / server", "storage", "🗄️"], ["Handshake", "deal agree", "🤝"],
        ["Magnifying glass", "search", "🔍"], ["Presenter", "speaker talk", "🗣️"], ["Meeting (two at table)", "conference", "👥"],
        ["Two people", "team", "👥"], ["Group", "people", "👥"], ["Clipboard", "list notes", "📋"], ["Spiral notebook", "notes", "📓"],
        ["Clipboard with list", "tasks", "📋"], ["Wireless lock", "smart lock", "🔐"], ["Bell", "alert notification", "🔔"],
        ["Map pin", "location", "📍"], ["Price tag", "label", "🏷️"], ["Tag", "label", "🏷️"],
        ["School / institution", "building", "🏫"], ["Bank", "finance columns", "🏦"], ["Coins / stacks", "money", "🪙"],
        ["Unbalanced scale", "justice", "⚖️"], ["Scales of justice", "law", "⚖️"], ["Gavel", "judge court", "🔨"],
        ["Piggy bank", "savings", "🐷"], ["Banknotes", "cash money", "💵"], ["Contacts / people card", "address book", "📇"],
        ["Factory", "industry", "🏭"], ["Open 24 hours", "always", "🕒"], ["24-hour support headset", "helpdesk", "🎧"],
        ["Shopping cart", "buy", "🛒"], ["Phone with chat", "call message", "📞"], ["Play button", "media", "▶️"],
        ["Eye", "view visible", "👁️"], ["Chart trending up", "growth", "📈"], ["Bar chart", "statistics", "📊"],
        ["Pie chart", "statistics", "🥧"], ["Presenter at screen", "lecture", "👩‍🏫"], ["ID badge", "identity", "🪪"],
        ["Mobile device", "phone tablet", "📱"], ["Target with arrow", "goal aim", "🎯"], ["Flag", "pennant", "🚩"],
        ["Chess knight", "strategy", "♞"], ["Trophy", "award winner", "🏆"], ["Medal", "prize", "🏅"], ["Recycle", "eco", "♻️"],
        ["Factory workers", "team production", "🏭"], ["CO₂ cloud", "carbon emissions", "☁️"],
        ["Touch / tap", "finger screen", "👆"], ["Hands with gift", "give present", "🎁"], ["Two tags", "labels", "🏷️"],
        ["Stars in hand", "favorite rating", "⭐"], ["Download tag", "save label", "🏷️"], ["Parachute / air drop", "delivery", "🪂"],
        ["Registered mark", "trademark R", "®"], ["Copyright", "legal C", "©"], ["Trademark", "TM", "™"]
        ],
      },
      { id: "healthcare", name: "Healthcare", group: "Pictograph", key: "a/b", kw: "medical health",
        items: [
        ["First aid kit", "medical cross box", "🩹"], ["Medicine bottle", "pills pharmacy", "💊"],
        ["Bandage / plaster", "band-aid", "🩹"], ["Capsule", "pill", "💊"], ["Syringe", "injection vaccine", "💉"],
        ["Flask", "lab chemistry", "⚗️"], ["Two medicine bottles", "pharmacy", "💊"], ["Jar / ointment", "cream", "🧴"],
        ["Microscope", "lab science", "🔬"], ["Medical bag", "doctor kit", "🧳"], ["Spray bottle", "disinfectant", "🧴"],
        ["Germs / bacteria", "virus", "🦠"], ["Face mask", "ppe covid", "😷"], ["Virus", "covid germ", "🦠"],
        ["Thermometer", "fever temperature", "🌡️"], ["Sanitizer bottle", "soap", "🧴"], ["Sparkles (clean)", "sanitized", "✨"],
        ["Lungs / organ", "respiratory", "🫁"], ["Biohazard fan", "hazard", "☣️"], ["Heartbeat", "ecg pulse", "💓"],
        ["Ambulance", "emergency", "🚑"], ["Stethoscope", "doctor", "🩺"], ["Radiation", "radioactive", "☢️"],
        ["Blood drop with cross", "donate blood", "🩸"], ["Nurse cap", "nursing", "👩‍⚕️"], ["Bone", "fracture xray", "🦴"],
        ["Two bones", "skeleton", "🦴"], ["Medical folder", "records", "📁"], ["Caduceus", "medicine staff", "⚕️"],
        ["Hospital H", "clinic", "🏥"]
        ],
      },
      { id: "electrical", name: "Electrical", group: "Pictograph", key: "a/b", kw: "IEC power electric",
        items: [
        ["AC (sine)", "alternating current", "∿"], ["DC (double bar)", "direct current", "⎓"], ["Earth / ground", "GND", "⏚"],
        ["Chassis ground (rake)", "frame earth", "⏚"], ["Fuse", "protection", "⌸"],
        ["Double insulation (Class II)", "square in square", "回"], ["Lamp indicator (circled X)", "light", "⊗"],
        ["Standby / power", "power button", "⏻"], ["Off (circle)", "power off O", "⭘"], ["On (bar)", "power on I", "⏐"],
        ["Earth in circle", "ground", "⏚"], ["On (circled I)", "power on", "Ⓘ"], ["Circled triangle", "warning", "🔻"],
        ["Speaker", "audio output", "🔈"], ["Dangerous voltage (boxed lightning)", "high voltage shock", "⚡"],
        ["Electrical hazard (lightning triangle)", "high voltage warning", "⚠️"], ["Equipotential / earth bars", "ground", "⏚"]
        ],
      },
      { id: "tools", name: "Tools", group: "Pictograph", key: "a/b", kw: "workshop DIY",
        items: [
        ["Hammer and brush", "tools paint", "🔨"], ["Paint brush", "painting", "🖌️"], ["Paint can", "bucket", "🪣"],
        ["Paint roller", "wall paint", "🖌️"], ["Toolbox", "tools kit", "🧰"], ["Screw", "fastener", "🔩"],
        ["Nut / hex", "bolt hardware", "🔩"], ["Screwdriver", "tool", "🪛"], ["Wrench", "spanner", "🔧"],
        ["Hand saw", "carpentry", "🪚"], ["Axe", "hatchet", "🪓"], ["Mallet", "hammer", "🔨"], ["Power drill", "tool", "🪛"],
        ["Stepladder", "ladder", "🪜"], ["Palette", "art painting", "🎨"], ["Open manual / book", "instructions", "📖"],
        ["Hard hat", "safety helmet construction", "⛑️"]
        ],
      },
      { id: "garden", name: "Garden", group: "Pictograph", key: "a/b", kw: "plants flowers yard",
        items: [
        ["Watering can", "water plants", "🚿"], ["Watering can pouring", "water", "🚿"], ["Trowel / spade", "dig", "🪏"],
        ["Hand fork", "cultivator", "🍴"], ["Rake", "leaves lawn", "🧹"], ["Lawn mower", "grass", "🚜"],
        ["Gardening gloves", "hands", "🧤"], ["Boot", "wellington", "👢"], ["Wheelbarrow", "cart", "🛒"],
        ["Potted plant", "flower pot", "🪴"], ["Flower pot", "plant", "🪴"], ["Four-leaf clover", "luck", "🍀"],
        ["Leaf", "foliage", "🍃"], ["Tulip", "flower spring", "🌷"], ["Rose", "flower", "🌹"], ["Daisy", "flower", "🌼"],
        ["Hydrangea", "flower ball", "🌸"], ["Bouquet", "flowers", "💐"], ["Palm tree", "tropical", "🌴"],
        ["Branch / twig", "plant", "🌿"], ["Leafy sprig", "herb", "🌿"], ["Blossom cluster", "flowers", "🌸"],
        ["Star flower", "blossom", "🌼"], ["Clover blossom", "flower", "🍀"]
        ],
      },
      { id: "craftbaby", name: "Craft/Baby", group: "Pictograph", key: "a/b", kw: "sewing baby craft",
        items: [
        ["Button", "sew", "🔘"], ["Measuring tape", "sew tailor", "📏"], ["Spool of thread", "sew", "🧵"],
        ["Pin cushion", "pins sew", "📍"], ["Sewing machine", "sew craft", "🧵"], ["Yarn and needles", "knit", "🧶"],
        ["Safety pin", "nappy diaper", "🧷"], ["Baby stroller", "pram buggy", "🍼"], ["Pacifier", "dummy soother", "🍼"],
        ["ABC blocks", "toys alphabet", "🧸"]
        ],
      },
      { id: "music", name: "Music", group: "Pictograph", key: "a/b", kw: "instruments notes",
        items: [
        ["Eighth note", "quaver", "🎵"], ["Beamed notes", "music", "🎶"], ["Two beamed notes", "music", "🎶"],
        ["Treble clef", "music", "🎼"], ["Guitar", "instrument", "🎸"], ["Violin and bow", "strings", "🎻"],
        ["Saxophone", "jazz", "🎷"], ["Harp", "instrument", "🎼"], ["Microphone", "karaoke mic", "🎤"]
        ],
      },
      { id: "animal", name: "Animal", group: "Pictograph", key: "a/b", kw: "pets zoo",
        items: [
        ["Dog (side head)", "puppy pet", "🐶"], ["Cat face", "kitten pet", "🐱"], ["Rabbit face", "bunny", "🐰"],
        ["Monkey face", "ape", "🐵"], ["Elephant", "trunk", "🐘"], ["Lion", "mane", "🦁"], ["Tiger", "stripes", "🐯"],
        ["Gorilla", "ape", "🦍"], ["Pig", "hog", "🐷"], ["Raccoon / red panda", "face", "🦝"], ["Bear", "teddy", "🐻"],
        ["Panda", "bear", "🐼"], ["Hippo face", "hippopotamus", "🦛"], ["Mouse", "rat", "🐭"], ["Sheep", "lamb farm", "🐑"],
        ["Dog (standing)", "pet", "🐕"], ["Poodle", "dog", "🐩"], ["Cat sitting", "pet", "🐈"], ["Cat (side)", "pet", "🐈"],
        ["Squirrel", "rodent", "🐿️"], ["Sheep (side)", "farm", "🐑"], ["Horse", "pony", "🐴"], ["Deer", "stag", "🦌"],
        ["Panda sitting", "bear", "🐼"], ["Elephant (side)", "trunk", "🐘"], ["Rooster", "chicken farm", "🐓"],
        ["Chick", "bird baby", "🐤"], ["Bird in flight", "dove", "🕊️"], ["Swan", "bird", "🦢"], ["Penguin", "bird", "🐧"],
        ["Owl", "bird", "🦉"], ["Tropical fish", "aquarium", "🐠"], ["Crab", "shellfish", "🦀"], ["Seahorse", "ocean", "🐴"],
        ["Lobster", "seafood", "🦞"], ["Dolphin", "ocean", "🐬"], ["Whale", "ocean", "🐋"], ["Turtle", "tortoise", "🐢"],
        ["Butterfly", "insect", "🦋"], ["Ladybird", "ladybug insect", "🐞"]
        ],
      },
      { id: "foods", name: "Foods", group: "Pictograph", key: "a/b", kw: "eat drink kitchen",
        items: [
        ["Citrus slice", "orange lemon", "🍊"], ["Grapes", "fruit wine", "🍇"], ["Berries / raspberries", "fruit", "🫐"],
        ["Apple", "fruit", "🍎"], ["Apple (outline)", "fruit", "🍏"], ["Cherries", "fruit", "🍒"], ["Strawberry", "berry", "🍓"],
        ["Strawberry (alt)", "berry", "🍓"], ["Pineapple", "tropical", "🍍"], ["Peach / apricot", "fruit", "🍑"],
        ["Pear", "fruit", "🍐"], ["Banana", "fruit", "🍌"], ["Mushroom", "fungi", "🍄"], ["Hamburger", "burger", "🍔"],
        ["Hot dog", "sausage", "🌭"], ["Roast chicken", "poultry", "🍗"], ["Steak / fish fillet", "meat", "🥩"],
        ["Shellfish / scallop", "seafood", "🐚"], ["Fried egg", "breakfast", "🍳"], ["Noodles / pasta", "bowl", "🍜"],
        ["Bread loaf", "bakery", "🍞"], ["Takeaway cup", "coffee", "🥤"], ["Cake slice", "dessert", "🍰"], ["Cupcake", "muffin", "🧁"],
        ["Donut", "doughnut", "🍩"], ["Ice cream cone", "dessert", "🍦"], ["Coffee beans", "coffee", "🫘"], ["Mug", "cup", "☕"],
        ["Steaming cup", "tea coffee", "☕"], ["Takeaway drink", "soda", "🥤"], ["Bottle", "water milk", "🍼"],
        ["Tumbler", "cup", "🥛"], ["Beer mug", "pint", "🍺"], ["Beer with foam", "ale", "🍻"], ["Wine glass", "drink", "🍷"],
        ["Espresso machine", "coffee", "☕"], ["Toaster", "breakfast", "🍞"], ["Kettle", "boil", "🫖"], ["Teapot", "tea", "🫖"],
        ["Moka pot", "coffee", "☕"], ["Fork and spoon", "cutlery", "🍴"], ["Ladle", "soup", "🥄"], ["Frying pan", "skillet", "🍳"],
        ["Kitchen knife", "chef", "🔪"], ["Fish on a board", "prepare", "🐟"], ["Plates", "dishes", "🍽️"],
        ["Mixing bowl", "whisk baking", "🥣"], ["Bowl", "soup", "🍲"], ["Cooking pot (steaming)", "saucepan", "🍲"],
        ["Pot with lid", "cook", "🍲"], ["Salt shaker", "seasoning", "🧂"], ["Pepper mill", "spice", "🧂"],
        ["Spice shaker", "seasoning", "🧂"], ["Cutting board", "chop", "🔪"], ["Spoons", "utensils", "🥄"],
        ["Fork and knife (place setting)", "dining", "🍴"], ["Jar with spoon", "preserve", "🫙"],
        ["Chef hat and utensils", "cook", "👨‍🍳"], ["Chef", "cook", "👨‍🍳"]
        ],
      },
      { id: "nature", name: "Nature/Earth", group: "Pictograph", key: "a/b", kw: "weather space",
        items: [
        ["Rainbow", "weather", "🌈"], ["Snowman", "winter", "⛄"], ["Sun", "sunny", "☀️"], ["Umbrella", "rain", "☔"],
        ["Cloud", "cloudy", "☁️"], ["Rain cloud", "shower", "🌧️"], ["Storm cloud", "thunder lightning", "⛈️"],
        ["Snowflake", "snow cold", "❄️"], ["Shooting star", "comet wish", "🌠"], ["Saturn", "planet space", "🪐"],
        ["Earth", "globe world", "🌍"], ["Pine trees", "forest", "🌲"], ["Mountain", "peak", "⛰️"],
        ["Palm trees", "tropical beach", "🌴"], ["Moon and stars", "night", "🌙"]
        ],
      },
      { id: "event", name: "Event", group: "Pictograph", key: "a/b", kw: "holiday party christmas",
        items: [
        ["Party poppers", "confetti celebration", "🎉"], ["Balloons", "party", "🎈"], ["Party hat", "birthday", "🥳"],
        ["Birthday cake", "candles", "🎂"], ["Cake with candles", "birthday", "🎂"], ["Bell with ribbon", "wedding christmas", "🔔"],
        ["Gift", "present", "🎁"], ["Gift with bow", "present wrapped", "🎁"], ["Heart with arrow", "valentine", "💘"],
        ["Clapperboard", "movie film", "🎬"], ["Fireworks", "new year", "🎆"], ["Champagne toast", "cheers", "🥂"],
        ["Cross", "church religion", "✝️"], ["Jack-o-lantern", "halloween pumpkin", "🎃"], ["Witch", "halloween broom", "🧙"],
        ["Heart with ribbon", "valentine gift", "💝"], ["Snowman with hat", "winter christmas", "⛄"],
        ["Graduation cap", "diploma", "🎓"], ["Ring", "wedding marriage", "💍"], ["Gingerbread", "christmas cookie", "🍪"],
        ["Santa Claus", "christmas", "🎅"], ["Angel", "christmas", "👼"], ["Sleigh", "christmas santa", "🛷"],
        ["Christmas bells", "jingle", "🔔"], ["Christmas tree", "xmas", "🎄"], ["Wreath", "christmas door", "🎄"],
        ["Holly", "christmas", "🎄"], ["Candy cane", "christmas sweets", "🍬"], ["Bauble", "christmas ornament", "🔮"],
        ["Dreidel", "hanukkah", "✡️"], ["Star of David", "hanukkah jewish", "✡️"], ["Menorah", "hanukkah", "🕎"]
        ],
      },
      { id: "vehicle", name: "Vehicle", group: "Pictograph", key: "a/b", kw: "transport travel",
        items: [
        ["Car (side)", "automobile", "🚗"], ["Car (compact)", "automobile", "🚘"], ["SUV / 4x4", "car", "🚙"],
        ["Car (front)", "automobile", "🚘"], ["Taxi / car with sign", "cab", "🚕"], ["Bicycle", "bike", "🚲"],
        ["Bicycle (diamond frame)", "bike", "🚲"], ["Motorcycle", "motorbike", "🏍️"], ["Scooter", "moped", "🛵"],
        ["Truck", "lorry", "🚚"], ["Box truck", "delivery", "🚛"], ["Forklift", "warehouse", "🏗️"], ["Bus (side)", "coach", "🚌"],
        ["Bus (front)", "transit", "🚌"], ["Tram / train front", "metro", "🚇"], ["Train (front)", "rail", "🚆"],
        ["High-speed train", "shinkansen", "🚄"], ["Airplane", "flight", "✈️"], ["Airplane taking off", "jet", "🛫"],
        ["Helicopter", "chopper", "🚁"], ["Helicopter (side)", "chopper", "🚁"], ["Ship", "cruise ferry", "🚢"],
        ["Boat with funnel", "steamship", "🛳️"], ["Cargo ship", "container", "⛴️"], ["Sailboat", "yacht", "⛵"],
        ["Sailboat with birds", "sailing", "⛵"], ["Hot air balloon", "balloon", "🎈"], ["Rocket", "space launch", "🚀"],
        ["UFO / flying saucer", "alien", "🛸"]
        ],
      },
      { id: "wardrobe", name: "Wardrobe", group: "Pictograph", key: "a/b", kw: "clothes fashion laundry wardobe",
        items: [
        ["T-shirt", "top", "👕"], ["Sweater", "jumper", "👚"], ["Coat / cardigan", "jacket", "🧥"],
        ["Shorts / trousers", "pants", "👖"], ["Skirt", "clothes", "👗"], ["Camisole / tank", "top", "👚"],
        ["Tee (plain)", "shirt", "👕"], ["Polka-dot top", "shirt", "👚"], ["Shirt", "button", "👔"], ["Jacket", "blazer", "🧥"],
        ["Sun hat", "ladies hat", "👒"], ["Bowler / fedora", "hat", "🎩"], ["Handbag", "purse", "👜"], ["Backpack", "bag", "🎒"],
        ["Sock", "socks", "🧦"], ["Sneaker", "shoe", "👟"], ["High heel", "shoe", "👠"], ["Flats / pumps", "shoes", "👞"],
        ["Scarf", "winter", "🧣"], ["Gloves", "winter hands", "🧤"], ["Glasses", "spectacles", "👓"], ["Sunglasses", "shades", "🕶️"],
        ["Bow tie", "formal", "🎀"], ["Tuxedo / suit", "formal", "🤵"], ["Dress", "gown", "👗"]
        ],
      },
      { id: "sports", name: "Sports", group: "Pictograph", key: "a/b", kw: "fitness games",
        items: [
        ["American football", "rugby ball", "🏈"], ["Volleyball", "ball", "🏐"], ["Baseball", "ball", "⚾"],
        ["Basketball", "ball", "🏀"], ["Soccer ball", "football", "⚽"], ["Hockey stick and puck", "ice hockey", "🏒"],
        ["Stadium", "arena", "🏟️"], ["Soccer goal", "net", "🥅"], ["Volleyball net", "net", "🏐"],
        ["Basketball hoop", "basket", "🏀"], ["Football goal posts", "field goal", "🏈"], ["Tennis racket and ball", "tennis", "🎾"],
        ["Crossed hockey sticks", "hockey", "🏒"], ["Table tennis", "ping pong", "🏓"], ["Golf", "flag club hole", "⛳"],
        ["Trophy", "cup winner", "🏆"], ["Running shoe", "sneaker", "👟"], ["Exercise bike", "gym", "🚴"],
        ["Dumbbell", "weights gym", "🏋️"], ["Swimmer", "pool", "🏊"], ["Snowboarder", "snow", "🏂"], ["Skier", "skiing", "⛷️"],
        ["Ice hockey player", "hockey", "🏒"], ["Golfer", "golf swing", "🏌️"], ["Billiard balls", "pool 8-ball", "🎱"],
        ["Bowling", "ball pin", "🎳"], ["Fishing", "rod hook", "🎣"], ["Mountain / climbing", "peak", "⛰️"]
        ],
      },
      { id: "family", name: "Family", group: "Pictograph", key: "a/b", kw: "people faces",
        items: [
        ["Man", "father dad face", "👨"], ["Woman", "mother mom face", "👩"], ["Grandfather", "old man grandpa", "👴"],
        ["Grandmother", "old woman grandma", "👵"], ["Girl", "daughter", "👧"], ["Boy", "son", "👦"], ["Baby", "infant", "👶"]
        ],
      },
      { id: "emoji", name: "Emoji", group: "Pictograph", key: "a/b", kw: "smiley faces hands",
        items: [
        ["Laughing face", "grin happy lol", "😆"], ["Smiling face", "smile happy", "🙂"], ["Big grin", "open mouth happy", "😃"],
        ["Neutral face", "meh", "😐"], ["Unamused face", "meh", "😒"], ["Angry face", "mad", "😠"],
        ["Straight mouth", "serious", "😑"], ["Wry smile", "smirk", "😏"], ["Speechless face", "dots", "😶"],
        ["Surprised face", "oh", "😮"], ["Heart eyes", "in love", "😍"], ["Sleeping / zzz face", "tired", "😴"],
        ["Open-mouth face", "wow", "😲"], ["Furious face", "rage", "😡"], ["Confounded face", "upset", "😖"],
        ["Weary face", "tired sad", "😩"], ["Pensive face", "sad", "😔"], ["Awkward smile", "nervous", "😅"],
        ["Cool face (sunglasses)", "sunglasses cool", "😎"], ["Thumbs up", "like ok", "👍"], ["Handshake", "deal agree", "🤝"],
        ["Fist bump left", "punch", "🤛"], ["Pointing right", "finger", "👉"], ["Pointing up", "finger", "☝️"],
        ["Pointing down", "finger", "👇"]
        ],
      },
      { id: "pictograph", name: "Pictograph", group: "Pictograph", key: "a/b", kw: "shapes cards ornaments",
        items: [
        ["Filled circle", "bullet disc", "●"], ["Hollow circle", "ring", "○"], ["Filled square", "box", "■"],
        ["Hollow square", "box", "□"], ["Filled triangle up", "delta", "▲"], ["Hollow triangle up", "delta", "△"],
        ["Filled triangle down", "nabla", "▼"], ["Hollow triangle down", "nabla", "▽"], ["Filled star", "favorite", "★"],
        ["Hollow star", "favorite", "☆"], ["Filled spade", "cards", "♠"], ["Hollow spade", "cards", "♤"],
        ["Filled heart", "love", "♥"], ["Hollow heart", "love", "♡"], ["Filled diamond", "cards", "◆"],
        ["Hollow diamond", "cards", "◇"], ["Filled club", "cards", "♣"], ["Hollow club", "cards", "♧"],
        ["Two dots / colon mark", "dots", "⁚"], ["Question burst", "help", "❓"], ["Plus / cross", "add", "➕"],
        ["Flower plus", "sparkle", "✳️"], ["Ribbon swirl", "flourish", "〰️"], ["Sleeping zzz", "sleep tired", "💤"],
        ["Footprints", "feet steps", "👣"], ["Paw print", "pet", "🐾"], ["Two hearts", "love", "💕"], ["Light bulb", "idea", "💡"],
        ["Crown", "royal", "👑"], ["Anchor", "nautical", "⚓"], ["Ship wheel", "helm nautical", "☸️"], ["Life ring", "rescue", "🛟"],
        ["Tower / pagoda", "building", "🗼"], ["Ferris wheel", "fair carnival", "🎡"]
        ],
      },
      { id: "astrology", name: "Astrology", group: "Pictograph", key: "a/b", kw: "zodiac horoscope",
        items: [
        ["Aries", "ram zodiac", "♈"], ["Taurus", "bull zodiac", "♉"], ["Gemini", "twins zodiac", "♊"],
        ["Cancer", "crab zodiac", "♋"], ["Leo", "lion zodiac", "♌"], ["Virgo", "maiden zodiac", "♍"],
        ["Libra", "scales zodiac", "♎"], ["Scorpio", "scorpion zodiac", "♏"], ["Sagittarius", "archer zodiac", "♐"],
        ["Capricorn", "goat zodiac", "♑"], ["Aquarius", "water zodiac", "♒"], ["Pisces", "fish zodiac", "♓"]
        ],
      }
    ],
    accented: {
      image: 'img/symbols/accented.png',
      howto: ['Type the base letter (upper or lower case).', 'Press [Accent]. Press [Accent] again or use [▲] / [▼] to cycle the variants.', 'Press [OK] to insert. The variants depend on the LCD language.'],
      table: { A: 'Á À Â Ä Æ Ã Å Ā Ă', a: 'á à â ä æ ã å ā ă', C: 'Ç Č Ć', c: 'ç č ć', D: 'Ď Đ', d: 'ď ð đ', E: 'É È Ê Ë Ę Ě Ē', e: 'é è ê ë ę ě ē', G: 'Ģ Ğ', g: 'ģ ğ', I: 'Í Ì Î Ï Ī İ', i: 'í ì î ï ī ı', K: 'Ķ', k: 'ķ', L: 'Ł Ĺ Ļ Ľ', l: 'ł ĺ ļ ľ', N: 'Ñ Ň Ń Ņ', n: 'ñ ň ń ņ', O: 'Ó Ò Ô Ø Ö Õ Œ Ő', o: 'ó ò ô ø ö õ œ ő', R: 'Ř Ŕ Ŗ', r: 'ř ŕ ŗ', S: 'Š Ś Ş Ș ß', s: 'š ś ş ș ß', T: 'Ť Ţ Þ', t: 'ť ţ þ', U: 'Ú Ù Û Ü Ů Ū Ű', u: 'ú ù û ü ů ū ű', Y: 'Ý Ÿ', y: 'ý ÿ', Z: 'Ž Ź Ż', z: 'ž ź ż' },
    },
  },

  frames: {
    howto: [
      'Press [Fn].',
      'Use [▲] / [▼] to display {Frame}, then [OK].',
      'Choose a category, then a frame with the cursor keys, or type the frame number.',
      'Press [OK].',
    ],
    notes: [
      'Frames are grouped as Simple 1, Simple 2, Decorative, Business 1 and Business 2 (167 designs on this guide\'s sheet; Brother lists 160).',
      'A template that needs a different tape width shows an error. Install the matching cassette or pick another design.',
    ],
    items: [
      ['off', 'No frame', 'none off plain remove'],
      [1, "Thin rectangle", "border thin rectangle"],
      [2, "Thick rectangle", "border thick rectangle"],
      [3, "Extra-thick rectangle", "border extra-thick rectangle"],
      [4, "Rounded rectangle", "border rounded rectangle"],
      [5, "Thick rounded rectangle", "border thick rounded rectangle"],
      [6, "Pill / capsule", "pill / capsule"],
      [7, "Double horizontal rules", "double horizontal rules"],
      [8, "Thick double rules", "thick double rules"],
      [9, "Notched left end", "notched left end"],
      [10, "Photo corners", "photo corners"],
      [11, "Pointed banner", "pointed banner"],
      [12, "Striped chevron banner", "striped chevron banner"],
      [13, "Corner L-brackets", "corner l-brackets"],
      [14, "Zigzag ends", "zigzag ends"],
      [15, "Speech bubble", "speech bubble"],
      [16, "Floral corner", "floral corner"],
      [17, "Flower corner box", "border flower corner box"],
      [18, "Wave / scroll end", "wave / scroll end"],
      [19, "Binder-clip end", "binder-clip end"],
      [20, "Stepped ends", "stepped ends"],
      [21, "Ticket notches", "ticket notches"],
      [22, "Block corners", "block corners"],
      [23, "Striped ends", "striped ends"],
      [24, "Dotted corners", "dotted corners"],
      [25, "Square corners", "square corners"],
      [26, "Scalloped ends", "scalloped ends"],
      [27, "Pixel diamond corners", "pixel diamond corners"],
      [28, "Circle ends", "circle ends"],
      [29, "Pixel stamp", "pixel stamp"],
      [30, "Swirl ends", "swirl ends"],
      [31, "Double-line box", "border double-line box"],
      [32, "Thick double-line box", "border thick double-line box"],
      [33, "Rounded double-line box", "border rounded double-line box"],
      [34, "Box with corner ticks", "border box with corner ticks"],
      [35, "Embossed box", "border embossed box"],
      [36, "Double-outline box", "border double-outline box"],
      [37, "Double rules", "double rules"],
      [38, "Stamp box", "border stamp box"],
      [39, "Notched box", "border notched box"],
      [40, "Ruler-edge box", "border ruler-edge box"],
      [41, "Notched thick box", "border notched thick box"],
      [42, "Perforated box", "border perforated box"],
      [43, "Dotted box", "border dotted box"],
      [44, "Zigzag box", "border zigzag box"],
      [45, "Wavy dotted box", "border wavy dotted box"],
      [46, "Jagged box", "border jagged box"],
      [47, "Diamond-edge box", "border diamond-edge box"],
      [48, "Dash-edge box", "border dash-edge box"],
      [49, "Scallop-edge box", "border scallop-edge box"],
      [50, "Star-edge box", "border star-edge box"],
      [51, "Check-edge box", "border check-edge box"],
      [52, "Wavy-edge box", "border wavy-edge box"],
      [53, "Checker-edge box", "border checker-edge box"],
      [54, "Zigzag thick box", "border zigzag thick box"],
      [55, "Dashed rules", "dashed rules"],
      [56, "Scalloped rules", "scalloped rules"],
      [57, "Double dashed rules", "double dashed rules"],
      [58, "Diamond rules", "diamond rules"],
      [59, "Dotted rules", "dotted rules"],
      [60, "Wavy rules", "wavy rules"],
      [61, "Candy / cracker ends", "candy / cracker ends"],
      [62, "Butterfly ends", "butterfly ends"],
      [63, "Sparkle dotted line", "sparkle dotted line"],
      [64, "Snowflake line", "snowflake line"],
      [65, "Flower line", "flower line"],
      [66, "Clover corners", "clover corners"],
      [67, "Vine corners", "vine corners"],
      [68, "Floral rounded box", "border floral rounded box"],
      [69, "Postage stamp", "postage stamp"],
      [70, "Stars", "stars"],
      [71, "Hearts", "hearts"],
      [72, "Party poppers", "party poppers"],
      [73, "Bouquet", "bouquet"],
      [74, "Pencil", "pencil"],
      [75, "Gift box", "border gift box"],
      [76, "Bell and gift", "bell and gift"],
      [77, "Music band", "music band"],
      [78, "Toy box", "border toy box"],
      [79, "Notes", "notes"],
      [80, "Dog", "dog"],
      [81, "Cat", "cat"],
      [82, "Comb and scissors", "comb and scissors"],
      [83, "Camera and palm", "camera and palm"],
      [84, "Clapper and camera", "clapper and camera"],
      [85, "Garden and watering can", "garden and watering can"],
      [86, "Flowers on a vine", "flowers on a vine"],
      [87, "Leafy vine box", "border leafy vine box"],
      [88, "Birds", "birds"],
      [89, "Sun face", "sun face"],
      [90, "Rain boots and umbrella", "rain boots and umbrella"],
      [91, "Sun and boat", "sun and boat"],
      [92, "Leaf and tree", "leaf and tree"],
      [93, "Cabin and snowman", "cabin and snowman"],
      [94, "Fir trees", "fir trees"],
      [95, "Winter trees", "winter trees"],
      [96, "Sun and tulip", "sun and tulip"],
      [97, "Playground", "playground"],
      [98, "Books and hook", "books and hook"],
      [99, "Golfer", "golfer"],
      [100, "Golf hole", "golf hole"],
      [101, "Battery / barrel", "battery / barrel"],
      [102, "Torn note", "torn note"],
      [103, "Note with pencil", "note with pencil"],
      [104, "Tag", "tag"],
      [105, "Dog-eared page", "dog-eared page"],
      [106, "Notepad", "notepad"],
      [107, "Paint roller banner", "paint roller banner"],
      [108, "Megaphone banner", "megaphone banner"],
      [109, "Burst banner", "burst banner"],
      [110, "Phone and keypad", "phone and keypad"],
      [111, "Paper plane", "paper plane"],
      [112, "Laptop and mouse", "laptop and mouse"],
      [113, "Boxing gloves", "border boxing gloves"],
      [114, "Pencil and eraser", "pencil and eraser"],
      [115, "Chart with figure", "chart with figure"],
      [116, "Books", "books"],
      [117, "Power cord", "power cord"],
      [118, "Key and lock", "key and lock"],
      [119, "Pin and checkbox", "border pin and checkbox"],
      [120, "Sunrise and walker", "sunrise and walker"],
      [121, "Night and day panels", "night and day panels"],
      [122, "Walker and airplane", "walker and airplane"],
      [123, "Wrench and gears", "wrench and gears"],
      [124, "Pump and car", "pump and car"],
      [125, "Warning triangles", "warning triangles"],
      [126, "Mug and kettle", "mug and kettle"],
      [127, "Gauge", "gauge"],
      [128, "Bottle and glasses", "bottle and glasses"],
      [129, "Chess", "chess"],
      [130, "Target and flag", "target and flag"],
      [131, "Money and phone", "money and phone"],
      [132, "Speech bubbles", "speech bubbles"],
      [133, "Flag on a hill", "flag on a hill"],
      [134, "Cursors", "cursors"],
      [135, "Check and timer", "check and timer"],
      [136, "Music and phone", "music and phone"],
      [137, "Envelope and tag", "envelope and tag"],
      [138, "Wi-Fi", "wi-fi"],
      [139, "Smartphone", "smartphone"],
      [140, "ID and bubble", "id and bubble"],
      [141, "Clipboard and hand", "clipboard and hand"],
      [142, "Phone and tap", "phone and tap"],
      [143, "Chart and pie", "chart and pie"],
      [144, "Phone vibrate", "phone vibrate"],
      [145, "Pointing hand", "pointing hand"],
      [146, "Paper plane", "paper plane"],
      [147, "City and speaker", "city and speaker"],
      [148, "Building and house", "building and house"],
      [149, "Celebration and coffee", "celebration and coffee"],
      [150, "Office chair", "office chair"],
      [151, "Plant", "plant"],
      [152, "Teacher at board", "teacher at board"],
      [153, "Team in a bubble", "team in a bubble"],
      [154, "Crowd in a bubble", "crowd in a bubble"],
      [155, "Info and airplane", "info and airplane"],
      [156, "No and car", "no and car"],
      [157, "Search box", "border search box"],
      [158, "Wi-Fi download box", "border wi-fi download box"],
      [159, "Lock box", "border lock box"],
      [160, "Medical box", "border medical box"],
      [161, "Handshake box", "border handshake box"],
      [162, "Caduceus box", "border caduceus box"],
      [163, "Gavel box", "border gavel box"],
      [164, "Camera box", "border camera box"],
      [165, "Card box", "border card box"],
      [166, "Recycle box", "border recycle box"],
      [167, "Touch screen box", "border touch screen box"]
    ],
  },

  templates: {
    notes: [
      'Auto Format → Templates. Each design needs the tape width printed under it. A mismatch shows an error.',
      'You can save a filled-in template to File memory. Preview and Print Options are on the print menu.',
      'Block Layouts (listed as Pattern below) arrange lines for a chosen tape width; Table Format builds a grid.',
    ],
    textHowto: [
      'Press [Home] → {Auto Format} → [OK] → {Templates} → [OK].',
      'Pick a category (Asset Management, Cabinet, File, Address/ID, Media, Cable Labeling, Signage), then [OK].',
      'Pick a design, then [OK]. Type each field and press [OK] (barcode fields use the barcode editor).',
      '{Print} → [OK], or choose Edit / Save / Menu / Preview / Print Options first.',
    ],
    patternHowto: [
      'Press [Home] → {Auto Format} → [OK] → {Block Layouts} → [OK].',
      'Pick the tape width, then a layout, then [OK].',
      'Type each field and press [OK]. The print menu offers Edit / Save / Menu / Preview / Print Options.',
    ],
    text: [
      [1, "Asset Tag 1", "asset barcode property", "Property-of bar with barcode (24 mm x 70 mm)."],
      [2, "Asset Tag 2", "asset barcode property", "Property-of bar with barcode (18 mm x 70 mm)."],
      [3, "Asset Tag 3", "asset company barcode", "Company bar over barcode (24 mm x 70 mm)."],
      [4, "Asset Tag 4", "asset company barcode", "Company bar over barcode (18 mm x 70 mm)."],
      [5, "Asset Tag 5", "asset property serial", "Property of / company / serial (24 mm x 70 mm)."],
      [6, "Asset Tag 6", "asset property serial", "Property of / company / serial (18 mm x 70 mm)."],
      [7, "Asset Tag 7", "asset barcode", "Company name over barcode (12 mm x 70 mm)."],
      [8, "Bin Box", "warehouse bin inventory", "Arrow, description and barcode (24 mm x 76 mm)."],
      [9, "Equipment Label", "asset table serial", "Company / control / sales / equipment no. (24 mm x 58 mm)."],
      [10, "Cabinet Label 1", "cabinet shelf office", "Pencil icon and department (24 mm x 126 mm)."],
      [11, "Cabinet Label 2", "cabinet shelf office", "Pencil icon and department (18 mm x 111 mm)."],
      [12, "Cabinet Label 3", "cabinet shelf office", "Pencil icon and department (24 mm x 126 mm)."],
      [13, "Cabinet Label 4", "cabinet shelf office", "Pencil icons either side (24 mm x 160 mm)."],
      [14, "Binder Spine 1", "file binder spine", "Vertical spine (24 mm x 219 mm)."],
      [15, "Binder Spine 2", "file binder spine", "Vertical spine (18 mm x 219 mm)."],
      [16, "Binder Spine 3", "file binder spine date", "Logo, title and date (24 mm x 219 mm)."],
      [17, "Binder Spine 4", "file binder spine date", "Logo, title and date (12 mm x 219 mm)."],
      [18, "File Folder Tab", "file tab folder", "Folder tab (12 mm x 82 mm)."],
      [19, "Divider Tab", "divider tab month", "Small divider tab (12 mm x 42 mm)."],
      [20, "Document index", "index spine year", "Vertical year index (24 mm x 36 mm)."],
      [21, "Address Label 1", "address mail", "Return-address block (24 mm x 72 mm)."],
      [22, "Address Label 2", "address mail name", "Name and address (24 mm x 72 mm)."],
      [23, "Name Badge 1", "badge name title", "Name and title (24 mm x 72 mm)."],
      [24, "Name Badge 2", "badge name title logo", "Logo, name and title (24 mm x 72 mm)."],
      [25, "Name Badge 3", "badge name company", "Name and company (18 mm x 72 mm)."],
      [26, "Name Badge 4", "badge name company", "Large name and company (24 mm x 72 mm)."],
      [27, "SD Card Label", "sd card media", "Tiny media label (12 mm x 25 mm)."],
      [28, "USB Flash Memory", "usb stick media", "Tiny media label (9 mm x 25 mm)."],
      [29, "DVD Case Spine", "dvd spine media", "Long spine (9 mm x 178 mm)."],
      [30, "CD Case Spine", "cd spine media", "Long spine (6 mm x 113 mm)."],
      [31, "Flag 1", "cable flag wrap", "Two-sided cable flag (12 mm x 90 mm)."],
      [32, "Flag 2", "cable flag wrap", "Two-sided cable flag with IDs (12 mm x 90 mm)."],
      [33, "Cable Wrap 1", "cable wrap wrap-around", "Wrap-around cable (24 mm x 39 mm)."],
      [34, "Cable Wrap 2", "cable wrap wrap-around", "Wrap-around cable (18 mm x 39 mm)."],
      [35, "Faceplate (VRT)", "faceplate port vertical", "Vertical faceplate (12 mm x 70 mm)."],
      [36, "Signage 1", "warning hot caution", "HOT! / Don't Touch (24 mm x 66 mm)."],
      [37, "Signage 2", "caution this side up", "THIS SIDE UP arrows (24 mm x 50 mm)."]
    ],
    pattern: [
      [1, "24 mm 1Line(Inversion)", "block layout 24 mm 1line(inversion)", "Block layout 1Line(Inversion) for 24 mm tape."],
      [2, "24 mm 2LineA", "block layout 24 mm 2linea", "Block layout 2LineA for 24 mm tape."],
      [3, "24 mm 2LineB", "block layout 24 mm 2lineb", "Block layout 2LineB for 24 mm tape."],
      [4, "24 mm 3LineA", "block layout 24 mm 3linea", "Block layout 3LineA for 24 mm tape."],
      [5, "24 mm 3LineB", "block layout 24 mm 3lineb", "Block layout 3LineB for 24 mm tape."],
      [6, "24 mm 3LineC", "block layout 24 mm 3linec", "Block layout 3LineC for 24 mm tape."],
      [7, "24 mm 1+1LineA", "block layout 24 mm 1+1linea", "Block layout 1+1LineA for 24 mm tape."],
      [8, "24 mm 1+1LineB", "block layout 24 mm 1+1lineb", "Block layout 1+1LineB for 24 mm tape."],
      [9, "24 mm 1+1LineC", "block layout 24 mm 1+1linec", "Block layout 1+1LineC for 24 mm tape."],
      [10, "24 mm 1+2LineA", "block layout 24 mm 1+2linea", "Block layout 1+2LineA for 24 mm tape."],
      [11, "24 mm 1+2LineB", "block layout 24 mm 1+2lineb", "Block layout 1+2LineB for 24 mm tape."],
      [12, "24 mm 1+2LineC", "block layout 24 mm 1+2linec", "Block layout 1+2LineC for 24 mm tape."],
      [13, "24 mm 1+3LineA", "block layout 24 mm 1+3linea", "Block layout 1+3LineA for 24 mm tape."],
      [14, "24 mm 1+3LineB", "block layout 24 mm 1+3lineb", "Block layout 1+3LineB for 24 mm tape."],
      [15, "24 mm 1+3LineC", "block layout 24 mm 1+3linec", "Block layout 1+3LineC for 24 mm tape."],
      [16, "24 mm 1+4LineA", "block layout 24 mm 1+4linea", "Block layout 1+4LineA for 24 mm tape."],
      [17, "24 mm 1+4LineB", "block layout 24 mm 1+4lineb", "Block layout 1+4LineB for 24 mm tape."],
      [18, "24 mm 1+5Line", "block layout 24 mm 1+5line", "Block layout 1+5Line for 24 mm tape."],
      [19, "18 mm 2LineA", "block layout 18 mm 2linea", "Block layout 2LineA for 18 mm tape."],
      [20, "18 mm 2LineB", "block layout 18 mm 2lineb", "Block layout 2LineB for 18 mm tape."],
      [21, "18 mm 3LineA", "block layout 18 mm 3linea", "Block layout 3LineA for 18 mm tape."],
      [22, "18 mm 3LineB", "block layout 18 mm 3lineb", "Block layout 3LineB for 18 mm tape."],
      [23, "18 mm 1+1LineB", "block layout 18 mm 1+1lineb", "Block layout 1+1LineB for 18 mm tape."],
      [24, "18 mm 1+1LineC", "block layout 18 mm 1+1linec", "Block layout 1+1LineC for 18 mm tape."],
      [25, "18 mm 1+2LineA", "block layout 18 mm 1+2linea", "Block layout 1+2LineA for 18 mm tape."],
      [26, "18 mm 1+2LineB", "block layout 18 mm 1+2lineb", "Block layout 1+2LineB for 18 mm tape."],
      [27, "18 mm 1+2LineC", "block layout 18 mm 1+2linec", "Block layout 1+2LineC for 18 mm tape."],
      [28, "18 mm 1+2LineD", "block layout 18 mm 1+2lined", "Block layout 1+2LineD for 18 mm tape."],
      [29, "18 mm 1+3Line", "block layout 18 mm 1+3line", "Block layout 1+3Line for 18 mm tape."],
      [30, "18 mm 1+4Line", "block layout 18 mm 1+4line", "Block layout 1+4Line for 18 mm tape."],
      [31, "18 mm 1+5Line", "block layout 18 mm 1+5line", "Block layout 1+5Line for 18 mm tape."],
      [32, "12 mm 2LineA", "block layout 12 mm 2linea", "Block layout 2LineA for 12 mm tape."],
      [33, "12 mm 2LineB", "block layout 12 mm 2lineb", "Block layout 2LineB for 12 mm tape."],
      [34, "12 mm 3LineA", "block layout 12 mm 3linea", "Block layout 3LineA for 12 mm tape."],
      [35, "12 mm 3LineB", "block layout 12 mm 3lineb", "Block layout 3LineB for 12 mm tape."],
      [36, "12 mm 1+1LineA", "block layout 12 mm 1+1linea", "Block layout 1+1LineA for 12 mm tape."],
      [37, "12 mm 1+1LineB", "block layout 12 mm 1+1lineb", "Block layout 1+1LineB for 12 mm tape."],
      [38, "12 mm 1+1LineC", "block layout 12 mm 1+1linec", "Block layout 1+1LineC for 12 mm tape."],
      [39, "12 mm 1+2Line", "block layout 12 mm 1+2line", "Block layout 1+2Line for 12 mm tape."],
      [40, "9 mm 2LineA", "block layout 9 mm 2linea", "Block layout 2LineA for 9 mm tape."],
      [41, "9 mm 2LineB", "block layout 9 mm 2lineb", "Block layout 2LineB for 9 mm tape."],
      [42, "9 mm 1+2Line", "block layout 9 mm 1+2line", "Block layout 1+2Line for 9 mm tape."],
      [43, "6 mm 1+2Line", "block layout 6 mm 1+2line", "Block layout 1+2Line for 6 mm tape."]
    ],
  },

  howto: [
    { id: 'home', title: 'Home Screen: Create Label, Auto Format, File, Settings', kw: 'home menu create auto format file settings',
      steps: ['Press [Home] (house / Bluetooth key).', 'Use [◀] / [▶] to pick {Create Label}, {Auto Format}, {File} or {Settings}, then [OK].'],
      notes: ['Create Label starts a 280-character label. Auto Format holds Templates, Block Layouts and Table Format.'] },
    { id: 'attributes', title: 'Font, size, width, style and alignment', kw: 'font size width style alignment bold italic vertical',
      steps: ['For one character: [Shift] + [Fn], pick the attribute, pick the value, [OK].', 'For a whole line: put the cursor on that line, then [Shift] + [Fn]. Three bars on the left mean the change applies to that line only.', 'Press [Esc] to return to the text.'],
      notes: ['17 fonts, 9 sizes (Auto + 6–48 pt), 5 widths, 17 styles including Vertical / Vertical Bold, 4 alignments. Some fonts are region-locked.'] },
    { id: 'two-lines', title: 'Multiple lines (up to 7)', kw: 'lines enter return 2 3 5 7 line limit',
      steps: ['Type line 1.', 'Press [Enter] at the end of the line (a return mark appears).', 'Type the next line. Repeat up to the tape width limit.'],
      notes: ['24 mm: 7 lines. 18 mm: 5. 12 mm: 3. 9 mm and 6 mm: 2. 3.5 mm: 1.'] },
    { id: 'blocks', title: 'Text blocks (up to 5)', kw: 'block section shift enter',
      steps: ['Hold [Shift] and press [Enter] to start a new block to the right of the cursor.', 'Format a block the same way as a line (cursor in the block, then Shift + Fn).'],
      notes: ['Maximum five blocks per label.'] },
    { id: 'length', title: 'Fixed label length', kw: 'label length auto 30 300 mm lock',
      steps: ['[Fn] → {Length} → [OK].', 'Pick {Auto} or 30–300 mm (1.2"–12") with [▲] / [▼] or the number keys, then [OK].'],
      notes: ['{Text too long} means the text no longer fits. Shorten it or return to Auto ([Space] in the setting).'] },
    { id: 'cut', title: 'Cut options (Small / Large / Chain / No Cut / Special Tape)', kw: 'cut margin chain waste tape cutter special fabric',
      steps: ['[Fn] → {Cut Option} → [OK].', 'Pick {Small Margin} (2 mm), {Large Margin} (25 mm), {Chain}, {No Cut} or {Special Tape}, then [OK].'],
      notes: ['The first label still has about 23 mm of lead-in (print head to cutter). After Chain or No Cut, press Shift + Preview to feed and cut the last label.', 'Use No Cut / Special Tape for fabric iron-on, then cut with scissors.'] },
    { id: 'chain', title: 'Chain print: many labels, less waste', kw: 'chain print batch feed waste',
      steps: ['[Fn] → {Cut Option} → {Chain} → [OK].', 'Print each label. After the last one, press [Shift] + [Preview] and choose Feed & Cut.'],
      notes: ['If you skip the final feed, the last label can be cut short.'] },
    { id: 'print', title: 'Print and copies', kw: 'print copies 99 cutter',
      steps: ['Press [Print].', 'Set copies with [▲] / [▼] or the number keys (or [OK] for one).', 'Press [Print] or [OK].'],
      notes: ['Do not pull the tape while it is ejecting, and do not block the exit slot.'] },
    { id: 'numbering', title: 'Sequential numbering', kw: 'numbering serial increment copies 99',
      steps: ['Type the text including the number.', '[Shift] + [Print] → {Number} → [OK].', 'Set the start and end with [◀] / [▶], then [OK].', 'Set copies and print.'],
      notes: ['Up to 99 labels per run.'] },
    { id: 'mirror', title: 'Mirror print (glass and windows)', kw: 'mirror reverse window glass clear tape',
      steps: ['Type the text.', '[Shift] + [Print] → {Mirror} → [OK].', 'Press [Print] or [OK].'],
      notes: ['Use clear tape so the label reads correctly from the other side of the glass.'] },
    { id: 'preview', title: 'Preview a label', kw: 'preview zoom lcd check',
      steps: ['Press [Preview].', 'Scroll with the cursor keys. Shift + a cursor key jumps to that edge.', 'Press [Scale/Zoom] to change magnification.', 'Leave with [Esc].'] },
    { id: 'feed', title: 'Feed tape', kw: 'feed cut blank tape fabric',
      steps: ['[Shift] + [Preview].', 'Pick {Feed & Cut} or {Feed Only}, then [OK].'],
      notes: ['Feed Only is recommended for fabric iron-on tape, which you then cut with scissors.'] },
    { id: 'barcode', title: 'Barcodes', kw: 'barcode CODE39 CODE128 EAN UPC ITF CODABAR GS1',
      steps: ['[Fn] → {Barcode} → [OK].', 'Set Protocol, Width (use Large when you can), Under# and C.Digit, then enter the data.', 'Up to five barcodes per label.'],
      notes: ['Print black on white. {Check no. of digits entered} means the data length does not match the protocol.'] },
    { id: 'table', title: 'Table format', kw: 'table rows columns grid auto format',
      steps: ['[Home] → {Auto Format} → {Table Format} → [OK].', 'Pick the tape width, then set Rows and Columns.', 'Type each cell, then print or save.'],
      notes: ['Row limit follows the tape: 7 / 5 / 3 / 2 lines.'] },
    { id: 'files', title: 'Save, open, print and mark files (99 slots)', kw: 'save file memory 99 open delete mark colour',
      steps: ['Save: [Fn] → {Save} → pick a slot → [OK].', 'Open / print / delete / mark: [Home] → {File} → pick a slot → pick the action.', 'Marking stores the file in one of eight colour categories.'],
      notes: ['280 characters per file. Files are lost if power is gone for more than two minutes without batteries.'] },
    { id: 'history', title: 'Symbol History (last 30)', kw: 'symbol history recent',
      steps: ['[Home] → {Settings} → {Symbol History} → {On} or {Off}.', 'With History on, [Symbol] lists the last 30 symbols first.'] },
    { id: 'accents', title: 'Accented characters', kw: 'accent e n u umlaut tilde',
      steps: ['Type the letter.', 'Press [Accent] and cycle with [Accent] or [▲] / [▼].', 'Press [OK].'],
      notes: ['The set depends on the LCD language. See the Accent table under Symbols.'] },
    { id: 'clear', title: 'Clear text and/or formatting', kw: 'clear delete erase text format',
      steps: ['[BS] deletes one character.', '[Clear] → {Text Only} or {Text & Format} → [OK].', 'Shift + BS deletes the current line.'] },
    { id: 'tabs', title: 'Tabs', kw: 'tab length indent',
      steps: ['Press [Tab] to insert a tab.', '[Fn] → {Tab Length} → 0–100 mm (0–4.0") → [OK].'] },
    { id: 'reminder', title: 'Text Reminder (autocomplete)', kw: 'autocomplete words brother reminder',
      steps: ['Type a letter and press [OK] to see stored words starting with that letter.', '[Home] → {Settings} to turn Text Reminder on or off, or to clear its memory.'] },
    { id: 'clock', title: 'Time stamp and clock', kw: 'date time stamp clock format',
      steps: ['Set the clock: [Home] → {Settings} → {Set Clock}.', 'Format: {Time & Date Format}.', 'Stamp: {Time Stamp Setting} for Auto/Fixed, Date / D&T / Time / T&D, and optional Forward date.'],
      notes: ['Keep AA cells in so the clock survives unplugging.'] },
    { id: 'bluetooth', title: 'Bluetooth', kw: 'bluetooth wireless iphone android iprint',
      steps: ['[Shift] + [Home], or [Home] → {Settings} → {Bluetooth} → {Bluetooth (On/Off)}.', 'Pair from Brother iPrint&Label or P-touch Editor.'],
      notes: ['Bluetooth 5.0, SPP / iAP2. The device cannot pair with two hosts at once.'] },
    { id: 'language-unit', title: 'Language and units', kw: 'language english unit inch mm',
      steps: ['Language: [Home] → {Settings} → {Language}.', 'Unit: {Settings} → {Unit} → {inch} or {mm}.'] },
    { id: 'contrast', title: 'Display brightness and label-length trim', kw: 'brightness contrast lcd adjustment length',
      steps: ['[Home] → {Settings} → {Adjustment} → {Display Brightness} (−2 … +2).', '{Label Length} trim is −3 … +3 (about 1% of length per step) when a nearly-empty cassette prints short.'] },
    { id: 'input-mode', title: 'Label View vs Print Preview', kw: 'input mode lcd colour tape detection',
      steps: ['[Home] → {Settings} → {Input Mode} → {Label View} or {Print Preview}.', 'Tape Colour detection (default On) tints Label View to match the cassette.'] },
    { id: 'power', title: 'Batteries, adapter and auto power-off', kw: 'battery AA adapter AD-E001A power off',
      steps: ['Use 6 × AA alkaline (LR6), all new, same type.', 'Adapter AD-E001A only. Keep batteries in as memory/clock backup.', 'Auto power-off: Settings → Auto Power Off. Battery 5/10/30 min; AC 1/2/4/8 hr.'],
      notes: ['Power gone for more than two minutes without batteries clears the current text, format and saved files.'] },
    { id: 'tape', title: 'Change the tape cassette', kw: 'tape cassette TZe insert release lever',
      steps: ['Open the cassette cover.', 'Drop the TZe cassette in so the tape runs under the guides and does not catch the print head.', 'Close the cover. If it will not close, lift the release lever first.'],
      notes: ['Only Brother TZe tapes with the TZe mark. An empty cassette damages the head.'] },
    { id: 'clean', title: 'Clean the print head and cutter', kw: 'clean head swab TZe-CL4 cutter alcohol',
      steps: ['Unplug and remove the batteries.', 'Wipe the print head with a dry cotton swab or use cassette TZe-CL4.', 'About once a year, wipe the cutter blade with a cotton swab and isopropyl alcohol. Do not touch the blade.'] },
    { id: 'reset', title: 'Reset (LCD)', kw: 'reset factory erase memory locked up',
      steps: ['[Home] → {Settings} → {Reset} → pick a method → [OK] twice.', '{Reset All Settings} keeps files. {Erase All Content} clears files and keeps settings. {Factory Settings} clears both.'],
      notes: ['After Reset All Settings or Factory Settings you must set the language again.'] },
  ],

  errors: [
    ['Barcode error / Record: / Field:', 'A transferred database barcode used characters the protocol cannot encode.', 'Fix the database field or pick another protocol.'],
    ['Check no. of digits entered', 'Barcode data length does not match the protocol.', 'Enter the required number of digits.'],
    ['Cutter malfunction', 'Tape is jammed in the cutter.', 'Remove the jam. Turn the device off and on before continuing.'],
    ['Label too long', 'Printed length would exceed 999 mm (39.37").', 'Shorten the text.'],
    ['System error XX', 'Internal fault.', 'Contact Brother Customer Service and quote the number.'],
    ['Text too long', 'Text is longer than the fixed label length.', 'Shorten the text or set Length back to Auto.'],
  ],
  problems: [
    ['Nothing prints', 'Cassette missing, empty or not clicked in; cover open; device off; Bluetooth paired to another host; dirty print head (clean with a swab or TZe-CL4).'],
    ['Tape does not feed / jammed', 'Cut off a bent leader. Remove the cassette, clear the jam, feed the tape under the guides, re-insert.'],
    ['Too much blank tape on both sides', 'Cut Option → Small Margin or Chain. The first ~23 mm lead-in cannot be removed. After a Chain batch, Shift + Preview → Feed & Cut.'],
    ['LCD blank after power on', 'Check battery direction, replace all six AA cells, or seat the AD-E001A adapter.'],
    ['LCD in a foreign language', 'Settings → Language.'],
    ['Stops while printing', 'Striped leader means the cassette is empty. Weak batteries: replace all six or use the adapter.'],
    ['Saved files gone', 'Power was off more than two minutes without batteries. Keep AA cells in as backup.'],
    ['Screen locked / keys do nothing', 'Settings → Reset, or unplug and remove batteries for 10 minutes.'],
    ['Barcodes will not scan', 'Use black on white tape and Width = Large.'],
    ['Font will not go larger', 'Already at the maximum for this tape, or Length is fixed.'],
    ['Last Chain label cut wrong', 'Feed & Cut after the last copy.'],
    ['Firmware update failed', 'Restart and retry. Do not press keys until the Home Screen returns.'],
  ],
  tips: [
    'Type a frame number after Fn → Frame instead of scrolling 167 designs.',
    'History (first stop under Symbol) remembers the last 30 symbols.',
    'Shift + Fn formats one character; move the cursor to a line first to format that line only.',
    'Cable flags: Auto Format → Cable Labeling → Flag 1 / Flag 2. Fold around the cable so the text shows on both sides.',
    'Keep AA cells in even on the adapter. They back up the 99 files and the clock.',
    'Space inside a setting jumps back to its default (Auto length, brightness 0, …).',
    'Preview + Scale/Zoom is the quickest way to check a 7-line 24 mm layout before you print.',
  ],
};
