// DYMO LabelManager 280. Reference data for Labelarium.
// Source: official User Guide LM280_UserGuide_en-US.pdf (Rev. 12/2019) plus DYMO product page.
// Notation in steps: [Key] = a key on the device, {Text} = what the LCD shows, → = then.
// Catalog counts are from the printed grids in this guide: 132 symbols, 89 clip-art cells, 8 borders,
// 3 fonts, 6 point sizes, 7 printed text styles. This model has no template library and no
// Brother-style frame sheet. Symbol items: [name, keywords, unicode approximation].
export default {
  id: 'dymo-lm280',
  brand: 'DYMO',
  model: 'LabelManager 280',
  name: 'LabelManager 280',
  tagline: 'Rechargeable Portable Label Maker',
  links: [
    ['Official support & product page', 'https://www.dymo.com/label-makers-printers/labelmanager-label-makers/dymo-labelmanager-280-rechargeable-portable-label-maker/SP_95478.html'],
    ['DYMO support (software, manuals, FAQs)', 'https://support.dymo.com'],
  ],
  specs: [
    ['Tape', 'DYMO D1 tape cassettes, 6 / 9 / 12 mm (1/4" / 3/8" / 1/2")'],
    ['Print', 'Thermal transfer. Product page lists 15 mm/s. Two lines max (9 & 12 mm tape)'],
    ['Text', 'Graphical LCD. Buffer limit is the “Too Many Characters!” message. The guide does not state a character cap'],
    ['Fonts', '3 font types (Basic, Serif, Fun) · 6 point sizes (8–24 pt, tape-width limited) · 7 printed text styles'],
    ['Decorations', '8 borders · 132 symbols · 89 clip-art cells. No template library in this guide'],
    ['Memory', '9 saved labels (text and formatting). Saved text can be inserted into the current label without its formatting'],
    ['Power', 'Li-ion pack 7.2 V 600 mAh 4.32 Wh. Charge only in the label maker with adapter DSA-6PFG-12 Fc 120050 (12 V / 0.5 A). Full charge ~3 hours; after ~10 minutes of charging you can print. The adapter cannot power the maker. It only charges the pack'],
    ['Auto power off', 'After 2 minutes idle. Last label text and style are remembered when power returns'],
    ['Computer', 'USB on the top edge. Standalone, or print from DYMO desktop software (install software before plugging in USB)'],
    ['Item', '1815990 (DYMO product page)'],
  ],
  tapes: [
    { mm: 6, in: '1/4"', lines: 1, note: 'Single line only. Point sizes 8, 10, 12.' },
    { mm: 9, in: '3/8"', lines: 2, note: 'Two lines OK. One line: 8–20 pt. Two lines: 8 or 10 pt.' },
    { mm: 12, in: '1/2"', lines: 2, note: 'Two lines OK. One line: 8–24 pt. Two lines: 8, 10 or 12 pt.' },
  ],
  keyboard: {
    image: 'img/keyboard.png',
    legend: [
      [1, 'USB port', 'Mini-USB on the top edge. Connect only after the desktop software installer asks you to.'],
      [2, 'Power port', 'Charging-adapter jack on the top edge. Adapter charges the battery pack; it does not run the maker by itself.'],
      [3, 'LCD display', 'Graphical LCD. Feature indicators along the top and side turn black when that feature is on.'],
      [4, 'Cutter', 'Cutter button on the upper right. Blade is extremely sharp. Keep fingers clear when changing tape.'],
      [5, 'Italics', 'Toggle italic on or off.'],
      [6, 'Underline', 'Toggle underline on or off. On two-line labels each line is underlined. Underline does not print on a vertical label.'],
      [7, 'Vertical text', 'Toggle vertical text on or off. On a two-line vertical label, line 2 prints to the right of line 1.'],
      [8, 'Print / Copies', 'Print. Hold a few seconds to preview layout, or to set 1–10 copies.'],
      [9, 'Back', 'Exit a menu without making a selection (Cancel).'],
      [10, 'Save / Open', 'Save the current label (up to 9 memory slots) or hold to open a saved label.'],
      [11, 'Numeric keys', 'Digits 1–0. Also used to type a fixed label length.'],
      [12, 'Symbols', 'Jump to the symbol picker. Same library as [Menu] → Insert → Symbols.'],
      [13, 'Backspace', 'Delete the character to the left of the cursor. Also deletes an auto-number as one character.'],
      [14, 'Return', 'Start the second line (9 or 12 mm tape). Confirms some menu steps.'],
      [15, 'Space bar', 'Space.'],
      [16, 'Caps', 'Toggle capitals. Default is Caps on; when off, letters are lowercase.'],
      [17, 'Accented characters', 'Press this key then a letter, or press and hold a letter, to pick an accented variant.'],
      [18, 'Navigation', '◀ ▶ ▲ ▼ move in menus and along the label. [OK] in the centre confirms.'],
      [19, 'OK', 'Confirm a menu choice or insert the selected symbol / clip art.'],
      [20, 'New label / Clear', 'Clear label text and keep formatting, or clear both text and formatting.'],
      [21, 'Menu', 'Format, Insert, Open and Settings tabs.'],
      [22, 'On / Off', 'Power. Auto-off after two idle minutes.'],
      [23, 'Text size', 'Step the point size. Current size is shown on the LCD.'],
      [24, 'Bold', 'Toggle bold on or off. Combine with the italic and underline keys.'],
    ],
  },
  shortcuts: [
    { keys: '[Symbols] (the ,# key)', action: 'Open the symbol picker without going through Menu', kw: 'symbol shortcut' },
    { keys: '[Menu] → Insert → {Symbols} → [OK]', action: 'Insert a symbol from the 132-cell set', kw: 'symbol insert' },
    { keys: '[Menu] → Insert → {Clip Art} → [OK]', action: 'Insert clip art from the 89-cell set', kw: 'clip art pictograph' },
    { keys: 'hold a letter, or [Accent] then a letter', action: 'Accented characters (example on a: a à â æ …)', kw: 'accent accented umlaut tilde' },
    { keys: '[B] / [I] / [U]', action: 'Toggle bold, italic, underline', kw: 'bold italic underline style format' },
    { keys: '[Vertical]', action: 'Toggle vertical text', kw: 'vertical rotate' },
    { keys: '[AAA] (text size)', action: 'Step the point size', kw: 'size point 8 10 12 16 20 24' },
    { keys: '[Caps]', action: 'Toggle capitals (default on)', kw: 'caps lock uppercase lowercase' },
    { keys: '[Print] hold', action: 'Preview layout, or set 1–10 copies', kw: 'preview copies print hold' },
    { keys: '[Save/Open]', action: 'Save to one of 9 memory slots', kw: 'save memory file' },
    { keys: 'hold [Save/Open]', action: 'Open a saved label', kw: 'open recall memory file' },
    { keys: '[New label/Clear]', action: 'Clear text, or text and formatting', kw: 'clear new erase' },
    { keys: '[Back]', action: 'Leave a menu without changing anything', kw: 'cancel back escape' },
    { keys: '[Return]', action: 'Second line on 9 / 12 mm tape', kw: 'enter return two lines' },
    { keys: '[Menu] → Format', action: 'Font, size, style, borders, length, alignment, mirror', kw: 'format font border align mirror' },
    { keys: '[Menu] → Insert', action: 'Symbols, clip art, date and time, auto-numbering, saved text', kw: 'insert date time numbering' },
    { keys: '[Menu] → Settings', action: 'Language, label width, units (inches / mm)', kw: 'settings language width units' },
  ],
  fonts: [
    ['Basic', 'basic.png', 'Sans-serif. Shown as BASIC on the font LCD.', '"Helvetica Neue", Helvetica, Arial, sans-serif', 400, 'normal'],
    ['Serif', 'serif.png', 'Classic serif (Times-like).', 'Georgia, "Times New Roman", Times, serif', 400, 'normal'],
    ['Fun', 'fun.png', 'Rounded playful display.', '"Comic Sans MS", "Chalkboard SE", "Segoe Print", cursive', 400, 'normal'],
  ],
  sizes: [
    ['8 pt', '8pt.png', 8 / 24],
    ['10 pt', '10pt.png', 10 / 24],
    ['12 pt', '12pt.png', 12 / 24],
    ['16 pt', '16pt.png', 16 / 24],
    ['20 pt', '20pt.png', 20 / 24],
    ['24 pt', '24pt.png', 1],
  ],
  widths: [
    ['Normal', 'width-normal.png', 1],
  ],
  styles: [
    ['Normal', 'style-normal.png'],
    ['Bold', 'style-bold.png'],
    ['Italic', 'style-italic.png'],
    ['Underline', 'style-underline.png'],
    ['Vertical', 'style-vertical.png'],
    ['Outline', 'style-outline.png'],
    ['Shadow', 'style-shadow.png'],
  ],
  alignments: [
    ['Left', 'align-left.png'],
    ['Center', 'align-center.png'],
    ['Right', 'align-right.png'],
  ],
  fontNote: 'Three font types, six point sizes and seven text styles are printed in this guide. Available point sizes depend on tape width and on whether the label is one or two lines (see Tapes). The text size applies to every character on the label. Some styles can be combined with the [B], [I] and [U] keys. This guide has no character-width (×2 / ×½) setting. Alignment (left / centre / right) applies only to fixed-length labels; variable-length labels are always centred.',

  symbols: {
    howto: [
      'Symbols: press the [Symbols] key (,#), or [Menu] → Insert → {Symbols} → [OK].',
      'Clip art: [Menu] → Insert → {Clip Art} → [OK].',
      'Use [◀] [▶] [▲] [▼] to move to the cell, then [OK] to insert.',
      'To leave without inserting press [Back].',
    ],
    categories: [
      { id: 'symbols', name: 'Symbols', group: 'Basic', key: ',#', kw: 'punctuation math currency fractions greek subscripts superscripts', items: [
        ['Question mark', 'question mark ?', '?'],
        ['Exclamation mark', 'exclamation bang !', '!'],
        ['Underscore', 'underscore underline _', '_'],
        ['Hyphen', 'hyphen minus dash -', '-'],
        ['Colon', 'colon :', ':'],
        ['Apostrophe', 'apostrophe quote single \'', '\''],
        ['Quotation mark', 'quote double "', '"'],
        ['Comma', 'comma ,', ','],
        ['Period', 'period full stop dot .', '.'],
        ['Semicolon', 'semicolon ;', ';'],
        ['Right single quote', 'apostrophe curly quote ’', '’'],
        ['Inverted exclamation', 'inverted exclamation spanish ¡', '¡'],
        ['Inverted question mark', 'inverted question spanish ¿', '¿'],
        ['Slash', 'slash solidus /', '/'],
        ['Backslash', 'backslash \\', '\\'],
        ['Ampersand', 'ampersand and &', '&'],
        ['At sign', 'at @ email', '@'],
        ['Hash', 'hash pound number #', '#'],
        ['Percent', 'percent %', '%'],
        ['Per mille', 'per mille permille ‰', '‰'],
        ['Vertical bar', 'pipe bar |', '|'],
        ['Left parenthesis', 'parenthesis open (', '('],
        ['Right parenthesis', 'parenthesis close )', ')'],
        ['Left curly brace', 'brace curly open {', '{'],
        ['Right curly brace', 'brace curly close }', '}'],
        ['Left square bracket', 'bracket square open [', '['],
        ['Right square bracket', 'bracket square close ]', ']'],
        ['Degree', 'degree temperature °', '°'],
        ['Bullet', 'bullet dot •', '•'],
        ['Asterisk', 'asterisk star *', '*'],
        ['Plus', 'plus add +', '+'],
        ['Minus', 'minus subtract −', '−'],
        ['Multiply', 'multiply times x ×', '×'],
        ['Divide', 'divide division ÷', '÷'],
        ['Square root', 'square root radical √', '√'],
        ['Caret', 'caret circumflex power ^', '^'],
        ['Tilde', 'tilde ~', '~'],
        ['Approximately equal', 'approximately almost equal ≈', '≈'],
        ['Equals', 'equals =', '='],
        ['Not equal', 'not equal ≠', '≠'],
        ['Plus-minus', 'plus-minus plusminus ±', '±'],
        ['Less than', 'less than <', '<'],
        ['Greater than', 'greater than >', '>'],
        ['Less than or equal', 'less equal ≤', '≤'],
        ['Greater than or equal', 'greater equal ≥', '≥'],
        ['Euro', 'euro currency €', '€'],
        ['Pound sterling', 'pound sterling gbp £', '£'],
        ['Dollar', 'dollar currency $', '$'],
        ['Cent', 'cent ¢', '¢'],
        ['Yen', 'yen yuan ¥', '¥'],
        ['Copyright', 'copyright ©', '©'],
        ['Registered', 'registered trademark ®', '®'],
        ['CE mark', 'CE european conformity', 'CE'],
        ['Trademark', 'trademark tm ™', '™'],
        ['Section', 'section silcrow §', '§'],
        ['One third', 'fraction one third ⅓', '⅓'],
        ['Two thirds', 'fraction two thirds ⅔', '⅔'],
        ['One eighth', 'fraction one eighth ⅛', '⅛'],
        ['Five eighths', 'fraction five eighths ⅝', '⅝'],
        ['Seven eighths', 'fraction seven eighths ⅞', '⅞'],
        ['One quarter', 'fraction one quarter ¼', '¼'],
        ['One half', 'fraction one half ½', '½'],
        ['Three quarters', 'fraction three quarters ¾', '¾'],
        ['Three eighths', 'fraction three eighths ⅜', '⅜'],
        ['Subscript 0', 'subscript 0 ₀', '₀'],
        ['Subscript 1', 'subscript 1 ₁', '₁'],
        ['Subscript 2', 'subscript 2 ₂', '₂'],
        ['Subscript 3', 'subscript 3 ₃', '₃'],
        ['Subscript 4', 'subscript 4 ₄', '₄'],
        ['Subscript 5', 'subscript 5 ₅', '₅'],
        ['Subscript 6', 'subscript 6 ₆', '₆'],
        ['Subscript 7', 'subscript 7 ₇', '₇'],
        ['Subscript 8', 'subscript 8 ₈', '₈'],
        ['Subscript 9', 'subscript 9 ₉', '₉'],
        ['Superscript 0', 'superscript 0 ⁰', '⁰'],
        ['Superscript 1', 'superscript 1 ¹', '¹'],
        ['Superscript 2', 'superscript 2 squared ²', '²'],
        ['Superscript 3', 'superscript 3 cubed ³', '³'],
        ['Superscript 4', 'superscript 4 ⁴', '⁴'],
        ['Superscript 5', 'superscript 5 ⁵', '⁵'],
        ['Superscript 6', 'superscript 6 ⁶', '⁶'],
        ['Superscript 7', 'superscript 7 ⁷', '⁷'],
        ['Superscript 8', 'superscript 8 ⁸', '⁸'],
        ['Superscript 9', 'superscript 9 ⁹', '⁹'],
        ['Alpha', 'greek alpha α', 'α'],
        ['Beta', 'greek beta β', 'β'],
        ['Gamma', 'greek gamma γ', 'γ'],
        ['Delta', 'greek delta δ', 'δ'],
        ['Epsilon', 'greek epsilon ε', 'ε'],
        ['Zeta', 'greek zeta ζ', 'ζ'],
        ['Eta', 'greek eta η', 'η'],
        ['Theta', 'greek theta θ', 'θ'],
        ['Iota', 'greek iota ι', 'ι'],
        ['Kappa', 'greek kappa κ', 'κ'],
        ['Lambda', 'greek lambda λ', 'λ'],
        ['Mu', 'greek mu micro μ', 'μ'],
        ['Nu', 'greek nu ν', 'ν'],
        ['Xi', 'greek xi ξ', 'ξ'],
        ['Omicron', 'greek omicron ο', 'ο'],
        ['Pi', 'greek pi π', 'π'],
        ['Rho', 'greek rho ρ', 'ρ'],
        ['Sigma', 'greek sigma σ', 'σ'],
        ['Tau', 'greek tau τ', 'τ'],
        ['Upsilon', 'greek upsilon υ', 'υ'],
        ['Phi', 'greek phi φ', 'φ'],
        ['Chi', 'greek chi χ', 'χ'],
        ['Psi', 'greek psi ψ', 'ψ'],
        ['Omega', 'greek omega ω', 'ω'],
        ['Capital alpha', 'greek Alpha Α', 'Α'],
        ['Capital beta', 'greek Beta Β', 'Β'],
        ['Capital gamma', 'greek Gamma Γ', 'Γ'],
        ['Capital delta', 'greek Delta Δ', 'Δ'],
        ['Capital epsilon', 'greek Epsilon Ε', 'Ε'],
        ['Capital zeta', 'greek Zeta Ζ', 'Ζ'],
        ['Capital eta', 'greek Eta Η', 'Η'],
        ['Capital theta', 'greek Theta Θ', 'Θ'],
        ['Capital iota', 'greek Iota Ι', 'Ι'],
        ['Capital kappa', 'greek Kappa Κ', 'Κ'],
        ['Capital lambda', 'greek Lambda Λ', 'Λ'],
        ['Capital mu', 'greek Mu Μ', 'Μ'],
        ['Capital nu', 'greek Nu Ν', 'Ν'],
        ['Capital xi', 'greek Xi Ξ', 'Ξ'],
        ['Capital omicron', 'greek Omicron Ο', 'Ο'],
        ['Capital pi', 'greek Pi Π', 'Π'],
        ['Capital rho', 'greek Rho Ρ', 'Ρ'],
        ['Capital sigma', 'greek Sigma Σ', 'Σ'],
        ['Capital tau', 'greek Tau Τ', 'Τ'],
        ['Capital upsilon', 'greek Upsilon Υ', 'Υ'],
        ['Capital phi', 'greek Phi Φ', 'Φ'],
        ['Capital chi', 'greek Chi Χ', 'Χ'],
        ['Capital psi', 'greek Psi Ψ', 'Ψ'],
        ['Capital omega', 'greek Omega Ω', 'Ω']
      ]},
      { id: 'clipart', name: 'Clip art', group: 'Pictograph', key: 'Menu', kw: 'clip art arrows faces office hazard nature', items: [
        ['Arrow up (bold)', 'arrow up north', '⬆'],
        ['Arrow down (bold)', 'arrow down south', '⬇'],
        ['Arrow left (bold)', 'arrow left west', '⬅'],
        ['Arrow right (bold)', 'arrow right east', '➡'],
        ['Arrow up (outline)', 'arrow up outline', '↑'],
        ['Arrow down (outline)', 'arrow down outline', '↓'],
        ['Arrow up-right', 'arrow diagonal northeast', '↗'],
        ['Arrow down-right', 'arrow diagonal southeast', '↘'],
        ['Return arrow', 'return enter hook arrow', '↩'],
        ['Tab arrow', 'tab forward hook arrow', '↪'],
        ['Arrow left-right', 'arrow both ways horizontal', '↔'],
        ['Check mark', 'check tick ok yes', '✓'],
        ['X mark', 'x cross no close multiply', '✕'],
        ['Pointing right', 'hand finger point right', '👉'],
        ['Thumbs up', 'thumbs up like ok good', '👍'],
        ['Pointing left', 'hand finger point left', '👈'],
        ['Thumbs down', 'thumbs down no dislike', '👎'],
        ['Pointing up', 'hand finger point up', '☝️'],
        ['Telephone', 'phone landline call', '☎️'],
        ['Mobile phone', 'cell phone mobile', '📱'],
        ['Scissors', 'scissors cut', '✂️'],
        ['Smiling face', 'smile happy face', '🙂'],
        ['Frowning face', 'frown sad face', '🙁'],
        ['Neutral face', 'neutral meh face', '😐'],
        ['Man', 'man male person', '🚹'],
        ['Woman', 'woman female person', '🚺'],
        ['Line chart', 'chart graph statistics', '📈'],
        ['Money bag', 'money cash dollar bag', '💰'],
        ['Hourglass', 'hourglass time timer', '⏳'],
        ['Umbrella', 'umbrella rain weather', '☔'],
        ['No entry', 'no entry prohibited bar circle', '⛔'],
        ['Information', 'information info i', 'ℹ️'],
        ['Litter bin', 'litter trash garbage waste', '🚮'],
        ['Wheelchair', 'wheelchair accessible disability', '♿'],
        ['Skull and crossbones', 'skull poison toxic danger', '☠️'],
        ['First aid', 'first aid medical plus cross', '➕'],
        ['Folder', 'folder file directory', '📁'],
        ['Closed folder', 'folder file directory closed', '📁'],
        ['Document', 'document page paper', '📄'],
        ['Documents', 'documents pages stack papers', '📑'],
        ['Floppy disk', 'floppy disk save', '💾'],
        ['Keyboard', 'keyboard type', '⌨️'],
        ['Mouse', 'mouse computer', '🖱️'],
        ['Camera', 'camera photo', '📷'],
        ['Clapperboard', 'clapperboard film movie', '🎬'],
        ['Movie camera', 'movie camera video film', '🎥'],
        ['Laptop', 'laptop computer notebook', '💻'],
        ['Mailbox', 'mailbox post mail', '📫'],
        ['Envelope', 'envelope letter mail email', '✉️'],
        ['Open book', 'book read', '📖'],
        ['Flower', 'flower blossom', '🌸'],
        ['Environmentally hazardous', 'environment fish tree hazardous diamond', '🐟'],
        ['Warning', 'warning caution hazard exclamation diamond', '⚠️'],
        ['Toxic', 'toxic poison skull diamond', '☠️'],
        ['Flammable', 'flammable flame fire diamond', '🔥'],
        ['High voltage', 'high voltage lightning shock triangle', '⚡'],
        ['Radiation', 'radiation radioactive trefoil', '☢️'],
        ['No smoking', 'no smoking cigarette prohibited', '🚭'],
        ['Power', 'power standby on off', '⏻'],
        ['Calendar', 'calendar date day 1', '📅'],
        ['Flag', 'flag', '🚩'],
        ['Recycle', 'recycle recycling eco', '♻️'],
        ['Wine glass', 'wine glass drink fragile', '🍷'],
        ['This way up', 'this way up arrows package', '⏫'],
        ['Van', 'van truck vehicle', '🚐'],
        ['Starburst', 'starburst asterisk flower', '✳️'],
        ['Apple', 'apple fruit', '🍎'],
        ['Sailboat', 'sailboat yacht sailing', '⛵'],
        ['Bug', 'bug beetle insect', '🐞'],
        ['Butterfly', 'butterfly insect', '🦋'],
        ['Cactus', 'cactus plant desert', '🌵'],
        ['Car', 'car automobile vehicle', '🚗'],
        ['Cherries', 'cherries fruit', '🍒'],
        ['Fish', 'fish', '🐟'],
        ['Airplane', 'airplane plane flight', '✈️'],
        ['Eight ball', 'eight ball 8-ball pool', '🎱'],
        ['Tomato', 'tomato fruit vegetable', '🍅'],
        ['Eighth note', 'music note eighth quaver', '♪'],
        ['Circle', 'circle shape', '○'],
        ['Triangle', 'triangle shape', '△'],
        ['Square', 'square rectangle shape', '□'],
        ['Padlock', 'padlock lock secure', '🔒'],
        ['Key', 'key lock', '🔑'],
        ['Clock', 'clock time', '🕒'],
        ['Star', 'star', '★'],
        ['Spade', 'spade cards', '♠'],
        ['Club', 'club cards', '♣'],
        ['Heart', 'heart love cards', '♥'],
        ['Diamond', 'diamond cards', '♦']
      ]},
    ],
    accented: {
      image: 'img/symbols/accented.png',
      howto: [
        'Two methods in this guide: press [Accent] then the letter, or press and hold the letter.',
        'After you press the letter, every available variant for it is shown.',
        'Use [◀] / [▶] to the one you want, then [OK].',
        'The only worked example in this English guide is hold [a] → a à â æ and so on.',
      ],
      table: { a: 'a à â æ …' },
    },
  },

  frames: {
    howto: [
      'Press [Menu], select the Format tab, then [OK].',
      'Select Borders, then [OK].',
      'Use [▲] / [▼] to the border, then [OK].',
      'On two-line labels both lines sit inside one border.',
    ],
    notes: [
      'This guide prints eight border styles (the ABC 123 samples). There is no 99-frame Brother-style sheet.',
      'Borders wrap the whole label, both lines included.',
    ],
    items: [
      ['off', 'No border', 'none off plain remove'],
      [1, 'Rectangle', 'box rectangle border simple'],
      [2, 'Folded banner', 'banner folded ribbon tag'],
      [3, 'Rounded rectangle', 'rounded box rectangle'],
      [4, 'Speech bubble', 'speech bubble talk comment'],
      [5, 'Chevron ends', 'chevron pointed ends banner'],
      [6, 'Flowers', 'flowers floral ends'],
      [7, 'Diamond ends', 'diamond hexagon pointed ends'],
      [8, 'Ribbon', 'ribbon banner ends']
    ],
  },

  templates: {
    notes: [
      'The LabelManager 280 user guide has no template library (no text-label or pattern-label designs).',
      'Use fonts, styles, borders, symbols and clip art on a normal label instead.',
    ],
    textHowto: [
      'This model has no text templates in the official guide.',
    ],
    patternHowto: [
      'This model has no pattern templates in the official guide.',
    ],
    text: [],
    pattern: [],
  },

  howto: [
    { id: 'first', title: 'First-time setup', kw: 'language units width first on setup',
      steps: ['Press [On/Off].', 'Select the language → [OK].', 'Select inches or mm → [OK].', 'Select the width of the cassette that is in the maker → [OK].'],
      notes: ['You are asked for the cassette width every time you insert tape, because some features depend on it. You can change language, units and width later under [Menu] → Settings.'] },
    { id: 'tape', title: 'Insert a D1 tape cassette', kw: 'tape cassette D1 insert replace jam ribbon guides',
      steps: ['Lift the cassette cover.', 'Make sure the tape and ribbon are taut across the mouth of the cassette and the tape runs between the label guides. Turn the ribbon rewind spool clockwise if needed.', 'Insert the cassette until it clicks.', 'Close the cover.', 'When prompted, set the label width to match the cassette.'],
      notes: ['Cutter blade is extremely sharp. Keep fingers away and do not press the cutter while changing tape.', '6 / 9 / 12 mm (1/4" / 3/8" / 1/2") DYMO D1 cassettes.'] },
    { id: 'battery', title: 'Battery pack and charging', kw: 'battery charge adapter lithium li-ion power',
      steps: ['Slide the battery-compartment cover off (adapter unplugged).', 'Insert the Li-ion pack and replace the cover.', 'Plug the charging adapter into the top jack, then into the wall.', 'Charge about 3 hours for a full charge. After about 10 minutes of charging you can print.'],
      notes: ['Use only adapter DSA-6PFG-12 Fc 120050 (12 V / 0.5 A). The adapter cannot power the maker; it only charges the pack.', 'Remove the pack if the maker will sit unused for a long time.', 'Stop charging if it is not finished within three hours. Charge only at +10 °C to 35 °C.'] },
    { id: 'font', title: 'Font type, size and style', kw: 'font basic serif fun size point style bold italic underline outline shadow vertical',
      steps: ['Font type: [Menu] → Format → [OK] → Font → [OK] → [▲] / [▼] to Basic, Serif or Fun → [OK].', 'Size: press [AAA], or [Menu] → Format → the current size → [OK] → [◀] / [▶] to 8 / 10 / 12 / 16 / 20 / 24 pt → [OK].', 'Style: [Menu] → Format → Style → [OK] → [▲] / [▼] to the style → [OK]. Or toggle [B], [I], [U] and [Vertical] directly.'],
      notes: ['The guide prints seven styles (Normal, Bold, Italic, Underline, Vertical, Outline, Shadow) even though the sentence says “six”.', 'Point size applies to the whole label. Available sizes depend on tape width and line count.', 'Underline does not print on a vertical label. On multi-line labels each line is underlined.'] },
    { id: 'border', title: 'Add a border', kw: 'border frame box decoration',
      steps: ['[Menu] → Format → [OK] → Borders → [OK].', '[▲] / [▼] to one of the eight styles → [OK].'],
      notes: ['Both lines of a two-line label sit inside one border.'] },
    { id: 'mirror', title: 'Mirror text', kw: 'mirror reverse glass window',
      steps: ['[Menu] → Format → [OK] → Mirror → [OK].', '[◀] / [▶] to On → [OK].'] },
    { id: 'vertical', title: 'Vertical labels', kw: 'vertical rotate sideways spine',
      steps: ['Press [Vertical].', 'Type the text.', 'Press [Print].'],
      notes: ['On a two-line vertical label, line 2 prints to the right of line 1. Underline will not print.'] },
    { id: 'length', title: 'Fixed-length labels', kw: 'label length fixed 40 400 mm auto variable',
      steps: ['[Menu] → Format → [OK] → Label length → [OK].', '[◀] / [▶] to Fixed.', '[▲] / [▼] or the number keys for 40–400 mm (1.5"–15") → [OK].'],
      notes: ['Text is scaled to fit. If it cannot fit, you are asked to print a variable-length label instead. Fixed length stays on until you switch back to variable.'] },
    { id: 'align', title: 'Align text (fixed-length only)', kw: 'alignment left center right justify fixed length',
      steps: ['[Menu] → Format → [OK] → Alignment → [OK].', '[◀] / [▶] to Left, Centre or Right → [OK].'],
      notes: ['Default is centred. Alignment is ignored on variable-length labels. Those always print centred. This guide has no justify setting.'] },
    { id: 'two-lines', title: 'Two-line labels', kw: 'two lines return enter 6 mm',
      steps: ['Type line 1.', 'Press [Return].', 'Type line 2.', 'Press [Print].'],
      notes: ['Maximum two lines. 6 mm (1/4") tape is one line only.'] },
    { id: 'symbol', title: 'Insert a symbol', kw: 'symbol punctuation greek',
      steps: ['Press [Symbols], or [Menu] → Insert → {Symbols} → [OK].', 'Move with the navigation keys to the cell.', 'Press [OK].'] },
    { id: 'clipart', title: 'Insert clip art', kw: 'clip art pictograph icon',
      steps: ['[Menu] → Insert → {Clip Art} → [OK].', 'Move with the navigation keys to the image.', 'Press [OK].'] },
    { id: 'accents', title: 'Accented characters', kw: 'accent accented latin a à â æ',
      steps: ['Press [Accent] then the letter, or press and hold the letter.', 'When the variants appear, [◀] / [▶] to the one you want → [OK].'],
      notes: ['Worked example in this guide: hold [a] and you see a à â æ and the rest of that letter’s set.'] },
    { id: 'datetime', title: 'Date and time', kw: 'date time clock notation',
      steps: ['Format: [Menu] → Settings → Date/Time → Notation → pick a date or date-and-time format → [OK].', 'Set date: [Menu] → Settings → Date/Time → Set date → day, month, year → [OK], then [Back] twice.', 'Set time: [Menu] → Settings → Date/Time → Set time → hour and minutes → [OK], then [Back] twice.', 'Insert: [Menu] → Insert → {Date and Time} → [OK].'] },
    { id: 'numbering', title: 'Auto-numbering', kw: 'auto-numbering serial 0-9 A-Z a-z copies 10',
      steps: ['[Menu] → Insert → {Auto-numbering} → [OK].', 'Pick numeric (0–9), uppercase (A–Z) or lowercase (a–z) → [OK].', 'Set start and end values → [OK].'],
      notes: ['Up to 10 labels in the series. You can put text before and after the number. Only one auto-number per label. Delete it as one character with [Backspace] at the end of the number.'] },
    { id: 'print', title: 'Print, preview and copies', kw: 'print copies preview hold cutter peel backing',
      steps: ['Type the label.', 'Preview / copies: hold [Print] a few seconds. The LCD shows length, width and layout; [▲] / [▼] sets 1–10 copies, then [OK].', 'A short press of [Print] prints. Press the cutter button to cut.', 'Peel: find the split in the backing, pinch the label lengthwise toward the printed side so the backing separates, then peel.'],
      notes: ['After a copies run the copy count returns to 1.'] },
    { id: 'files', title: 'Save, open and insert saved text (9 slots)', kw: 'save open memory 9 slots insert saved text',
      steps: ['Save: press [Save/Open]. The first free slot is shown. Move to a slot (you may overwrite) → [OK]. Text and formatting are stored.', 'Open: hold [Save/Open], or [Menu] → Open, then pick a slot → [OK].', 'Insert saved text only: put the cursor where you want it → [Menu] → Insert → {Saved text} → pick a slot → [OK]. Formatting is not inserted.'] },
    { id: 'settings', title: 'Language, label width and units', kw: 'language width units inch mm settings',
      steps: ['Language: [Menu] → Settings → current language → [OK] → [▲] / [▼] → [OK].', 'Label width: [Menu] → Settings → current width → [OK] → [◀] / [▶] → [OK]. You can set this even if a different cassette is inserted.', 'Units: [Menu] → Settings → units → English (inches) or Metric (default).'] },
    { id: 'clean', title: 'Clean the cutter and print head', kw: 'clean cutter blade print head alcohol swab tool',
      steps: ['Cutter: remove the cassette. Press and hold the cutter button to expose the blade. Wipe both sides with a cotton swab and alcohol.', 'Print head: remove the cassette. Take the cleaning tool from inside the cover (or contact DYMO if it is missing). Wipe the padded side of the tool across the print head.'],
      notes: ['The cutter blade is extremely sharp. Clean it each time you change tape.'] },
    { id: 'usb', title: 'Use with a computer', kw: 'usb computer software windows mac connect desktop',
      steps: ['Install DYMO desktop software from support.dymo.com before plugging in USB (close Office apps on Windows first).', 'Then plug USB into the top of the maker and into the computer.', 'Turn the maker on. If several DYMO printers are installed, pick LabelManager 280 in the software Print area.'] },
  ],

  errors: [
    ['No display', 'Maker is off, or the pack is flat.', 'Turn it on. Attach the charging adapter and recharge the pack.'],
    ['Poor print quality', 'Weak pack, dirty head, or a bad cassette.', 'Recharge. Clean the print head. Reseat or replace the D1 cassette.'],
    ['Auto-numbering already inserted', 'The label already has an auto-number. Only one is allowed.', 'Delete the existing auto-number with [Backspace] at the end of it, then insert again if needed.'],
    ['Battery Failure!', 'Pack not seated, or damaged.', 'Reseat the pack. Replace it if it still fails.'],
    ['Wait n minutes / Battery Charging', 'Pack is charging and is not ready to unplug.', 'Leave the adapter connected until charging finishes.'],
    ['Too Many Characters!', 'The edit buffer is full.', 'Delete text, use a smaller point size, drop a line, or insert a wider cassette.'],
    ['No label found. / Insert label cartridge.', 'No cassette in the compartment.', 'Insert a D1 cassette and set the label width.'],
    ['Label jam!', 'Motor stalled on jammed tape.', 'Open the cover, remove the cassette, clear the jam, clean the cutter, make sure tape and ribbon are taut across the mouth and through the guides.'],
    ['Printing...', 'Print in progress.', 'Wait. The message clears when printing finishes.'],
    ['Print label with variable length? / Label length exceeds fixed length.', 'Text does not fit the fixed length.', '[OK] prints variable length, or shorten the text / reduce size / drop a line / use wider tape.'],
    ['Too many lines for selected label width', 'Two lines on 6 mm tape, or more lines than the width allows.', 'Delete a line, reduce size, use 9 or 12 mm tape, or switch to variable length.'],
    ['Label Length Exceeds Fixed Length!', 'Same fit problem, shown as an error.', 'Delete text, or print with variable length.'],
    ['Charge Battery!', 'Pack is too low to print.', 'Attach the adapter, check the pack is seated, or replace the pack.'],
  ],
  problems: [
    ['Display stays blank', 'Confirm power is on and the pack is charging / charged. The adapter does not run the maker without a pack.'],
    ['Too much blank tape on the label', 'Use a fixed length (40–400 mm) if you need a specific size. Variable-length labels are sized to the text and are always centred.'],
    ['Nothing prints, or print is faint / broken', 'Recharge, clean the print head, reseat the cassette with tape under the guides, replace a worn cassette.'],
    ['Tape jammed', 'Open the cover, pull the cassette, clear jammed tape, rewind slack on the ribbon spool, clean the cutter, reinsert.'],
    ['Cutter does not cut cleanly', 'Clean both sides of the blade with alcohol (hold the cutter button to expose it).'],
    ['Want a fresh label', 'Press [New label/Clear] and pick text-only or text-and-format.'],
    ['How do I peel the backing?', 'DYMO labels have a split back. Pinch lengthwise toward the printed side so the split opens, then peel.'],
  ],
  tips: [
    'The ,# key opens symbols without walking through Menu → Insert.',
    'Hold a letter for accents; the guide’s example on [a] is a à â æ and the rest of that set.',
    'Hold [Print] both to preview length/layout and to set 1–10 copies.',
    'Nine memory slots keep text and formatting. Insert → Saved text pastes the words only, at the cursor.',
    'Set the cassette width when asked. Two-line labels and the larger point sizes need 9 or 12 mm tape.',
    'The charging adapter never runs the maker by itself. Keep a charged pack in, even at the desk.',
    'On two-line labels, one border wraps both lines; underline (if used) goes under each line.',
  ],
};
