// DYMO LabelManager 160. Reference data for Labelarium.
// Source: official User Guide LM160_UserGuide_en.pdf (Rev. 6/20) plus the DYMO product page.
// Catalogs are counted from the printed tables on page 9 of THIS guide, not borrowed from Brother.
// Clip art: 105 cells (21×5). Symbols: 123 cells (25×5 minus 2 empty grey cells). Total 228.
// Box/underline: 5 styles (page 8). One typeface, 6 point sizes, bold + italic (combinable), vertical key.
// No template library. Notation in steps: [Key] = a key on the device, {Text} = what the LCD shows, → = then.
export default {
  id: 'dymo-lm160',
  brand: 'DYMO',
  model: 'LM160',
  name: 'LabelManager 160',
  tagline: 'Portable Label Maker',
  links: [
    ['Official product & support page', 'https://www.dymo.com/label-makers-printers/labelmanager-label-makers/dymo-labelmanager-160-portable-label-maker/SP_95477.html'],
    ['DYMO support', 'https://support.dymo.com'],
    ['Register your label maker', 'https://www.dymo.com/register'],
  ],
  specs: [
    ['Tape', 'DYMO D1 label cassettes, 6 / 9 / 12 mm (1/4" / 3/8" / 1/2")'],
    ['Print', 'Thermal transfer, 180 dpi, 12 mm/s. Manual cutter button'],
    ['Text', 'Graphical LCD. Buffer limit shown as {Too many characters!}. Last label is remembered while power remains'],
    ['Fonts', '1 typeface · 6 sizes (8–24 pt, depends on tape width) · bold and italic (combinable) · vertical'],
    ['Decorations', '5 box/underline styles · 105 clip-art images · 123 symbols (228 together, as printed on page 9)'],
    ['Memory', 'Current label text and formatting survive power-off. Lost if batteries are removed and the adapter is unplugged'],
    ['Power', '6 × AAA alkaline, or optional adapter DSA-18PFM-09 Fc 090200 (9 V, 2 A) from Dee Van Enterprise Co., Ltd.'],
    ['Auto power off', 'After 2 minutes idle'],
    ['Size / weight', '203 × 118 × 49 mm, 350 g without batteries (manufacturer datasheet)'],
    ['Cutter', 'Manual cutter button. Clean the blade with alcohol when you change the cassette'],
  ],
  tapes: [
    { mm: 6, in: '1/4"', lines: 1, note: 'Single line only. Font sizes 8, 10 and 12 pt.' },
    { mm: 9, in: '3/8"', lines: 2, note: 'Two lines OK. Font sizes 8, 10, 12, 16 and 20 pt.' },
    { mm: 12, in: '1/2"', lines: 2, note: 'Two lines OK. All six font sizes: 8, 10, 12, 16, 20 and 24 pt.' },
  ],
  keyboard: {
    image: 'img/keyboard.png',
    legend: [
      [1, 'LCD display', 'Graphical preview of the label. Indicators along the top and bottom light when a feature is on: (1) uppercase, (2) lowercase, (3) accented characters, (4) font size, (5) bold, (6) italic, (7) underline/boxes, (8) vertical. See the LCD figure on page 6 of the user guide.'],
      [2, 'Italic', 'Toggle italic on or off. Applied to letters and symbols, not to clip art. Can be combined with bold.'],
      [3, 'Label exit slot', 'Printed label comes out here. Press the cutter button (6) to cut.'],
      [4, 'Underline/Boxes', 'Cycle the five box and underline styles (and off). A label can be underlined or boxed, not both.'],
      [5, 'Vertical', 'Print text oriented vertically. On two-line vertical labels, line 2 prints after line 1. Underline does not print on a vertical label.'],
      [6, 'Cutter button', 'Cuts the label. Keep fingers away from the blade when changing cassettes or cleaning.'],
      [7, 'Print', 'Print the label. {Printing...} shows until it finishes.'],
      [8, 'Cancel', 'Exit a menu without changing anything, or cancel an action such as printing.'],
      [9, 'OK', 'Confirm a menu choice or insert the selected symbol / clip art.'],
      [10, 'Symbols – Punctuation', 'Quick key into the punctuation symbols. Full symbol and clip-art sets are under [Menu].'],
      [11, 'Backspace', 'Delete the character to the left of the cursor. Hold to delete quickly.'],
      [12, 'Return', 'Start the second line (9 mm or 12 mm tape). A return mark shows on the LCD and is not printed.'],
      [13, 'Space bar', 'Insert a space.'],
      [14, 'Caps', 'Toggle uppercase / lowercase. Default is Caps on. The LCD uppercase or lowercase indicator lights.'],
      [15, 'Accented characters', 'Then press a letter to see its accent variants (à á â ã ä …). Or press and hold the letter key.'],
      [16, 'Navigation', '◀ / ▶ review and edit the label. All four arrows move through menus. [OK] confirms.'],
      [17, 'Menu', 'Opens Symbols/Clip Art and Settings tabs. Press again to switch tabs. Settings = language and label width.'],
      [18, 'On/Off', 'Power. Auto-off after 2 idle minutes. Text and formatting come back if power was not fully removed.'],
      [19, 'Font size', 'Cycle 8 / 10 / 12 / 16 / 20 / 24 pt. Available sizes depend on the tape width (see Specs).'],
      [20, 'Bold', 'Toggle bold on or off. Applied to letters and symbols, not to clip art. Can be combined with italic.'],
    ],
  },
  shortcuts: [
    { keys: '[.,#]', action: 'Jump to punctuation symbols', kw: 'punctuation symbols quick comma period hash' },
    { keys: '[Menu]', action: 'Open Symbols/Clip Art, or toggle to Settings (language and label width)', kw: 'menu clip art symbols settings language width' },
    { keys: '[Menu] → {Clip Art} → [OK]', action: 'Browse the 105 clip-art images', kw: 'clip art pictures icons' },
    { keys: '[Menu] → {Symbols} → [OK]', action: 'Browse the 123 symbols', kw: 'symbols punctuation greek math' },
    { keys: '[Accent] then a letter', action: 'Show accent variants of that letter; [OK] inserts', kw: 'accent international latin' },
    { keys: 'Hold a letter key', action: 'Same accent variants as [Accent]', kw: 'accent hold key' },
    { keys: '[Size] (AA)', action: 'Cycle font size', kw: 'size point 8 10 12 16 20 24' },
    { keys: '[B]', action: 'Toggle bold', kw: 'bold style' },
    { keys: '[I]', action: 'Toggle italic', kw: 'italic style' },
    { keys: '[Box]', action: 'Cycle underline and box styles', kw: 'box underline frame border' },
    { keys: '[Vertical]', action: 'Toggle vertical text', kw: 'vertical rotate' },
    { keys: 'Hold [Backspace]', action: 'Delete quickly to the left of the cursor', kw: 'clear delete backspace' },
    { keys: '[Cancel]', action: 'Leave a menu or cancel printing', kw: 'cancel escape exit' },
    { keys: '[Return]', action: 'Second line (9 mm / 12 mm tape)', kw: 'return enter two lines newline' },
    { keys: '[Caps]', action: 'Toggle upper / lower case (default Caps on)', kw: 'caps uppercase lowercase' },
  ],
  fonts: [
    ['Default', 'default.png', 'The LM160 has one typeface. The guide shows it as “ABC 123” on the box-style samples.', '"Helvetica Neue", Helvetica, Arial, sans-serif', 400, 'normal'],
  ],
  sizes: [
    ['24 pt', 'size-24.png', 1],
    ['20 pt', 'size-20.png', 20 / 24],
    ['16 pt', 'size-16.png', 16 / 24],
    ['12 pt', 'size-12.png', 12 / 24],
    ['10 pt', 'size-10.png', 10 / 24],
    ['8 pt', 'size-8.png', 8 / 24],
  ],
  widths: [['Normal', 'width-normal.png', 1]],
  styles: [
    ['Normal', 'style-normal.png'],
    ['Bold', 'style-bold.png'],
    ['Italic', 'style-italic.png'],
    ['Vertical', 'style-vertical.png'],
  ],
  alignments: [],
  fontNote: 'Six point sizes: 8, 10 and 12 pt on 6 mm (1/4") tape; those plus 16 and 20 pt on 9 mm (3/8"); all six including 24 pt on 12 mm (1/2"). Size applies to every character. Bold and italic toggle independently and can be combined; they apply to letters and symbols, not to clip art. This model has no extra typefaces, no character-width setting and no alignment menu.',

  symbols: {
    howto: [
      'Press [Menu]. If the Settings tab is showing, press [Menu] again to open the Symbols/Clip Art tab.',
      'Press [▲] / [▼] to select {Clip Art} or {Symbols}, then [OK].',
      'Use the navigation keys to highlight the image (positions below count left-to-right, top-to-bottom as printed on page 9), then [OK].',
      'Punctuation only: press [.,#] to jump straight into the punctuation symbols.',
      'Press [Cancel] to leave without inserting.',
    ],
    categories: [
      { id: 'symbols', name: 'Symbols', group: 'Basic', key: '.,#', kw: 'punctuation math currency greek subscript superscript', items: [
        ['Apostrophe', 'quote single quote', '\''],
        ['Quotation mark', 'quote double quotes', '"'],
        ['Comma', 'comma', ','],
        ['Period', 'full stop dot', '.'],
        ['Semicolon', 'semicolon', ';'],
        ['Exclamation mark', 'exclamation bang', '!'],
        ['Question mark', 'question', '?'],
        ['Inverted exclamation', 'spanish exclamation inverted', '¡'],
        ['Inverted question', 'spanish question inverted', '¿'],
        ['Underscore', 'underline dash bar', '_'],
        ['Right single quotation mark', 'apostrophe quote', '’'],
        ['Colon', 'colon', ':'],
        ['Slash', 'forward slash stroke', '/'],
        ['Backslash', 'backslash', '\\'],
        ['Vertical bar', 'pipe bar', '|'],
        ['Section', 'section sign silcrow legal', '§'],
        ['Bullet', 'dot bullet', '•'],
        ['Pilcrow', 'paragraph mark', '¶'],
        ['Degree', 'degrees temperature angle', '°'],
        ['Infinity', 'infinity forever', '∞'],
        ['Euro', 'euro currency money', '€'],
        ['Dollar', 'dollar currency money', '$'],
        ['Cent', 'cent currency money', '¢'],
        ['Pound', 'pound sterling currency money', '£'],
        ['Yen', 'yen yuan currency money', '¥'],
        ['At', 'at email', '@'],
        ['Ampersand', 'and ampersand', '&'],
        ['Hash', 'hash pound number', '#'],
        ['Percent', 'percent', '%'],
        ['Per mille', 'per thousand permille', '‰'],
        ['Plus', 'plus add', '+'],
        ['Minus', 'minus hyphen dash', '−'],
        ['Asterisk', 'star asterisk', '*'],
        ['Division', 'divide obelus', '÷'],
        ['Square root', 'root radical', '√'],
        ['Caret', 'circumflex hat power', '^'],
        ['Tilde', 'tilde approximately', '~'],
        ['Approximately equal', 'approx almost equal', '≈'],
        ['Equals', 'equals', '='],
        ['Not equal', 'not equals inequality', '≠'],
        ['Plus-minus', 'plus minus', '±'],
        ['Less than', 'less', '<'],
        ['Greater than', 'greater', '>'],
        ['Less than or equal', 'less equal', '≤'],
        ['Greater than or equal', 'greater equal', '≥'],
        ['Left square bracket', 'bracket square', '['],
        ['Right square bracket', 'bracket square', ']'],
        ['One half', 'fraction half', '½'],
        ['One quarter', 'fraction quarter', '¼'],
        ['Three quarters', 'fraction three quarters', '¾'],
        ['Left parenthesis', 'paren open', '('],
        ['Right parenthesis', 'paren close', ')'],
        ['Left curly brace', 'brace curly', '{'],
        ['Right curly brace', 'brace curly', '}'],
        ['One third', 'fraction third', '⅓'],
        ['Subscript 0', 'subscript 0 lower', '₀'],
        ['Subscript 1', 'subscript 1 lower', '₁'],
        ['Subscript 2', 'subscript 2 lower', '₂'],
        ['Subscript 3', 'subscript 3 lower', '₃'],
        ['Subscript 4', 'subscript 4 lower', '₄'],
        ['Subscript 5', 'subscript 5 lower', '₅'],
        ['Subscript 6', 'subscript 6 lower', '₆'],
        ['Subscript 7', 'subscript 7 lower', '₇'],
        ['Subscript 8', 'subscript 8 lower', '₈'],
        ['Subscript 9', 'subscript 9 lower', '₉'],
        ['Superscript 0', 'superscript 0 power', '⁰'],
        ['Superscript 1', 'superscript 1 power', '¹'],
        ['Superscript 2', 'superscript 2 power', '²'],
        ['Superscript 3', 'superscript 3 power', '³'],
        ['Superscript 4', 'superscript 4 power', '⁴'],
        ['Superscript 5', 'superscript 5 power', '⁵'],
        ['Superscript 6', 'superscript 6 power', '⁶'],
        ['Superscript 7', 'superscript 7 power', '⁷'],
        ['Superscript 8', 'superscript 8 power', '⁸'],
        ['Superscript 9', 'superscript 9 power', '⁹'],
        ['Greek alpha', 'greek alpha α', 'α'],
        ['Greek beta', 'greek beta β', 'β'],
        ['Greek gamma', 'greek gamma γ', 'γ'],
        ['Greek delta', 'greek delta δ', 'δ'],
        ['Greek epsilon', 'greek epsilon ε', 'ε'],
        ['Greek zeta', 'greek zeta ζ', 'ζ'],
        ['Greek eta', 'greek eta η', 'η'],
        ['Greek theta', 'greek theta θ', 'θ'],
        ['Greek iota', 'greek iota ι', 'ι'],
        ['Greek kappa', 'greek kappa κ', 'κ'],
        ['Greek lambda', 'greek lambda λ', 'λ'],
        ['Greek mu', 'greek mu μ', 'μ'],
        ['Greek nu', 'greek nu ν', 'ν'],
        ['Greek xi', 'greek xi ξ', 'ξ'],
        ['Greek omicron', 'greek omicron ο', 'ο'],
        ['Greek pi', 'greek pi π', 'π'],
        ['Greek rho', 'greek rho ρ', 'ρ'],
        ['Greek sigma', 'greek sigma σ', 'σ'],
        ['Greek tau', 'greek tau τ', 'τ'],
        ['Greek upsilon', 'greek upsilon υ', 'υ'],
        ['Greek phi', 'greek phi φ', 'φ'],
        ['Greek chi', 'greek chi χ', 'χ'],
        ['Greek psi', 'greek psi ψ', 'ψ'],
        ['Greek omega', 'greek omega ω', 'ω'],
        ['Greek Alpha', 'greek alpha capital uppercase Α', 'Α'],
        ['Greek Beta', 'greek beta capital uppercase Β', 'Β'],
        ['Greek Gamma', 'greek gamma capital uppercase Γ', 'Γ'],
        ['Greek Delta', 'greek delta capital uppercase Δ', 'Δ'],
        ['Greek Epsilon', 'greek epsilon capital uppercase Ε', 'Ε'],
        ['Greek Zeta', 'greek zeta capital uppercase Ζ', 'Ζ'],
        ['Greek Eta', 'greek eta capital uppercase Η', 'Η'],
        ['Greek Theta', 'greek theta capital uppercase Θ', 'Θ'],
        ['Greek Iota', 'greek iota capital uppercase Ι', 'Ι'],
        ['Greek Kappa', 'greek kappa capital uppercase Κ', 'Κ'],
        ['Greek Lambda', 'greek lambda capital uppercase Λ', 'Λ'],
        ['Greek Mu', 'greek mu capital uppercase Μ', 'Μ'],
        ['Greek Nu', 'greek nu capital uppercase Ν', 'Ν'],
        ['Greek Xi', 'greek xi capital uppercase Ξ', 'Ξ'],
        ['Greek Omicron', 'greek omicron capital uppercase Ο', 'Ο'],
        ['Greek Pi', 'greek pi capital uppercase Π', 'Π'],
        ['Greek Rho', 'greek rho capital uppercase Ρ', 'Ρ'],
        ['Greek Sigma', 'greek sigma capital uppercase Σ', 'Σ'],
        ['Greek Tau', 'greek tau capital uppercase Τ', 'Τ'],
        ['Greek Upsilon', 'greek upsilon capital uppercase Υ', 'Υ'],
        ['Greek Phi', 'greek phi capital uppercase Φ', 'Φ'],
        ['Greek Chi', 'greek chi capital uppercase Χ', 'Χ'],
        ['Greek Psi', 'greek psi capital uppercase Ψ', 'Ψ'],
        ['Greek Omega', 'greek omega capital uppercase Ω', 'Ω'],
      ]},
      { id: 'clipart', name: 'Clip Art', group: 'Pictograph', key: 'Menu', kw: 'clip art pictures icons', items: [
        ['Use litter bin', 'trash garbage waste rubbish dispose tidy recycle bin', '🚮'],
        ['Umbrella', 'rain weather', '☔'],
        ['This way up', 'arrows up orientation package shipping box', '⏫'],
        ['Fragile (broken glass)', 'glass breakable handle with care shipping wine', '🍷'],
        ['Recycle', 'recycling eco environment triangle arrows', '♻️'],
        ['Wheelchair accessible', 'disabled accessibility handicap', '♿'],
        ['Man', 'male person restroom gents', '🚹'],
        ['Woman', 'female person restroom ladies', '🚺'],
        ['Flammable', 'fire flame burn hazard', '🔥'],
        ['Warning', 'caution danger hazard attention alert exclamation', '⚠️'],
        ['Information', 'info help i', 'ℹ️'],
        ['Skull and crossbones', 'poison toxic danger death hazard', '☠️'],
        ['No entry', 'do not enter stop prohibited', '⛔'],
        ['Pointing left', 'hand finger left', '👈'],
        ['Pointing right', 'hand finger right', '👉'],
        ['Arrow up', 'up direction', '↑'],
        ['Arrow down', 'down direction', '↓'],
        ['Arrow left', 'left direction', '←'],
        ['Arrow right', 'right direction', '→'],
        ['Pointing up', 'hand finger up', '☝️'],
        ['Telephone', 'phone landline call', '☎️'],
        ['Mobile phone', 'cell phone cordless handset', '📱'],
        ['Scissors', 'cut craft', '✂️'],
        ['Open book', 'read reading textbook', '📖'],
        ['Mailbox', 'post letterbox mail', '📫'],
        ['Envelope', 'mail letter email post', '✉️'],
        ['Flag', 'pennant banner', '🚩'],
        ['Money bag', 'dollar cash money', '💰'],
        ['Hourglass', 'timer sand time', '⏳'],
        ['Push pin', 'thumbtack pin notice board', '📌'],
        ['Folder', 'file directory open', '📂'],
        ['File folder', 'file directory closed tab', '📁'],
        ['Document', 'page paper sheet', '📄'],
        ['Documents', 'pages papers stack copies', '📑'],
        ['Filing cabinet', 'files drawers office storage', '🗄️'],
        ['Keyboard', 'type computer keys', '⌨️'],
        ['Mouse', 'computer pointer', '🖱️'],
        ['Laptop', 'computer notebook PC', '💻'],
        ['Floppy disk', 'save diskette storage', '💾'],
        ['Line chart', 'graph statistics report finance', '📈'],
        ['Paperclip', 'clip attach office', '📎'],
        ['Clock', 'time schedule', '🕒'],
        ['Calendar', 'date day 1 schedule', '📅'],
        ['Television', 'TV monitor screen display', '📺'],
        ['CD', 'disc DVD compact disk', '💿'],
        ['Copyright', 'copyright C legal', '©'],
        ['Registered', 'registered trademark R legal', '®'],
        ['Trademark', 'TM legal brand', '™'],
        ['CE mark', 'CE European conformity', 'CE'],
        ['Pencil', 'write draw', '✏️'],
        ['Cherries', 'fruit', '🍒'],
        ['Coffee cup', 'tea mug hot drink', '☕'],
        ['Teapot', 'kettle tea pot', '🫖'],
        ['Bananas', 'fruit', '🍌'],
        ['Apple', 'fruit', '🍎'],
        ['Cheese', 'dairy food', '🧀'],
        ['Wine', 'bottle glass drink cocktail', '🍷'],
        ['Table tennis', 'ping pong paddle ball sport', '🏓'],
        ['Ice hockey', 'hockey stick puck sport', '🏒'],
        ['American football', 'rugby ball sport', '🏈'],
        ['Cycling', 'bicycle bike sport rider', '🚴'],
        ['Soccer ball', 'football sport', '⚽'],
        ['Baseball', 'ball sport', '⚾'],
        ['Bowling', 'pin ball sport', '🎳'],
        ['Gymnastics', 'gymnast dancer sport stretch', '🤸'],
        ['Car', 'automobile vehicle front', '🚗'],
        ['Truck', 'lorry delivery van', '🚚'],
        ['Fire engine', 'fire truck ladder emergency', '🚒'],
        ['Train', 'locomotive rail steam', '🚂'],
        ['Motorcycle', 'motorbike scooter rider', '🏍️'],
        ['Bicycle', 'bike cycling', '🚲'],
        ['Sailboat', 'yacht sailing boat', '⛵'],
        ['Vintage car', 'automobile beetle classic', '🚘'],
        ['Race car', 'formula racing kart top view', '🏎️'],
        ['Airplane', 'plane flight travel', '✈️'],
        ['Fish', 'sea animal', '🐟'],
        ['Squirrel', 'chipmunk animal', '🐿️'],
        ['Horse', 'animal equine', '🐴'],
        ['Pig', 'hog animal farm', '🐷'],
        ['Dolphin', 'sea animal', '🐬'],
        ['Spider', 'bug arachnid', '🕷️'],
        ['Cat', 'kitten pet', '🐱'],
        ['Dog', 'puppy pet', '🐶'],
        ['Check mark', 'tick done ok yes', '✔️'],
        ['Cross', 'x no cancel wrong', '❌'],
        ['Smile', 'happy face smiley', '🙂'],
        ['Frown', 'sad face', '☹'],
        ['Neutral face', 'meh straight mouth', '😐'],
        ['Thumbs up', 'like ok good', '👍'],
        ['Thumbs down', 'dislike no bad', '👎'],
        ['Heart', 'love valentine', '❤'],
        ['Flower', 'blossom rose', '🌸'],
        ['Trophy', 'cup winner award prize', '🏆'],
        ['Eighth note', 'music quaver song', '🎵'],
        ['Beamed notes', 'music song notes', '🎶'],
        ['Hammer and wrench', 'tools DIY repair workshop', '🔧'],
        ['Megaphone', 'announcement loudspeaker', '📣'],
        ['Camera', 'photo photography', '📷'],
        ['Clapperboard', 'movie film cinema', '🎬'],
        ['Movie camera', 'film cinema video', '🎥'],
        ['Nail', 'fastener hardware tack', '📌'],
        ['Bolt', 'screw fastener hardware', '🔩'],
        ['Hex nut', 'nut bolt hardware', '⬡'],
        ['Drill bit', 'drill tool', '🪛'],
        ['Screw', 'fastener hardware wood screw', '🔩'],
      ]},
    ],
    accented: {
      image: 'img/symbols/accented.png',
      howto: [
        'Press [Accent], then press a letter. Or press and hold the letter key.',
        'The accent variants for that letter are shown. The guide’s example for a is à á â ã ä, “and so on through all the variations available.”',
        'Use the navigation keys to highlight the one you want and press [OK].',
      ],
      table: { a: 'à á â ã ä …' },
    },
  },

  frames: {
    howto: [
      'Press [Box] (the underline/boxes key) until the style you want is shown on the LCD.',
      'Keep pressing to cycle through the five styles and back to none.',
    ],
    notes: [
      'Five styles are printed in the guide (page 8): underline, rounded box, square box, notched banner, pointed box.',
      'A label can be underlined or enclosed in a box, but not both.',
      'On a two-line label, underline applies to each line; a box wraps both lines in one frame.',
      'Underline does not print on a vertical label.',
    ],
    items: [
      ['off', 'No box', 'none off plain remove'],
      [1, 'Underline', 'underline line under text'],
      [2, 'Rounded box', 'rectangle rounded border'],
      [3, 'Square box', 'rectangle square border'],
      [4, 'Notched banner', 'zigzag ends ticket ribbon'],
      [5, 'Pointed box', 'hexagon arrow ends chevron'],
    ],
  },

  templates: {
    notes: [
      'The LabelManager 160 has no template library. Page 9 of the user guide is clip art and symbols only.',
    ],
    textHowto: [
      'This model does not have text templates.',
    ],
    patternHowto: [
      'This model does not have pattern templates.',
    ],
    text: [],
    pattern: [],
  },

  howto: [
    { id: 'first-label', title: 'Print your first label', kw: 'first print cut peel backing start',
      steps: ['Press [Power] to turn on the label maker.', 'The first time, select the language and press [OK], then select the cassette width and press [OK].', 'Type the text.', 'Press [Print].', 'Press the cutter button.', 'Peel the split backing: pinch the label lengthwise toward the printed side so the backing separates, then peel.'],
      notes: ['Visit www.dymo.com/register to register the serial number (inside the back cover).'] },
    { id: 'two-lines', title: 'Two-line labels', kw: 'two lines second line return enter 1/4 6 mm',
      steps: ['Type line 1.', 'Press [Return]. A return mark appears on the LCD (it is not printed).', 'Type line 2. Press [Print].'],
      notes: ['Maximum two lines. Only one line will print on 6 mm (1/4") tape. {Too many lines!} if you try more.'] },
    { id: 'vertical', title: 'Vertical labels', kw: 'vertical rotate sideways',
      steps: ['Press [Vertical].', 'Type the text.', 'Press [Print].'],
      notes: ['On two-line vertical labels, line 2 prints after line 1. Underline does not print on a vertical label.'] },
    { id: 'size', title: 'Change the font size', kw: 'size point 8 10 12 16 20 24 tape width',
      steps: ['Press [Size] (the AA key) until the size you want is shown.'],
      notes: ['6 mm tape: 8, 10, 12 pt. 9 mm: 8, 10, 12, 16, 20 pt. 12 mm: 8, 10, 12, 16, 20, 24 pt. Size applies to the whole label.'] },
    { id: 'style', title: 'Bold and italic', kw: 'bold italic style combine',
      steps: ['Press [B] to add or remove bold.', 'Press [I] to add or remove italic.'],
      notes: ['The two can be combined. They apply to letters and symbols, not to clip art. The LCD B / I indicators light when a style is on.'] },
    { id: 'box', title: 'Box and underline styles', kw: 'box underline frame border rounded square banner pointed',
      steps: ['Press [Box] until the style is shown on the LCD.'],
      notes: ['Five styles (see Frames). Underline or box, not both.'] },
    { id: 'clipart', title: 'Insert clip art', kw: 'clip art picture icon insert',
      steps: ['Press [Menu].', '[▲] / [▼] to {Clip Art} → [OK].', 'Navigate to the image → [OK].'],
      notes: ['105 images, printed on page 9. Positions in this app match that table, left to right, top to bottom.'] },
    { id: 'symbol', title: 'Insert a symbol', kw: 'symbol punctuation greek math insert',
      steps: ['Press [Menu].', '[▲] / [▼] to {Symbols} → [OK].', 'Navigate to the symbol → [OK].', 'Punctuation only: press [.,#] instead of [Menu].'],
      notes: ['123 symbols on page 9 (two grey cells on the sheet are empty and are not in the set).'] },
    { id: 'accents', title: 'Accented characters (à á â ã ä …)', kw: 'accent international latin spanish french german',
      steps: ['Press [Accent] then the letter, or press and hold the letter.', 'Navigate to the variant → [OK].'],
      notes: ['The guide only prints the a-series example (à á â ã ä and so on). Other letters have their own variants on the device.'] },
    { id: 'caps', title: 'Upper and lower case', kw: 'caps uppercase lowercase capital',
      steps: ['Press [Caps] to toggle. Default is Caps on.', 'The LCD uppercase or lowercase indicator shows the current mode.'] },
    { id: 'menu-settings', title: 'Language and label width', kw: 'language settings width cassette menu first time',
      steps: ['Press [Menu] until the Settings tab is selected.', 'Choose language or label width, then [OK].'],
      notes: ['You are asked for language and width the first time you power on, and again whenever you change the cassette.'] },
    { id: 'cassette', title: 'Insert or change the D1 cassette', kw: 'tape cassette D1 install replace label guides ribbon',
      steps: ['Lift the label cassette cover.', 'Make sure the label and ribbon are taut across the mouth of the cassette and the label passes between the label guides. Turn the ribbon rewind spool clockwise if needed.', 'Insert the cassette until it clicks. Close the cover.', 'Select the new label width when prompted.'],
      notes: ['The cutter blade is extremely sharp. Do not press the cutter button while changing cassettes. Use DYMO D1 cassettes only.'] },
    { id: 'batteries', title: 'Batteries and optional adapter', kw: 'battery AAA adapter DSA-18PFM-09 power 9 volt',
      steps: ['Press the thumb latch on the back to open the battery cover.', 'Insert six AAA alkaline cells following the + / − markings. Replace the cover.', 'Optional adapter: plug DSA-18PFM-09 Fc 090200 into the connector on the top, then into a wall outlet. The adapter disconnects the batteries as a power source.'],
      notes: ['Do not mix old and new cells, or alkaline with rechargeable. Remove the batteries if the maker will sit unused for a long time. Text is lost if batteries come out and the adapter is unplugged.'] },
    { id: 'clean', title: 'Clean the cutter and print head', kw: 'clean cutter blade print head alcohol cotton',
      steps: ['Remove the cassette.', 'Cutter: press and hold the cutter button to expose the blade. Wipe both sides with a cotton ball and alcohol.', 'Print head: take the cleaning tool from inside the cassette cover (or contact DYMO if it is missing) and wipe the padded side gently across the head.'],
      notes: ['Clean the cutter each time you replace the cassette. The blade is extremely sharp.'] },
    { id: 'peel', title: 'Peel the split backing', kw: 'peel backing split adhesive stick',
      steps: ['Find the split on the backing.', 'Pinch the label lengthwise, folding toward the printed side, so the backing separates.', 'Peel the backing away.'] },
    { id: 'power', title: 'Auto power-off and memory', kw: 'auto off two minutes memory backup batteries adapter',
      steps: ['The maker turns off after two idle minutes.', 'Text and formatting come back when you turn it on, as long as batteries or the adapter still supply power.'],
      notes: ['If batteries are removed and the adapter is disconnected, the current label is lost.'] },
  ],

  errors: [
    ['Printing...', 'The label is printing.', 'No action. The message disappears when printing finishes.'],
    ['Too many characters!', 'The text buffer is full (the guide does not state a character count).', 'Delete some characters. Additional characters cannot be added.'],
    ['Too many lines!', 'More lines than this tape width allows.', 'Delete a line, or insert a wider cassette. 6 mm (1/4") = one line; 9 mm and 12 mm = two lines max.'],
    ['Battery low', 'Batteries are weak. The LCD may also show a battery icon.', 'Replace all six AAA cells, or connect the optional 9 V adapter.'],
    ['Insert cassette!', 'No label cassette is inserted.', 'Insert a DYMO D1 cassette and select its width when prompted.'],
    ['Label jam!', 'The motor stalled because of a jammed label.', 'Remove the jam and replace the cassette. Clean the cutter blade.'],
  ],
  problems: [
    ['No display', 'Make sure the label maker is on. Replace the batteries or connect the optional adapter.'],
    ['Poor print quality', 'Replace batteries or use the adapter. Check the cassette is seated. Clean the print head. Try a new cassette.'],
    ['Poor cutter performance', 'Clean the cutter blade with alcohol. See Caring for Your Label Maker in the user guide.'],
    ['How do I remove the backing from the label?', 'DYMO labels have a split back. Pinch lengthwise toward the printed side so the backing separates, then peel.'],
  ],
  tips: [
    'Press [.,#] when you only need punctuation. It skips the Clip Art menu.',
    'Hold a letter to reach à á â ã ä … without the [Accent] key.',
    'Bold and italic stack: press both [B] and [I] for bold italic.',
    'On 6 mm (1/4") tape you only get one line and sizes 8–12 pt. Switch to 12 mm for 24 pt and two lines.',
    'The ~two-minute auto-off keeps the current label if batteries (or the adapter) stay connected.',
    'Clean the cutter blade every time you change the cassette. That is the guide’s maintenance step, not optional.',
  ],
};
