// Brother P-touch PT-D210 — reference data for Labelarium.
// Source: official User's Guide D0123W001 v02 (insertion sheet) + Brother-USA product specs.
// Notation in steps: [Key] = a key on the device, {Text} = what the LCD shows, → = then.
// Symbol items: [name, keywords, unicode approximation]. Position (1-based) = order in the category on the device.
//
// Catalog notes / gaps vs the insertion sheet:
// - Official count is 98 frames + underline; sheet numbers designs 01–99 with Off separate. We ship Off + 1–99
//   (1 = Underline). Brother markets “98 frames”; underline is also listed separately on brochures.
// - Official count is 617 symbols; Basic categories use chars lists (no per-glyph PNGs). Pictograph items are
//   named from the sheet artwork; category overview PNGs + as many per-item crops as extracted are under img/symbols/.
//   Missing per-item PNGs are OK (broken <img>) — names were not invented beyond what the sheet shows.
// - Font/size/width/style/align sample PNGs: same 14 font names as PT-D220, so matching files were copied from
//   devices/brother-pt-d220/img/fonts/ (D210 has 10 styles — no I+Solid). Sheet overviews also kept under img/fonts/.
// - Keyboard cropped from D210 getting-started page (LCD Display & Keyboard).
// - Frame/template per-item PNGs were cropped from the D210 insertion sheet; some cells may be misaligned —
//   see img/frames/_overview.png and img/templates/_*-overview.png for the full official grids.
export default {
  id: 'brother-pt-d210',
  brand: 'Brother',
  model: 'PT-D210',
  name: 'P-touch PT-D210',
  tagline: 'Home & Office Everyday Label Maker',
  links: [
    ['Official support, FAQs & manual', 'https://support.brother.com/g/b/producttop.aspx?c=us&lang=en&prod=d210eus'],
  ],
  specs: [
    ['Tape', 'Brother TZe laminated tape, 3.5 / 6 / 9 / 12 mm (0.13" / 0.23" / 0.35" / 0.47")'],
    ['Print', '180 dpi thermal transfer, up to 20 mm/s, 2 lines max (9 & 12 mm tape)'],
    ['Text', 'Up to 80 characters per label (50 in templates), 15-character one-row LCD'],
    ['Fonts', '14 fonts · 3 sizes · 3 widths · 10 styles · 4 alignments'],
    ['Decorations', '98 frames (+ underline / Off) · 27 templates (17 text + 10 pattern) · 617 symbols in 27 categories'],
    ['Memory', '30 saved labels (80 chars each, 2400 total). History keeps the last 7 symbols'],
    ['Power', '6 × AAA alkaline (LR03) or Ni-MH (HR03), or AC adapter AD-24ES / AD-24ESA (optional)'],
    ['Auto power off', 'After 5 minutes idle. Text & settings survive 3 minutes without power'],
    ['Size / weight', '157 × 150 × 68 mm, 490 g without batteries'],
    ['Cutter', 'Manual lever; replacement cutter unit TC-4'],
  ],
  tapes: [
    { mm: 3.5, in: '0.13"', lines: 1, note: 'Single line only. Frames may not print (No Frame OK?).' },
    { mm: 6, in: '0.23"', lines: 1, note: 'Single line only.' },
    { mm: 9, in: '0.35"', lines: 2, note: 'Two lines OK. Some frames and all templates need 12 mm.' },
    { mm: 12, in: '0.47"', lines: 2, note: 'Everything works: 2 lines, all frames, templates.' },
  ],
  keyboard: {
    image: 'img/keyboard.png',
    legend: [
      [1, 'Size indicator', 'Shows the current font size (Large / Medium / Small).'],
      [2, 'Cursor', 'Text insertion point. ◀ / ▶ move it; Shift+◀ / Shift+▶ jump to start / end.'],
      [3, 'Underline / Frame indicator', 'Lit when a frame or underline is set.'],
      [4, 'Width indicator', 'Normal, ×2 or ×½ character width.'],
      [5, 'Style indicator', 'Bold, outline, shadow, italic, vertical …'],
      [6, 'Caps indicator', 'Lit when Caps lock is on.'],
      [7, 'Label length', 'Shows the label length; a padlock means a fixed length is set.'],
      [8, 'OK key', 'Confirm a menu choice. "Accepted" shows for one second.'],
      [9, 'Cursor ▶', 'Move right / next option. With Shift: jump to end of text.'],
      [10, 'Cursor ◀', 'Move left / previous option. With Shift: jump to start of text.'],
      [11, 'Esc', 'Cancel any operation, leave preview, back out of menus.'],
      [12, 'Power', 'On / off. Part of the reset combo (Shift + R + Power).'],
      [13, 'Menu', 'File, Tab, Unit, LCD Contrast, Clear, Language. Menu + number = shortcut.'],
      [14, 'Label', 'Label Length, Tab Length, Margin.'],
      [15, 'Font', 'Font, Size, Width, Style, Alignment.'],
      [16, 'Character keys', 'Letters, numbers and punctuation. Shift + digit gives the top-right symbol.'],
      [17, 'Tab', 'Insert a tab (shows as ▯ on the LCD).'],
      [18, 'Caps', 'Toggle upper case.'],
      [19, 'Shift', 'Upper case for one letter, symbols on digit keys, and combos (Shift+Print, Shift+BS, Shift+Feed).'],
      [20, 'File', 'Save, Print or Open one of 30 stored labels.'],
      [21, 'Tape cutter lever', 'Push after "Please Cut". Never while "Please Wait" is shown.'],
      [22, 'Print (Print Options)', 'Print with 1–9 copies. Shift + Print = Numbering / Mirror.'],
      [23, 'Preview (Feed)', 'Show the label image. Shift + Preview feeds 25 mm of tape.'],
      [24, 'Frame', 'Pick a frame by ◀ / ▶ or by typing its number.'],
      [25, 'Symbol', 'History / Basic / Pictograph symbol categories.'],
      [26, 'Template Library', 'Text label and Pattern label templates (12 mm tape only).'],
      [27, 'Backspace (Clear)', 'Delete one character. Shift + BS clears text and/or format.'],
      [28, 'Enter', 'Start the second line (9 or 12 mm tape). Also confirms in some menus.'],
      [29, 'Accent', 'Cycle through accented versions of the letter you typed.'],
      [30, 'Space', 'Space. Inside a setting: reset that setting to its default.'],
    ],
  },
  shortcuts: [
    { keys: '[Menu] → [1]', action: 'File menu', kw: 'save open stored labels memory' },
    { keys: '[Menu] → [2]', action: 'Insert a Tab', kw: 'tab' },
    { keys: '[Menu] → [3]', action: 'Unit (inch / mm)', kw: 'unit inch mm measurement' },
    { keys: '[Menu] → [4]', action: 'LCD Contrast (−2 … +2)', kw: 'contrast brightness screen display' },
    { keys: '[Menu] → [BS]', action: 'Clear (Text & Format, or Text Only)', kw: 'clear delete all erase reset text' },
    { keys: '[Menu] → [Space]', action: 'Language', kw: 'language english spanish french german' },
    { keys: '[Shift] + [BS]', action: 'Clear text and/or format', kw: 'clear delete all erase' },
    { keys: '[Shift] + [Preview]', action: 'Feed about 25 mm (1") of blank tape', kw: 'feed tape blank advance' },
    { keys: '[Shift] + [Print]', action: 'Print Options: Numbering or Mirror', kw: 'numbering serial mirror print options' },
    { keys: '[Shift] + [▶]', action: 'Jump cursor to the end of the text', kw: 'cursor end jump navigate' },
    { keys: '[Shift] + [◀]', action: 'Jump cursor to the start of the text', kw: 'cursor start beginning home jump' },
    { keys: '[Frame] → number keys → [OK]', action: 'Pick a frame directly by its number', kw: 'frame number direct' },
    { keys: '[Symbol] → {Basic} or {Pictograph} → [OK] → letter key', action: 'Jump straight to a symbol category (see each category for its key)', kw: 'symbol category jump letter' },
    { keys: '[Print] → digit key', action: 'Set number of copies (1–9) by typing it', kw: 'copies number print' },
    { keys: '[Space] (inside any setting)', action: 'Return that setting to its default (e.g. Label Length → Auto)', kw: 'default reset setting auto' },
    { keys: '[Esc]', action: 'Cancel anything, exit preview or templates', kw: 'cancel escape exit back' },
    { keys: '[Shift] + digit', action: 'Type the symbol printed above the digit: ! @ # $ % \' & * ( ) and " on the − key', kw: 'punctuation exclamation at hash dollar percent ampersand asterisk parentheses quote' },
    { keys: '[Shift] + [,] / [.] / [;]', action: 'Type ? / and :', kw: 'question mark slash colon' },
    { keys: 'letter → [Accent] → [Accent]…', action: 'Cycle accented letters (é è ê ë …), [OK] to insert', kw: 'accent accented umlaut tilde cedilla' },
    { keys: '[Enter]', action: 'New line (2-line label on 9 / 12 mm tape)', kw: 'enter newline second line two lines' },
    { keys: '[Esc] / [OK] / [Enter] in preview', action: 'Leave the preview', kw: 'preview exit' },
    { keys: '[Power] off → hold [Shift] + [R] → press [Power]', action: 'Factory reset (clears everything; release Power first, then Shift and R)', kw: 'reset factory initialize frozen locked up' },
  ],
  fonts: [
    ['Helsinki', 'helsinki.png', 'Clean sans-serif. The default, and the fallback when text must shrink.', '"Helvetica Neue", Helvetica, Arial, sans-serif', 400, 'normal'],
    ['Brussels', 'brussels.png', 'Classic serif (Times-like).', 'Georgia, "Times New Roman", serif', 400, 'normal'],
    ['US', 'us.png', 'Light serif, typewriter feel.', '"Times New Roman", Times, serif', 300, 'normal'],
    ['Florida', 'florida.png', 'Heavy rounded sans.', '"Arial Rounded MT Bold", "Helvetica Neue", Arial, sans-serif', 800, 'normal'],
    ['Belgium', 'belgium.png', 'Squared, technical bold sans.', '"Avenir Next Condensed", "Arial Narrow", sans-serif', 700, 'normal'],
    ['San Diego', 'san-diego.png', 'High-contrast serif (Bodoni-like).', '"Bodoni 72", Didot, Georgia, serif', 400, 'normal'],
    ['Los Angeles', 'los-angeles.png', 'Very heavy display sans.', 'Impact, "Arial Black", sans-serif', 900, 'normal'],
    ['Calgary', 'calgary.png', 'Elegant script / handwriting.', '"Snell Roundhand", "Brush Script MT", cursive', 400, 'italic'],
    ['Atlanta', 'atlanta.png', 'Humanist sans (Optima-like).', 'Optima, Futura, "Gill Sans", sans-serif', 500, 'normal'],
    ['Adams', 'adams.png', 'Narrow bold sans.', '"Arial Narrow", "Helvetica Neue", sans-serif', 700, 'normal'],
    ['Brunei', 'brunei.png', 'Bold italic display.', '"Arial Black", Impact, sans-serif', 900, 'italic'],
    ['Istanbul', 'istanbul.png', 'Bold grotesque sans.', '"Helvetica Neue", Arial, sans-serif', 900, 'normal'],
    ['Sofia', 'sofia.png', 'Extra-bold condensed.', '"Futura Condensed ExtraBold", "Arial Narrow", sans-serif', 900, 'normal'],
    ['Germany', 'germany.png', 'Blackletter / Old English.', '"Old English Text MT", UnifrakturMaguntia, fantasy', 400, 'normal'],
  ],
  sizes: [['Large', 'size-large.png', 1], ['Medium', 'size-medium.png', .66], ['Small', 'size-small.png', .42]],
  widths: [['Normal', 'width-normal.png', 1], ['× 2', 'width-x2.png', 2], ['× 1/2', 'width-half.png', .5]],
  styles: [
    ['Normal', 'style-normal.png'], ['Bold', 'style-bold.png'], ['Outline', 'style-outline.png'], ['Shadow', 'style-shadow.png'], ['Solid', 'style-solid.png'],
    ['Italic', 'style-italic.png'], ['I+Bold', 'style-italic-bold.png'], ['I+Outline', 'style-italic-outline.png'], ['I+Shadow', 'style-italic-shadow.png'],
    ['Vertical', 'style-vertical.png'],
  ],
  alignments: [['Left', 'align-left.png'], ['Center', 'align-center.png'], ['Right', 'align-right.png'], ['Justify', 'align-justify.png']],
  fontNote: 'The printed size depends on tape width, number of characters and lines. When characters hit the minimum size the device silently switches to a small Helsinki-based font so the label still fits. PT-D210 has 10 styles (no I+Solid).',

  symbols: {
    howto: [
      'Press [Symbol].',
      'Use [◀] / [▶] to choose {History}, {Basic} or {Pictograph}, then [OK]. (History = your last 7 symbols; no categories inside it.)',
      'Use [◀] / [▶] to choose the category, then [OK] — or press the category\'s shortcut key to jump straight to it.',
      'Use [◀] / [▶] to move to the symbol (positions below count from the left), then [OK].',
      'To cancel at any point press [Esc].',
    ],
    categories: [
      { id: 'punctuation', name: 'Punctuation', group: 'Basic', key: 'Space', chars: ". , : ; \" ' • ? ! ¿ ¡ - & ~ _ \ / * @ #", kw: 'period comma colon semicolon quote apostrophe bullet question exclamation inverted hyphen dash ampersand tilde underscore backslash slash asterisk at hash pound' },
      { id: 'mathematics', name: 'Mathematics', group: 'Basic', key: 'A', chars: '+ − × ÷ ± = ≥ ≤ ≠ ∴', kw: 'plus minus times multiply divide plus-minus equals greater less not equal therefore math' },
      { id: 'brackets', name: 'Brackets', group: 'Basic', key: 'B', chars: '( ) [ ] { } < > « » 【 】', kw: 'parentheses parens square curly angle guillemets corner brackets' },
      { id: 'arrows', name: 'Arrows', group: 'Basic', key: 'C', chars: '→ ← ↑ ↓ ↔ ⇄ ↕ ↗ ↘ ↖ ↙', kw: 'right left up down both ways direction pointer diagonal' },
      { id: 'unit', name: 'Unit', group: 'Basic', key: 'D', chars: '% $ ¢ € £ ¥ ฿ ° ft. in. m² m³ cc ℓ oz. lb. °F °C', kw: 'percent dollar cent euro pound yen baht degree feet inch square cubic metre liter ounce pound fahrenheit celsius currency' },
      { id: 'greek', name: 'Greek Letter', group: 'Basic', key: 'E', chars: 'α β γ δ μ Ω σ Σ φ π', kw: 'alpha beta gamma delta mu micro ohm omega sigma phi pi greek' },
      { id: 'number1', name: 'Number 1', group: 'Basic', key: 'F', chars: '² ³ ¼ ½ ¾ Ⅰ Ⅱ Ⅲ Ⅳ Ⅴ Ⅵ Ⅶ Ⅷ Ⅸ Ⅹ', kw: 'superscript squared cubed fraction quarter half three-quarters roman numerals' },
      { id: 'number2', name: 'Number 2', group: 'Basic', key: 'G', chars: '① ② ③ ④ ⑤ ⑥ ⑦ ⑧ ⑨ ⑩ ⑪ ⑫ ⑬ ⑭ ⑮ ⑯ ⑰ ⑱ ⑲ ⑳', charsNote: 'See insertion sheet for the full set.', kw: 'circled numbers circle digits numbered list' },
      { id: 'number3', name: 'Number 3', group: 'Basic', key: 'H', chars: '1 2 3 4 5 6 7 8 9 10 … 20', charsNote: 'See insertion sheet for the full set.', kw: 'boxed squared numbers square digits numbered' },
      { id: 'shape', name: 'Shape', group: 'Basic', key: 'I', chars: '● ○ ■ □ ★ ☆ ♠ ♤ ♥ ♡ ◆ ◇ ♣ ♧ ▲ △ ▼ ▽', kw: 'circle square star spade heart diamond club triangle filled hollow bullet shapes cards' },

      { id: 'fun', name: 'Fun', group: 'Pictograph', key: 'Space', kw: 'music decoration ornaments emoji party', items: [
        ['Two hearts', 'love hearts', '💕'],
        ['Beamed notes', 'music song', '🎶'],
        ['Shooting star', 'star meteor wish', '🌠'],
        ['Rainbow', 'weather pride', '🌈'],
        ['Planet with ring', 'saturn space', '🪐'],
        ['Crown', 'king queen royal', '👑'],
        ['Paw print', 'pet dog cat', '🐾'],
        ['Star badge', 'star circle award', '⭐'],
        ['Thumbs up', 'like ok good', '👍'],
        ['Droplets', 'water sweat drops', '💦'],
        ['Eighth note', 'music quaver', '🎵'],
        ['Sixteenth notes', 'music beamed', '🎵'],
        ['Treble clef', 'music', '🎼'],
        ['Grinning face', 'smile happy lol', '😃'],
        ['Happy face', 'smile', '😊'],
        ['Sad face', 'frown unhappy', '😢'],
        ['Neutral face', 'expressionless', '😐'],
        ['Skeptical face', 'unsure', '😒'],
        ['Kissing face', 'kiss love', '😘'],
        ['Round face', 'emoji', '🙂']
      ]},
      { id: 'family', name: 'Family', group: 'Pictograph', key: 'A', kw: 'people faces baby parents relatives', items: [
        ['House', 'home family', '🏠'],
        ['Man', 'father dad', '👨'],
        ['Woman', 'mother mom', '👩'],
        ['Boy', 'son child', '👦'],
        ['Girl', 'daughter child', '👧'],
        ['Baby', 'infant', '👶'],
        ['Wedding ring', 'marriage couple', '💍'],
        ['Grandfather', 'old man grandpa', '👴'],
        ['Grandmother', 'old woman grandma', '👵'],
        ['Stroller', 'pram buggy', '🍼'],
        ['Pacifier', 'dummy soother', '🍼'],
        ['Boy with cap', 'child', '👦']
      ]},
      { id: 'clothing', name: 'Clothing', group: 'Pictograph', key: 'B', kw: 'clothes fashion laundry wardrobe', items: [
        ['T-shirt', 'shirt top', '👕'],
        ['Trousers', 'pants jeans', '👖'],
        ['Dress', 'gown', '👗'],
        ['Shoe', 'footwear', '👟'],
        ['High heel', 'heels shoe', '👠'],
        ['Hat', 'cap', '👒'],
        ['Hanger', 'closet wardrobe', '🪝'],
        ['Jacket', 'coat', '🧥'],
        ['Sock', 'socks', '🧦'],
        ['Handbag', 'purse bag', '👜'],
        ['Glasses', 'spectacles', '👓'],
        ['Tie', 'necktie formal', '👔']
      ]},
      { id: 'vehicle', name: 'Vehicle', group: 'Pictograph', key: 'C', kw: 'transport travel car', items: [
        ['Bicycle', 'bike cycling', '🚲'],
        ['Car', 'automobile sedan', '🚗'],
        ['Minivan', 'van', '🚐'],
        ['Truck', 'lorry delivery', '🚚'],
        ['Bus', 'coach transit', '🚌'],
        ['Motorcycle', 'motorbike', '🏍️'],
        ['Scooter', 'moped', '🛵'],
        ['Sailboat', 'yacht sailing', '⛵'],
        ['Speedboat', 'boat', '🚤'],
        ['Airplane', 'plane flight', '✈️'],
        ['Helicopter', 'chopper', '🚁'],
        ['Train', 'rail subway', '🚆'],
        ['Tram', 'streetcar trolley', '🚊']
      ]},
      { id: 'sports', name: 'Sports', group: 'Pictograph', key: 'D', kw: 'sport games fitness', items: [
        ['Tennis', 'racket ball', '🎾'],
        ['Soccer ball', 'football', '⚽'],
        ['American football', 'rugby', '🏈'],
        ['Baseball', 'ball bat', '⚾'],
        ['Golf', 'club ball hole', '⛳'],
        ['Swimmer', 'swim pool', '🏊'],
        ['Skier', 'skiing snow', '⛷️'],
        ['Basketball', 'ball', '🏀'],
        ['Volleyball', 'ball', '🏐'],
        ['Bowling', 'pins ball', '🎳'],
        ['Trophy', 'cup winner award', '🏆'],
        ['Medal', 'award prize', '🏅']
      ]},
      { id: 'animal', name: 'Animal', group: 'Pictograph', key: 'E', kw: 'animals pets zoo', items: [
        ['Cat', 'kitten pet', '🐱'],
        ['Dog', 'puppy pet', '🐶'],
        ['Rabbit', 'bunny', '🐰'],
        ['Bird', 'tweet', '🐦'],
        ['Fish', 'aquarium', '🐟'],
        ['Paw print', 'pet print', '🐾'],
        ['Butterfly', 'insect', '🦋'],
        ['Horse', 'pony', '🐴'],
        ['Cow', 'cattle farm', '🐮'],
        ['Pig', 'hog', '🐷'],
        ['Mouse', 'rat', '🐭'],
        ['Frog', 'toad', '🐸']
      ]},
      { id: 'astrology', name: 'Astrology', group: 'Pictograph', key: 'F', kw: 'zodiac horoscope star sign', items: [
        ['Aries', 'ram zodiac', '♈'],
        ['Taurus', 'bull zodiac', '♉'],
        ['Gemini', 'twins zodiac', '♊'],
        ['Cancer', 'crab zodiac', '♋'],
        ['Leo', 'lion zodiac', '♌'],
        ['Virgo', 'maiden zodiac', '♍'],
        ['Libra', 'scales zodiac', '♎'],
        ['Scorpio', 'scorpion zodiac', '♏'],
        ['Sagittarius', 'archer zodiac', '♐'],
        ['Capricorn', 'goat zodiac', '♑'],
        ['Aquarius', 'water zodiac', '♒'],
        ['Pisces', 'fish zodiac', '♓']
      ]},
      { id: 'event-season', name: 'Event/Season', group: 'Pictograph', key: 'G', kw: 'celebration holiday party christmas season weather', items: [
        ['Party popper', 'confetti celebration', '🎉'],
        ['Birthday cake', 'candles party', '🎂'],
        ['Gift box', 'present', '🎁'],
        ['Christmas tree', 'xmas', '🎄'],
        ['Snowflake', 'snow winter', '❄️'],
        ['Snowman', 'winter', '⛄'],
        ['Jack-o-lantern', 'halloween pumpkin', '🎃'],
        ['Umbrella', 'rain weather', '☔'],
        ['Sun', 'sunny summer', '☀️'],
        ['Flower blossom', 'spring sakura', '🌸'],
        ['Maple leaf', 'autumn fall', '🍁'],
        ['Fireworks', 'new year', '🎆'],
        ['Bell', 'christmas wedding', '🔔'],
        ['Heart with ribbon', 'valentine', '💝']
      ]},
      { id: 'food', name: 'Food', group: 'Pictograph', key: 'H', kw: 'eat drink fruit meal', items: [
        ['Apple', 'fruit', '🍎'],
        ['Grapes', 'fruit wine', '🍇'],
        ['Cherries', 'fruit', '🍒'],
        ['Banana', 'fruit', '🍌'],
        ['Hamburger', 'burger', '🍔'],
        ['Coffee cup', 'hot drink tea', '☕'],
        ['Beer mug', 'ale pint', '🍺'],
        ['Fork and knife', 'dining cutlery', '🍴'],
        ['Ice cream', 'dessert', '🍦'],
        ['Bread', 'loaf bakery', '🍞'],
        ['Pizza', 'slice', '🍕'],
        ['Cake slice', 'dessert', '🍰']
      ]},
      { id: 'kitchen', name: 'Kitchen', group: 'Pictograph', key: 'I', kw: 'cooking utensils pantry', items: [
        ['Frying pan', 'skillet cook', '🍳'],
        ['Pot', 'saucepan', '🍲'],
        ['Teapot', 'kettle tea', '🫖'],
        ['Toaster', 'breakfast', '🍞'],
        ['Refrigerator', 'fridge', '🧊'],
        ['Chef hat', 'cook', '👨‍🍳'],
        ['Ladle', 'soup spoon', '🥄'],
        ['Kitchen knife', 'chef cut', '🔪'],
        ['Mixing bowl', 'baking', '🥣'],
        ['Salt shaker', 'seasoning', '🧂'],
        ['Bottle', 'oil sauce', '🍾'],
        ['Plate', 'dishes', '🍽️']
      ]},
      { id: 'garden', name: 'Garden', group: 'Pictograph', key: 'J', kw: 'plants flowers outdoor yard', items: [
        ['Flower', 'blossom', '🌸'],
        ['Tulip', 'spring flower', '🌷'],
        ['Sunflower', 'flower', '🌻'],
        ['Clover', 'luck shamrock', '🍀'],
        ['Potted plant', 'pot', '🪴'],
        ['Seedling', 'sprout grow', '🌱'],
        ['Palm tree', 'tropical', '🌴'],
        ['Pine tree', 'evergreen', '🌲'],
        ['Watering can', 'water plants', '🚿'],
        ['Trowel', 'spade dig', '🪏'],
        ['Rake', 'leaves lawn', '🧹'],
        ['Lawn mower', 'grass', '🚜'],
        ['Butterfly', 'insect garden', '🦋'],
        ['Ladybug', 'insect', '🐞'],
        ['Bee', 'honey', '🐝']
      ]},
      { id: 'diy', name: 'DIY', group: 'Pictograph', key: 'K', kw: 'tools crafts hobby workshop', items: [
        ['Handsaw', 'saw wood', '🪚'],
        ['Hammer', 'nail tool', '🔨'],
        ['Drill', 'power tool', '🪛'],
        ['Paintbrush', 'paint decorate', '🖌️'],
        ['Paint bucket', 'paint can', '🪣'],
        ['Axe', 'hatchet', '🪓'],
        ['Toolbox', 'tools kit', '🧰'],
        ['Screw', 'fastener', '🔩'],
        ['Screwdriver', 'tool', '🪛'],
        ['Wrench', 'spanner', '🔧'],
        ['Ladder', 'stepladder', '🪜'],
        ['Tape measure', 'measure', '📏']
      ]},
      { id: 'school', name: 'School', group: 'Pictograph', key: 'L', kw: 'education study kids', items: [
        ['School building', 'school', '🏫'],
        ['Pencil', 'write draw', '✏️'],
        ['Scissors', 'cut craft', '✂️'],
        ['Open book', 'read textbook', '📖'],
        ['Books', 'stack study', '📚'],
        ['Light bulb', 'idea', '💡'],
        ['Graduation cap', 'graduate diploma', '🎓'],
        ['Alarm clock', 'time wake', '⏰'],
        ['Bell', 'school bell', '🔔'],
        ['Hourglass', 'timer', '⏳'],
        ['Ruler', 'measure geometry', '📐'],
        ['Flask', 'science lab', '⚗️'],
        ['Globe', 'geography world', '🌍'],
        ['Magnifying glass', 'search', '🔍'],
        ['Palette', 'art paint', '🎨'],
        ['Calculator', 'math', '🧮'],
        ['Backpack', 'bag school', '🎒']
      ]},
      { id: 'office', name: 'Office', group: 'Pictograph', key: 'M', kw: 'work business desk', items: [
        ['Check mark', 'tick done ok', '✔️'],
        ['Checked box', 'checkbox', '☑️'],
        ['Folder', 'file', '📁'],
        ['Document', 'page paper', '📄'],
        ['Documents stack', 'papers', '📑'],
        ['Clipboard', 'notes', '📋'],
        ['Calculator', 'math', '🧮'],
        ['Pie chart', 'statistics', '🥧'],
        ['Bar chart', 'graph report', '📊'],
        ['Key', 'access lock', '🔑'],
        ['Padlock', 'secure', '🔒'],
        ['Clock', 'time', '🕒'],
        ['Telephone', 'phone call', '☎️'],
        ['Briefcase', 'bag work', '💼'],
        ['Laptop', 'computer', '💻'],
        ['Envelope', 'mail letter', '✉️'],
        ['Paperclip', 'clip', '📎'],
        ['Push pin', 'thumbtack', '📌']
      ]},
      { id: 'signs', name: 'Signs', group: 'Pictograph', key: 'N', kw: 'safety warning info prohibition', items: [
        ['Prohibited', 'no forbidden banned', '🚫'],
        ['No entry', 'stop bar', '⛔'],
        ['Fire hazard', 'flame flammable', '🔥'],
        ['Warning', 'caution danger alert', '⚠️'],
        ['High voltage', 'lightning electric', '⚡'],
        ['Fragile', 'glass breakable', '🍷'],
        ['This way up', 'arrows package', '⏫'],
        ['Recycle', 'eco recycling', '♻️'],
        ['Parking', 'car park P', '🅿️'],
        ['Emergency exit', 'exit escape', '🚪'],
        ['Men', 'male restroom', '🚹'],
        ['Women', 'female restroom', '🚺'],
        ['Restroom', 'toilet unisex', '🚻'],
        ['Wheelchair', 'accessibility handicap', '♿'],
        ['Stairs', 'steps', '🪜'],
        ['Elevator', 'lift', '🛗'],
        ['No smoking', 'cigarette prohibited', '🚭'],
        ['No phones', 'mobile prohibited', '📵'],
        ['Information', 'info i', 'ℹ️'],
        ['Skull', 'poison toxic danger', '☠️'],
        ['Litter bin', 'trash dispose', '🚮']
      ]},
      { id: 'datacom-av', name: 'Datacom/AV', group: 'Pictograph', key: 'O', kw: 'computer network audio video media', items: [
        ['Monitor', 'screen display', '🖥️'],
        ['Laptop', 'notebook computer', '💻'],
        ['Smartphone', 'phone mobile', '📱'],
        ['Wi-Fi', 'wireless network', '📶'],
        ['Printer', 'print', '🖨️'],
        ['Envelope', 'email mail', '✉️'],
        ['Telephone', 'phone', '☎️'],
        ['Television', 'TV', '📺'],
        ['Projector', 'beamer', '📽️'],
        ['Video camera', 'camcorder', '📹'],
        ['Camera', 'photo', '📷'],
        ['Headphones', 'audio music', '🎧'],
        ['Microphone', 'mic recording', '🎤'],
        ['Speaker', 'sound volume', '🔊'],
        ['CD / DVD', 'disc media', '💿'],
        ['Game controller', 'gaming', '🎮'],
        ['Play', 'media start', '▶️'],
        ['Pause', 'media', '⏸️'],
        ['Fast forward', 'skip', '⏩'],
        ['Rewind', 'back', '⏪'],
        ['Satellite dish', 'signal', '📡'],
        ['Antenna', 'aerial', '📶'],
        ['Chat bubbles', 'message SMS', '💬']
      ]},
      { id: 'electrical', name: 'Electrical', group: 'Pictograph', key: 'P', kw: 'electric power IEC symbols', items: [
        ['Earth ground', 'earth GND', '⏚'],
        ['AC', 'alternating current', '∿'],
        ['DC', 'direct current', '⎓'],
        ['Power / standby', 'power button', '⏻'],
        ['Light bulb', 'lamp', '💡'],
        ['Battery', 'power charge', '🔋'],
        ['Outlet', 'plug socket', '🔌'],
        ['Fuse', 'protection', '⌸'],
        ['Double insulation', 'class II', '回'],
        ['On', 'power on I', 'Ⓘ'],
        ['Off', 'power off O', '⭘'],
        ['Lightning hazard', 'high voltage shock', '⚡'],
        ['Speaker', 'horn audio', '🔈'],
        ['Resistor', 'component', 'Ω']
      ]},
    ],
    accented: {
      image: 'img/symbols/accented.png',
      howto: ['Type the base letter (upper or lower case).', 'Press [Accent]. Press [Accent] again or use [◀] / [▶] to cycle through the variants.', 'Press [OK] to insert. The order of variants depends on the LCD language.'],
      table: { A: 'À Á Â Ä Æ Ã Ą Å Ā Ă', a: 'à á â ä æ ã ą å ā ă', C: 'Ç Č Ć', c: 'ç č ć', D: 'Ď Đ Ð', d: 'ď ð đ', E: 'É È Ê Ë Ę Ě Ė Ē', e: 'é è ê ë ę ě ė ē', G: 'Ģ Ğ', g: 'ģ ğ', I: 'Í Ì Î Ï Į Ī İ', i: 'í ì î ï į ī ı', K: 'Ķ', k: 'ķ', L: 'Ł Ĺ Ļ Ľ', l: 'ł ĺ ļ ľ', N: 'Ñ Ň Ń Ņ', n: 'ñ ň ń ņ', O: 'Ó Ò Ô Ø Ö Õ Œ Ő', o: 'ó ò ô ø ö õ œ ő', R: 'Ř Ŕ Ŗ', r: 'ř ŕ ŗ', S: 'Š Ś Ş Ș ß', s: 'š ś ş ș ß', T: 'Ť Ţ Þ', t: 'ť ţ þ', U: 'Ú Ù Û Ü Ų Ů Ū Ű', u: 'ú ù û ü ų ů ū ű', Y: 'Ý Ÿ', y: 'ý ÿ', Z: 'Ž Ź Ż', z: 'ž ź ż' },
    },
  },

  frames: {
    howto: [
      'Press [Frame].',
      'Use [◀] / [▶] to browse, or simply type the frame number with the digit keys.',
      'Press [OK]. "Accepted" appears and the frame indicator lights on the LCD.',
      'To remove a frame: [Frame] → choose {Off} → [OK].',
    ],
    notes: [
      'Frames with highlighted numbers on the insertion sheet print only on 12 mm (0.47") tape. On narrower tape you get "No Frame OK?" — [OK] prints without the frame, [Esc] cancels.',
      'On 3.5 mm tape frames are not available.',
      'Frames wrap the whole label, both lines included.',
      'Brother lists 98 frames; the sheet numbers designs 01–99 with Off separate (01 = Underline on the sheet).',
    ],
    // [number, name, keywords, 12mm-only]
    items: [
      ['off', 'No frame', 'none off plain remove'],
      [1, 'Underline', 'underline line under text'],
      [2, 'Rounded box', 'rectangle border rounded corners'],
      [3, 'Zigzag / torn ends', 'jagged ribbon banner'],
      [4, 'Pointed ribbon', 'arrow chevron ends tag'],
      [5, 'Corner brackets', 'L corners minimal'],
      [6, 'Dotted corners', 'pixel dots corner'],
      [7, 'Rounded box with corner dots', 'circle corners'],
      [8, 'Scroll flourishes', 'ornament swirl corners'],
      [9, 'Film strip', 'sprocket perforations'],
      [10, 'Diamond side borders', 'geometric diamonds'],
      [11, 'Chevron / arrow ends', 'pointer stripes'],
      [12, 'Geometric corner squares', 'cross-hatch corners'],
      [13, 'Leafy scroll corners', 'floral ornate'],
      [14, 'Luggage / film canister tag', 'ticket tag roll'],
      [15, 'Sticky note with push-pin', 'memo pin notepad'],
      [16, 'Scroll with pen', 'parchment quill pencil'],
      [17, 'Paperclip note', 'clipboard memo'],
      [18, 'Spiral notebook', 'binder rings'],
      [19, 'Stars at ends', 'star ornaments'],
      [20, 'Hearts at ends', 'heart love'],
      [21, 'Sparkles at ends', 'twinkle star'],
      [22, 'Bubbles at ends', 'circles dots'],
      [23, 'Target / bullseye', 'circles concentric'],
      [24, 'Leafy vine corners', 'leaves nature'],
      [25, 'Ornate floral corners', 'filigree lace'],
      [26, 'Flower border sides', 'floral dots'],
      [27, 'Snowflakes', 'snow winter ornate', true],
      [28, 'Floral mandala ends', 'geometric flower', true],
      [29, 'Pencil & eraser', 'stationery school'],
      [30, 'Alarm clock & building', 'school time'],
      [31, 'School & pencil', 'education'],
      [32, 'School & open book', 'reading study'],
      [33, 'Calculator & documents', 'office math'],
      [34, 'Register & papers', 'receipt office'],
      [35, 'Bar chart & pie chart', 'business statistics'],
      [36, 'Pencil & checkbox', 'checklist todo'],
      [37, 'Monitor & envelope', 'computer email'],
      [38, 'Desktop PC & mouse', 'computer IT'],
      [39, 'Recycle & trees', 'eco environment'],
      [40, 'City skyline', 'buildings urban'],
      [41, 'Man & woman', 'people gender'],
      [42, 'Clapperboard & camera', 'movie film'],
      [43, 'Camera & palm trees', 'travel vacation photo'],
      [44, 'Comb & scissors', 'hair salon beauty'],
      [45, 'Globe & trees', 'world nature'],
      [46, 'Info & car', 'information vehicle'],
      [47, 'Info & airplane', 'travel flight'],
      [48, 'Traveler & airplane', 'luggage trip'],
      [49, 'Phone & handset', 'telephone contact'],
      [50, 'Wheelchair & medical cross', 'accessibility health'],
      [51, 'Clipboard & stethoscope', 'medical doctor'],
      [52, 'Birds & sun', 'nature morning'],
      [53, 'Floral cluster', 'flowers ornate', true],
      [54, 'Rain cloud & umbrella', 'weather rain'],
      [55, 'Waves & sailboat', 'sea beach'],
      [56, 'Starburst ends', 'sparkle firework'],
      [57, 'Leaves & tree', 'autumn nature'],
      [58, 'Snowy house & snowman', 'winter christmas'],
      [59, 'Pine trees', 'forest winter'],
      [60, 'Mountain & snowman', 'winter snow'],
      [61, 'Bell & gift', 'christmas present'],
      [62, 'Champagne & music note', 'party celebration'],
      [63, 'Hot air balloons', 'balloon travel'],
      [64, 'Megaphone speech bubble', 'announcement'],
      [65, 'Light bulb & smile', 'idea funny'],
      [66, 'Smile & heart', 'love happy'],
      [67, 'Key & car', 'keys vehicle'],
      [68, 'Wrench & gears', 'tools mechanic'],
      [69, 'Flowers & vine', 'garden floral'],
      [70, 'Plants & watering can', 'gardening'],
      [71, 'Books & binders', 'library study'],
      [72, 'Dog house & dog', 'pet puppy'],
      [73, 'Toys / gift box', 'kids play'],
      [74, 'Cup & teapot', 'coffee tea kitchen'],
      [75, 'Dining / no food', 'restaurant cutlery'],
      [76, 'Phone & bed', 'hotel sleep'],
      [77, 'Yarn & cat', 'knitting kitten craft', true],
      [78, 'Baseball & diamond', 'sports baseball'],
      [79, 'Sun & tulip', 'spring flower'],
      [80, 'Car & checkered flag', 'racing motorsport'],
      [81, 'Soccer & jersey', 'football sports'],
      [82, 'Fan & football', 'sports cheer'],
      [83, 'Golfer & hole', 'golf sports'],
      [84, 'Pincushion & sewing machine', 'sewing craft', true],
      [85, 'Circus / seal & tent', 'party circus', true],
      [86, 'Sea life / fish', 'ocean aquarium', true],
      [87, 'Music notes & stars', 'music melody'],
      [88, 'Ticket & stamp', 'coupon postmark'],
      [89, 'Seasonal ornament', 'holiday badge', true],
      [90, 'Fruit branch', 'apple orange kitchen', true],
      [91, 'Hanging hearts', 'love valentine', true],
      [92, 'Gift with ribbon', 'present wrap', true],
      [93, 'Birds on swirls', 'doves nature', true],
      [94, 'Beads & heart locket', 'jewelry love', true],
      [95, 'Roses', 'flowers romantic', true],
      [96, 'Flower bouquets', 'floral', true],
      [97, 'Clock & rabbit', 'wonderland fairy tale', true],
      [98, 'Fairy & moon', 'magic fantasy', true],
      [99, 'Carriage & castle', 'cinderella fairy tale princess', true],
    ],
  },
  templates: {
    notes: [
      'Templates need 12 mm (0.47") tape and cannot be edited or saved to memory. Max 50 characters.',
      'Text templates: no label length setting and no copies. Pattern templates: no text and no preview.',
      'Exit templates with [Esc], or pick {Quit} with [◀] / [▶] when {Print} is shown and press [OK].',
      'Preview a text template with the [Preview] key while {Print} is shown.',
    ],
    textHowto: [
      'Press [Template Library].',
      '{Select Category}: use [◀] / [▶] to pick {Text}, then [OK].',
      '{Select Design}: use [◀] / [▶] to pick the design (number below), then [OK].',
      '{Input Text 1}: clear the sample text with [BS] (or [Shift] + [BS] for all), type yours, then [OK].',
      'Two-font templates then ask for {Input Text 2}: type it and press [OK].',
      '{Print}: press [OK]. Cut when "Please Cut" appears.',
    ],
    patternHowto: [
      'Press [Template Library].',
      '{Select Category}: use [◀] / [▶] to pick {Patterns}, then [OK].',
      '{Select Design}: use [◀] / [▶] to pick the pattern, then [OK].',
      '{Set Label Length}: [◀] / [▶] for 30–999 mm (1.2"–39"), then [OK]. [Space] resets to 100 mm.',
      '{Print}: use [◀] / [▶] or a digit for 1–9 copies, then [OK].',
    ],
    // [number, name, keywords, description]
    text: [
      [1, 'Letters in stars', 'kids initials star alphabet', 'Each letter inside a star.'],
      [2, 'Letters in apples', 'kids fruit alphabet', 'Each letter inside an apple.'],
      [3, 'Letters in cars', 'kids vehicle alphabet', 'Each letter inside a car silhouette.'],
      [4, 'Letters in hearts', 'kids love alphabet', 'Each letter inside a heart.'],
      [5, 'Letters in solid circles', 'circled letters initials', 'White letters in black circles.'],
      [6, 'Letters in solid squares', 'boxed letters blocks', 'White letters in black squares.'],
      [7, 'File No.1 (serif)', 'file folder binder filing', 'Serif style file label.'],
      [8, 'File No.1 (bold italic)', 'file folder modern', 'Bold italic file label.'],
      [9, 'File No.1 (script)', 'file folder elegant script', 'Script style file label.'],
      [10, 'File No.1 (heavy)', 'file folder bold heavy', 'Heavy sans-serif file label.'],
      [11, 'To Name (ribbon / floral)', 'gift tag present to from', 'Gift-tag style with flourish.'],
      [12, 'To Name (snowflakes)', 'gift tag christmas winter', 'Gift tag with snowflake ornaments.'],
      [13, 'To Name (carriage & castle)', 'gift tag fairytale', 'Fairytale carriage and castle.'],
      [14, 'Bill White / ABC Company', 'name badge company centered', 'Two-line centered name and company.'],
      [15, 'Bill White / ABC Company (icons)', 'name badge squares', 'Name/company with icon squares.'],
      [16, 'ABC Company / Bill White (solid)', 'name badge inverted banner', 'Inverted name bar under company.'],
      [17, 'Bill White / ABC Company (framed)', 'name badge double frame', 'Two-line name in a double-line box.'],
    ],
    pattern: [
      [1, 'Ornate lace', 'floral filigree lace border', 'Dense ornate lace/filigree pattern.'],
      [2, 'Diamond lattice lace', 'geometric lace diamonds', 'Interconnected diamond lace.'],
      [3, 'Dense woven lace', 'crosshatch lace scallop', 'Dense woven/scalloped lace.'],
      [4, 'Small flowers / snowflakes', 'floral star motif', 'Repeating small floral motifs.'],
      [5, 'Crown filigree', 'ornate scroll flourish', 'Regal scrollwork border.'],
      [6, 'Pets & nature', 'dog cat paw butterfly bird', 'Pets, paw prints and small animals.'],
      [7, 'Houndstooth / plaid', 'check tartan geometric', 'Diagonal check / houndstooth.'],
      [8, 'Polka dots', 'dots grid pattern', 'Regular polka-dot grid.'],
      [9, 'Fruit & roses', 'apple grapes rose leaf', 'Roses, apples, grapes and leaves.'],
      [10, 'Emoji faces', 'smiley emoticon expressions', 'Repeating emoji face row.'],
    ],
  },
  howto: [
    { id: 'margins', title: 'Save tape: margins (Full / Half / Narrow / Chain)', kw: 'margin waste tape saving short label length leader blank space before after cut dots',
      steps: ['Press [Label].', 'Use [◀] / [▶] until {Margin} shows, then [OK].', 'Pick {Full} (25 mm each side), {Half} (12 mm), {Narrow} (4 mm) or {Chain Print}, then [OK].'],
      notes: ['The ~25 mm lead-in before the first label cannot be eliminated (it is the distance from print head to cutter). With Half / Narrow the device prints two dots (:) — cut there with scissors so the margins are even.', 'For several labels in a row use Chain Print (below) — later labels lose the lead-in entirely.', 'Fix for "too much blank tape on both sides of the text".'] },
    { id: 'chain', title: 'Chain Print: many labels, minimal waste', kw: 'chain print batch several labels feed ok waste multiple',
      steps: ['[Label] → {Margin} → [OK] → {Chain Print} → [OK].', 'Type the first label and press [Print]. When {Copies:} shows, set the number and press [OK].', 'When "Feed OK?" appears press [Esc] to keep going.', 'Clear the text (keep the format), type the next label, press [Print].', 'After the last label press [OK] at "Feed OK?" so the tape feeds, then push the cutter lever.'],
      notes: ['Feed before cutting, otherwise the last label may be cut through.', 'When a specific label is done printing you can also cut manually with the lever — only after "Please Cut".'] },
    { id: 'two-lines', title: 'Two-line labels', kw: 'two lines second line enter multi-line return 2 line limit',
      steps: ['Type line 1.', 'Press [Enter] where the second line should start (a ↵ appears on the LCD).', 'Type line 2. Print.'],
      notes: ['Needs 9 mm or 12 mm tape. On 3.5 / 6 mm you get "2 Line Limit!" — the same message appears if you press Enter a third time.'] },
    { id: 'length', title: 'Fixed label length', kw: 'label length auto fixed size mm inch lock padlock change length',
      steps: ['Press [Label].', '{Label Length} → [OK].', 'Use [◀] / [▶] to pick {Auto} or 30–300 mm (1.2"–12"), then [OK].'],
      notes: ['A lock appears on the LCD when a length is fixed. Press [Space] in the setting to return to Auto.', '"Change Length!" means the text no longer fits: shorten it or return to Auto.', 'After printing, cut along the printed dots (:) so the length matches.'] },
    { id: 'tabs', title: 'Tabs and tab length', kw: 'tab spacing align columns tab length',
      steps: ['Insert a tab with [Tab] (or [Menu] → {Tab} → [OK]). A ▯ shows in the text.', 'Tab length: [Label] → {Tab Length} → [OK] → {Auto} or 0–100 mm → [OK].'],
      notes: ['Up to 80 tabs in a label with no text (79 with one letter). [Space] resets tab length to Auto.'] },
    { id: 'caps', title: 'Upper and lower case', kw: 'caps lock uppercase lowercase capital shift letters',
      steps: ['Press [Caps] to toggle upper case for everything you type (Caps indicator on the LCD).', 'Hold [Shift] while typing one letter for a single capital.'] },
    { id: 'accents', title: 'Accented characters (é ñ ü …)', kw: 'accent accented letters umlaut tilde cedilla international spanish french german',
      steps: ['Type the letter.', 'Press [Accent]. Press [Accent] again (or [◀] / [▶]) to cycle the variants.', 'Press [OK].'],
      notes: ['See the Accent table under Symbols for every variant. Order depends on the LCD language.'] },
    { id: 'clear', title: 'Clear text and/or formatting', kw: 'clear delete erase all text format new label start over',
      steps: ['[BS] deletes one character (Backspace).', '[Shift] + [BS] → choose {Text&Format} (everything) or {Text Only} (keep font, frame, margins) → [OK].', 'Alternative: [Menu] → {Clear} → [OK] → {Text&Format} / {Text Only} → [OK].'] },
    { id: 'preview', title: 'Preview a label', kw: 'preview view before print check image lcd',
      steps: ['Press [Preview] (the magnifier key).', 'Scroll a long label with [◀] / [▶].', 'Leave with [Esc], [OK] or [Enter].'],
      notes: ['The preview is generated and may differ slightly from the print. Not available for pattern templates.'] },
    { id: 'feed', title: 'Feed blank tape', kw: 'feed tape advance blank 25 mm',
      steps: ['Press [Shift] + [Preview]. About 25 mm (1") of tape feeds.'] },
    { id: 'print-copies', title: 'Print and print copies', kw: 'print copies multiple duplicates cut lever please cut peel backing',
      steps: ['Press [Print]. {Copies:} appears.', 'Use [◀] / [▶] or type a digit for 1–9 copies (or just press [OK] for one).', 'Press [OK].', 'When "Please Cut" appears push the cutter lever at the top right.'],
      notes: ['Never press the lever while "Please Wait" is displayed — it jams the tape.', 'To peel: fold the label lengthwise with text inside so the backing splits, then peel each half.'] },
    { id: 'numbering', title: 'Numbering (auto-increment serial labels)', kw: 'numbering serial sequence increment auto number consecutive 0123 0124 series count',
      steps: ['Type the text including the number, e.g. {0123}.', 'Move the cursor onto the number to increment with [◀] / [▶].', 'Press [Shift] + [Print].', '{Numbering} → [OK].', 'Use [◀] / [▶] to set the highest number to print (e.g. 0125 prints 0123, 0124, 0125), then [OK].'],
      notes: ['Up to 9 labels per run. "Invalid!" means the cursor is not on a number.'] },
    { id: 'mirror', title: 'Mirror print (for glass and windows)', kw: 'mirror reverse flip window glass inside transparent clear tape backwards',
      steps: ['Type the text.', 'Press [Shift] + [Print].', '[◀] / [▶] to {Mirror} → [OK].', '{Mirror Print?} → [OK].'],
      notes: ['Use clear tape so the label reads correctly from the other side of the glass.'] },
    { id: 'files', title: 'Save, open and print stored labels (30 slots)', kw: 'save file memory store recall open load favorite stored labels slots overwrite',
      steps: ['Save: type the label → [File] → [◀] / [▶] to {Save} → [OK] → [◀] / [▶] to a slot number (1–30) → [OK]. Choosing an occupied slot asks "Overwrite OK?".', 'Print a stored label: [File] → {Print} → [OK] → pick the slot → [OK] → {Copies:} → [OK].', 'Open for editing: [File] → {Open} → [OK] → pick the slot → [OK].', 'Shortcut into the File menu: [Menu] → [1].'],
      notes: ['80 characters per file, 2400 in total. Files are lost after a reset, a repair, or if power is cut for a long time — keep good batteries in as memory backup even when using the adapter.', 'Labels made with templates cannot be saved.'] },
    { id: 'font', title: 'Font, size, width, style and alignment', kw: 'font typeface size large medium small width x2 half style bold italic outline shadow solid vertical alignment left center right justify',
      steps: ['Press [Font].', 'Use [◀] / [▶] to pick {Font}, {Size}, {Width}, {Style} or {Alignment}, then [OK].', 'Use [◀] / [▶] to pick the setting, then [OK].'],
      notes: ['See the Fonts & styles section for samples of all 14 fonts and 10 styles (D210 has no I+Solid).', 'Vertical style prints each character rotated so the label reads top-to-bottom when hung vertically.'] },
    { id: 'frame', title: 'Add a frame', kw: 'frame border box decoration outline around text',
      steps: ['Press [Frame].', 'Type the frame number or browse with [◀] / [▶].', 'Press [OK].'],
      notes: ['12 mm-only frames are highlighted on the insertion sheet. See the Frames section to browse designs with their numbers.'] },
    { id: 'symbol', title: 'Insert a symbol or pictogram', kw: 'symbol pictogram icon picture insert history',
      steps: ['Press [Symbol].', 'Choose {History}, {Basic} or {Pictograph} with [◀] / [▶], then [OK].', 'Choose the category (or press its shortcut letter), then [OK].', 'Move to the symbol with [◀] / [▶], then [OK].'],
      notes: ['History holds your 7 most recent symbols. Every category page in this app shows the shortcut key and each symbol\'s position.'] },
    { id: 'templates', title: 'Use the template library', kw: 'template library text label pattern label designs built-in',
      steps: ['Press [Template Library].', '{Select Category}: {Text} or {Patterns} → [OK].', 'Pick a design → [OK], then follow the prompts ({Input Text 1}, {Input Text 2} or {Set Label Length}).', '{Print} → [OK].'],
      notes: ['12 mm tape only. See the Templates section for pictures of all 27 designs (17 text + 10 pattern).'] },
    { id: 'language-unit', title: 'Language and units (inch / mm)', kw: 'language english spanish french unit inch mm millimetre setup initial settings',
      steps: ['Language: [Menu] → [◀] / [▶] to {Language} → [OK] → pick → [OK]. Shortcut: [Menu] → [Space].', 'Unit: [Menu] → {Unit} → [OK] → {inch} / {mm} → [OK]. Shortcut: [Menu] → [3].'],
      notes: ['Languages from the D210 guide: English, Español, Français, Hrvatski, Italiano, Magyar, Nederlands, Norsk, Polski, Português, Portug. (BR), Română, Slovenski, Slovenský, Suomi, Svenska, Türkçe, Čeština, Dansk, Deutsch.'] },
    { id: 'contrast', title: 'LCD contrast', kw: 'contrast brightness screen dark light display hard to read',
      steps: ['[Menu] → {LCD Contrast} → [OK] → [◀] / [▶] for −2 … +2 → [OK]. Shortcut: [Menu] → [4].'],
      notes: ['[Space] returns to the default (0).'] },
    { id: 'reset', title: 'Factory reset (also fixes a locked-up device)', kw: 'reset factory initialize frozen locked up not responding hang restore default clear memory',
      steps: ['Turn the device off.', 'Hold [Shift] and [R], then press [Power] to turn it on.', 'Release [Power] first, then release [Shift] and [R].'],
      notes: ['Everything is erased: text, settings, all 30 stored files, language and unit.'] },
    { id: 'cursor', title: 'Move around long text', kw: 'cursor jump start end navigate scroll long text shift arrow',
      steps: ['[◀] / [▶] move one character.', '[Shift] + [▶] jumps to the end, [Shift] + [◀] to the start.', 'The LCD shows 15 characters at a time; the label can hold 80.'] },
    { id: 'power', title: 'Batteries, adapter and auto power off', kw: 'battery batteries AAA adapter AD-24ES power off automatic sleep memory backup',
      steps: ['Use 6 × AAA alkaline (LR03) or fully charged Ni-MH (HR03) — replace all six together, never mix types.', 'Optional adapter AD-24ES / AD-24ESA plugs into the jack at the top. Keep batteries in as memory backup.', 'The device switches off after 5 idle minutes. Text and settings survive 3 minutes without any power; longer and they are lost.'],
      notes: ['The device cannot charge Ni-MH cells. Compatible adapters also include AD-24ESAW / AD-24ESA-01 / AD-24ESAW-01.'] },
    { id: 'tape', title: 'Change the tape cassette', kw: 'tape cassette install replace insert TZe cartridge jam stuck feed guides',
      steps: ['Switch off. Press the marked area at the top end to open the cassette cover.', 'Pull the old cassette straight up.', 'Insert the new TZe cassette until it clicks, making sure the tape end runs under the tape guides.', 'Close the cover.'],
      notes: ['Only Brother TZe tapes with the TZe mark work. Never print with an empty cassette — it damages the print head.', 'Blank line through the print? Wipe the print head with a dry cotton swab.'] },
    { id: 'cutter', title: 'Replace a blunt cutter (TC-4)', kw: 'cutter blade dull blunt not cutting replace TC-4',
      steps: ['Open the cassette cover and remove the tape.', 'Pull the two green sections of the cutter unit out in the direction of the arrows.', 'Push the new TC-4 unit in until it locks.'],
      notes: ['Never touch the blade with your fingers.'] },
  ],

  errors: [
    ['Battery Low! / Battery Empty!', 'Batteries are weak or nearly flat.', 'Replace all six alkaline cells, or fully charge the Ni-MH cells.'],
    ['Invalid!', 'Numbering with no number under the cursor, an invalid character selected for Numbering, or an invalid Tab / Label Length value (also inside templates).', 'Move the cursor onto a digit, or enter a value within range.'],
    ['No Text!', 'Print, Preview, Feed, Numbering or a template step was requested with no text entered, or you tried to print an empty file slot.', 'Type some text first.'],
    ['2 Line Limit! / 1 Line Limit!', 'You pressed Enter for a third line, or tried two lines on 3.5 / 6 mm tape.', 'Use 9 or 12 mm tape for two lines; keep to two lines max.'],
    ['No Cassette!', 'Print, feed or preview with no tape installed.', 'Insert a TZe cassette.'],
    ['Cutter Pressed', 'The cutter lever was pushed while printing.', 'Wait for "Please Cut" before cutting.'],
    ['Text Full!', '80 characters (50 in templates) already entered.', 'Shorten the text.'],
    ['Change Length', 'The text is longer than the fixed label length.', 'Reduce the text or set Label Length back to Auto ([Space] in the setting).'],
    ['No Frame OK?', 'Frame set on 3.5 mm tape, or a 12 mm-only frame on narrower tape.', '[OK] prints without the frame, [Esc] cancels. Or switch to 12 mm tape.'],
    ['Feed OK?', 'Shown after each label when Chain Print is on.', '[OK] feeds the tape (do this before cutting the last label); [Esc] continues with the next label.'],
    ['Insert 0.47"', 'Templates need 12 mm tape.', 'Install a 12 mm (0.47") cassette.'],
    ['Use TZe Tape!', 'The cassette is not a TZe tape.', 'Use a cassette with the TZe mark.'],
  ],
  problems: [
    ['Display stays blank after power on', 'Check battery orientation, replace weak batteries, or check the adapter is plugged in properly.'],
    ['Too much blank tape on both sides of the text', 'Label → Margin → Half or Narrow. Use Chain Print for batches. The first 25 mm lead-in cannot be removed.'],
    ['Nothing prints, or characters are malformed', 'Check the cassette is inserted correctly and not empty, and that the cover is closed. Weak batteries also cause faint or broken print.'],
    ['Settings cleared on their own', 'Weak batteries, or power was disconnected for more than 3 minutes.'],
    ['Blank horizontal line through the label', 'Dust on the print head: remove the cassette and gently wipe the head up and down with a dry cotton swab.'],
    ['Device locked up (keys do nothing)', 'Do the factory reset: off → hold Shift + R → Power → release Power, then Shift and R.'],
    ['Power turns off when printing', 'Weak batteries, wrong adapter, or batteries inserted incorrectly. Use AD-24ES / AD-24ESA.'],
    ['Tape does not feed or gets stuck', 'Make sure the tape end runs under the guides. Do not touch the cutter lever while printing.'],
    ['Tape jammed inside', 'Open the cover, remove the cassette, gently pull out the jammed tape and rewind slack into the cassette with a fingertip before re-inserting.'],
    ['Cutter does not cut cleanly', 'Replace the cutter unit (TC-4).'],
    ['Want to start a fresh label', 'Shift + BS → Text&Format → OK.'],
  ],
  tips: [
    'Type a frame number straight after pressing Frame instead of scrolling through every design.',
    'Category shortcut letters work right after choosing Basic or Pictograph: Symbol → Pictograph → OK → Space jumps to Fun.',
    'History (the first option under Symbol) remembers your last 7 symbols — the fastest way to reuse ⚠ or →.',
    'PT-D210 has 10 styles (no I+Solid) and 27 templates (17 text + 10 pattern) — a bit different from the PT-D220.',
    'Two lines of small text on 12 mm tape fit twice the information per label — great for pantry jars with name + date.',
    'Store your 30 most-used labels in File slots and reprint them with Menu → 1 → Print.',
    'Press Space inside any setting to jump back to its default.',
  ],
};

