// Brady M211. Reference data for Labelarium.
// Source: official M211 User Manual Y5067197 Revision A-3 (2025) plus Brady support.
// The M211 has no on-device keyboard, fonts, frames, templates or symbol sheet.
// Labels are designed in the Brady Express Labels mobile app and sent over Bluetooth.
// Notation in steps: [Key] = a control on the printer, {Text} = app / status wording, → = then.
// Catalog tiles are one tight crop per printed cell from THIS M211 manual. Not Brother or M210 lists.
// Symbol items: [name, keywords, unicode approximation]. Position (1-based) = order in that printed catalog.
export default {
  id: 'brady-m211',
  brand: 'Brady',
  model: 'M211',
  name: 'M211 Label Printer',
  tagline: 'Bluetooth portable printer · Express Labels app',
  links: [
    ['Official support, FAQs & manual', 'https://www.bradyid.com/support/printer/m211'],
    ['Brady Express Labels (iOS)', 'https://apps.apple.com/us/app/brady-express-labels/id1428966237'],
    ['Brady Express Labels (Android)', 'https://play.google.com/store/apps/details?id=com.bradycorp.expresslabels'],
    ['Express Labels overview', 'https://www.bradyid.com/expresslabelsmobile'],
    ['Register the printer', 'https://www.bradycorp.com/register'],
  ],
  specs: [
    ['Print', 'Thermal transfer, 203 dpi, up to 0.6 in/s (15.2 mm/s), single colour'],
    ['Print area', 'Width 0.63" (16 mm) max · length 36" (914 mm) max · liner 0.875" (22.2 mm) max'],
    ['Labels', 'M21-series cartridges (ribbon + media in one). Widths 0.235"–0.75" (6.4–19 mm). Min height 0.236" (6 mm)'],
    ['Cartridge in the box', 'M21-750-499 black-on-white nylon cloth, 3/4". Brady Authentic smart-cell only'],
    ['Cutter', 'Automatic cutter with label retention; [Cut] also cuts manually. Cut mode is set in the label file'],
    ['Design', 'Brady Express Labels app (Android 6.0+ or iOS 10.0+, phone Bluetooth 4.2+). No on-printer editor'],
    ['Connection', 'Bluetooth Low Energy 5.0, one phone at a time, about 65 ft (19.8 m)'],
    ['Power', 'Internal 1100 mAh Li-ion (not user-replaceable). USB-C; use the ≥15 W adapter that shipped with the printer'],
    ['Charge', 'About 2.5 h to full (battery LED pulses green, then solid). Deep-discharged packs may need 6–8 h'],
    ['Duty', 'Up to 300 labels per charge; 100 labels/day recommended'],
    ['Auto power off', 'Default 30 minutes idle; set in Express Labels. Settings are not stored on the printer'],
    ['Size / weight', '11.0 × 4.5 × 4.6 in (279 × 113 × 116 mm), 1.2 lb (0.54 kg) with cartridge'],
    ['Environment', 'Operate 40–110 °F (4–43 °C), 20–90% RH non-condensing. Drop 6 ft (1.8 m); crush 250 lb (113.4 kg)'],
    ['Manual', 'Y5067197 Revision A-3, © 2025 Brady Worldwide, Inc.'],
  ],
  tapes: [
    { mm: 6.4, in: '0.235"', lines: 1, note: 'Minimum M21 label width in the user manual. Smart-cell sets formatting in the app.' },
    { mm: 12, in: '0.47"', lines: 1, note: 'Inside the published 6.4–19 mm range (the manual does not list this width as its own SKU).' },
    { mm: 19, in: '0.75"', lines: 1, note: 'Maximum label width. Included M21-750-499 is 3/4" nylon cloth. Printable width is 0.63" (16 mm).' },
  ],
  keyboard: {
    image: 'img/keyboard.png',
    legend: [
      [1, 'Cartridge bay with cartridge', 'M21 cartridge (ribbon + labels). Only Brady Authentic smart-cell cartridges. Unlock the lever before removing.'],
      [2, 'Label exit', 'Printed labels exit here. The auto cutter sits in this path; never pick fragments with your fingers.'],
      [3, 'Eject button', 'On the back. Unlock the lever, press eject, then lift the cartridge out.'],
      [4, 'USB charging port', 'USB-C. Charge from the supplied AC adapter (≥15 W) or a USB-A port via the C-to-A coupler (slower).'],
      [5, 'Lock lever', 'Clockwise = locked (ready to print). Counter-clockwise = unlocked (load/unload, and when idle so the printhead is not left on the platen).'],
      [6, 'Error indicator', 'Flashing orange: critical (open Express Labels for the message). Solid orange: non-critical; dismiss in the app and continue.'],
      [7, 'Battery indicator', 'Pulsing green = charging. Green 51–100%, orange 21–50%, red 11–20%, flashing red <10%.'],
      [8, 'Bluetooth indicator', 'Pulsing = broadcasting for pairing. Solid = paired. Only one mobile device at a time.'],
      [9, 'Cut button', 'Press to cut manually. Auto-cut follows the cut setting in the Express Labels file (between labels or end of job).'],
      [10, 'Power button and Bluetooth reset', 'Tap: on/off. Hold 5 seconds: drop the current pairing so another phone can connect. Hold 15 seconds: hard boot (battery and Bluetooth lights come on when it restarts).'],
    ],
  },
  shortcuts: [
    { keys: 'tap [Power]', action: 'Turn the printer on or off', kw: 'power on off start shutdown' },
    { keys: 'hold [Power] 5 seconds', action: 'Reset Bluetooth so a new phone can pair (light pulses)', kw: 'bluetooth disconnect unpair reset pairing' },
    { keys: 'hold [Power] 15 seconds', action: 'Hard boot if the printer is unresponsive', kw: 'reboot reset frozen locked up restart hard boot' },
    { keys: '[Cut]', action: 'Manual cut (auto-cut is set in the Express Labels file)', kw: 'cutter cut blade scissors' },
    { keys: 'lock lever clockwise', action: 'Lock the cartridge (required before print)', kw: 'lock lever cartridge print ready' },
    { keys: 'lock lever counter-clockwise', action: 'Unlock to load/unload, and whenever the printer sits idle', kw: 'unlock lever cartridge idle printhead platen' },
    { keys: '[Eject] after unlock', action: 'Pop the cartridge out of the bay', kw: 'eject remove cartridge change tape' },
    { keys: 'Express Labels → Print', action: 'Send the open label file to the M211', kw: 'print app send bluetooth' },
    { keys: 'Express Labels → gear', action: 'Printer properties including shutdown time (default 30 min)', kw: 'settings shutdown timeout idle auto off' },
    { keys: 'Express Labels → printers → more', action: 'Rename this M211 (name is not stored on the printer)', kw: 'rename printer name serial' },
  ],
  fonts: [
    ['Express Labels (phone)', 'express-labels.png', 'There is no Font key on the M211. Type is chosen in Brady Express Labels on your phone. This tile is the M211 wordmark printed in the user manual. The manual does not include a font catalog.', 'Arial, Helvetica, sans-serif', 400, 'normal'],
  ],
  sizes: [['App autosize', 'size-auto.png', 1]],
  widths: [['App default', 'width-normal.png', 1]],
  styles: [
    ['App default', 'style-normal.png'],
  ],
  alignments: [['App default', 'align-left.png']],
  fontNote: 'The M211 user manual (Y5067197 Rev A-3) does not print a font, size, width, style or alignment catalog. All typography lives in Brady Express Labels. The sample tiles are type and marks cropped from this manual, not an on-printer typeface list.',

  symbols: {
    howto: [
      'The M211 has no [Symbol] key and no on-printer pictograph sheet.',
      'Design symbols, barcodes and text in {Brady Express Labels} on a phone, then tap Print. The printer only needs to be on, locked, and paired.',
      'Tiles below are the catalog cells this M211 manual actually prints: the control panel, the accessories grid, cartridge states, and the recycling diagram.',
      'Express Labels includes additional app artwork that is not printed in this printer manual, so it is not listed here.',
    ],
    categories: [
      { id: 'controls', name: 'Controls & status', group: 'Pictograph', key: 'panel', kw: 'power cut bluetooth battery error led lights buttons', items: [
        ['Bluetooth indicator', 'pairing ble wireless connect pulsing solid', '📶'],
        ['Battery indicator', 'charge charging green orange red percent', '🔋'],
        ['Error indicator', 'fault orange flashing critical', '⚠️'],
        ['Cut button', 'cutter scissors manual cut auto cut', '✂️'],
        ['Power button', 'on off reboot bluetooth reset hold tap', '⏻'],
      ]},
      { id: 'accessories', name: 'Accessories', group: 'Pictograph', key: 'shop', kw: 'magnet clip case adapter power brick belt multi-tool', items: [
        ['Magnet (M21-MAGNET)', 'neodymium panel ibeam metal mount', '🧲'],
        ['Belt clip (M21-BELTCLIP)', 'holster belt clip carry', '📎'],
        ['Multi-Tool (M21-TOOL)', 'wire stripper tool accessory', '🔧'],
        ['Soft-sided carrying case (BMP-SC-1)', 'bag tote carry case', '👜'],
        ['Hard-sided carrying case (M211-HC)', 'hard case suitcase protect', '🧳'],
        ['Power Brick (M211-POWER)', 'battery pack extra power usb', '🔋'],
        ['AC adapter set for North America (M211-AC)', 'usb-c charger wall plug type a', '🔌'],
        ['AC adapter set for Europe, Middle East, and Africa (M211-EU-UK-US-AC)', 'charger type c type g europe uk', '🔌'],
        ['AC adapter set for Asia-Pacific and Australia (M2111-APAC-AC)', 'charger type c type g type i australia asia. Printed catalog number on this page is M2111-APAC-AC; the adapter table earlier in the manual lists M211-APAC-AC', '🔌'],
      ]},
      { id: 'cartridge', name: 'Cartridge', group: 'Pictograph', key: 'lock', kw: 'm21 authentic smart-cell nylon lock lever', items: [
        ['Locked', 'lever vertical print ready clockwise', '🔒'],
        ['Unlocked', 'lever horizontal load unload idle counterclockwise', '🔓'],
        ['Brady Authentic mark', 'smart-cell genuine cartridge only use authentic', '✓'],
      ]},
      { id: 'recycle', name: 'Recycling the cartridge', group: 'Pictograph', key: 'bin', kw: 'recycle pet hdpe metal electronic housing spring washer smart cell', items: [
        ['Plastic washer (PETE #1)', 'mylar washer spacer plastics 1 pete', '♻️'],
        ['Plastic spacer (HDPE #2)', 'spacer disc plastics 2 hdpe', '♻️'],
        ['Smart cell (electronic waste)', 'chip rfid authentic electronic waste', '💾'],
        ['Large and small springs, washers (metals #40 FE)', 'spring washer metal ferrous 40', '🔩'],
        ['Housings and retaining arm (PC #7)', 'polycarbonate housing plastics 7', '🧱'],
      ]},
    ],
    accented: {
      image: 'img/symbols/accented.png',
      howto: [
        'The M211 has no [Accent] key.',
        'Type accented letters on the phone keyboard inside Brady Express Labels.',
        'The graphic is the Express Labels mark printed in this user manual (Connecting the Printer).',
      ],
      table: {},
    },
  },

  frames: {
    howto: [
      'The M211 has no [Frame] key.',
      'Any border or layout is chosen in Brady Express Labels, not on the printer.',
      'This user manual does not print a frame catalog, so none is listed.',
    ],
    notes: [
      'Off is a blank patch from the printed page. The M211 guide has no frame sheet.',
      'Do not expect Brother-style numbered frames; those lists belong to other machines.',
    ],
    items: [
      ['off', 'No frame', 'none off plain'],
    ],
  },

  templates: {
    notes: [
      'The M211 has no Template Library key and this user manual does not print text or pattern templates.',
      'Create the label in Brady Express Labels (design guides live in the app, not in Y5067197).',
      'When you first create a file, pick the M211 so the app can match the installed M21 cartridge.',
    ],
    textHowto: [
      'Open Brady Express Labels on the phone.',
      'Connect the M211 (printer on, Bluetooth paired).',
      'Create a label file for the M211, type the text, tap Print.',
    ],
    patternHowto: [
      'Open Brady Express Labels on the phone.',
      'Pick a layout in the app. This printer manual does not show pattern tiles.',
      'Tap Print. The M211 cuts according to the file’s cut setting.',
    ],
    text: [],
    pattern: [],
  },

  howto: [
    { id: 'charge', title: 'Charge before first use', kw: 'battery charge usb adapter 15w green led',
      steps: ['Plug USB-C into the printer.', 'Use the supplied AC adapter (at least 15 W) and the regional plug.', 'Charge about 2.5 hours. The battery light pulses green, then stays solid green.'],
      notes: ['USB-A ports and weaker adapters charge more slowly.', 'If the pack was run completely flat and left unused about four weeks, reconditioning can take 6–8 hours.'] },
    { id: 'power', title: 'Power, Bluetooth reset and hard boot', kw: 'power on off bluetooth reboot 5 seconds 15 seconds',
      steps: ['Tap [Power] to turn on or off. Bluetooth is on whenever the printer is on.', 'Hold [Power] 5 seconds until the Bluetooth light pulses to drop the current phone.', 'Hold [Power] 15 seconds to hard-boot a frozen printer. Battery and Bluetooth lights come on when it has restarted.'] },
    { id: 'connect', title: 'Connect Express Labels over Bluetooth', kw: 'pair bluetooth app express labels phone android ios',
      steps: ['Install Brady Express Labels (Android 6.0+ or iOS 10.0+; phone needs Bluetooth 4.2+).', 'Turn the M211 on.', 'Open the app. It should detect the printer. Rename if you want, then tap connect.'],
      notes: ['Only one mobile device at a time. If the printer does not appear, hold [Power] 5 seconds to release the previous pairing.', 'Range is about 65 ft (19.8 m).'] },
    { id: 'settings', title: 'Shutdown time and printer name', kw: 'auto off 30 minutes rename serial settings gear',
      steps: ['Shutdown: open an M211 label file → tap the gear → set idle time (default 30 minutes).', 'Name: in the app printer list, open the more menu → rename.'],
      notes: ['These settings live in the app session, not on the printer. The next user starts from defaults. Language and units are app-wide.'] },
    { id: 'load', title: 'Load an M21 cartridge', kw: 'cartridge m21 authentic smart-cell lock lever eject',
      steps: ['Turn the lock lever counter-clockwise to unlock (power may be on or off).', 'Press [Eject] on the back and lift the cartridge out.', 'Drop the new Brady Authentic cartridge in until it snaps.', 'Turn the lever clockwise to lock.'],
      notes: ['Only cartridges with the Brady Authentic mark. Smart-cell tells the app the media and sets many format details.', 'Unlock the cartridge whenever you are not printing. A locked idle printer can transfer a black line onto the first label from residual heat.'] },
    { id: 'print', title: 'Print from the app', kw: 'print send file cut lock',
      steps: ['Printer on, cartridge locked.', 'Open the label file on the phone.', 'Tap Print. The app sends the job.', 'If the cartridge runs out mid-job, printing stops and the error light comes on. The app shows the message.'],
      notes: ['There is no on-printer editor. An SDK exists if you need other software; see Brady’s programming site.'] },
    { id: 'cut', title: 'Auto-cut and the Cut button', kw: 'cutter automatic manual fragments jam',
      steps: ['Set cut-between-labels or cut-at-end-of-job in the Express Labels file.', 'Press [Cut] on the printer for a manual cut.'],
      notes: ['If cuts are rough, fragments may be in the cutter. Unlock, remove the cartridge, pick fragments with tweezers, never fingers. The cutter is sharp.'] },
    { id: 'magnet', title: 'Fit the magnet accessory (M21-MAGNET)', kw: 'magnet neodymium panel ibeam pacemaker',
      steps: ['Slide the keeper plate off the magnet.', 'Line the magnet up with the screw holes on the back of the printer.', 'Fit the two screws that come with the magnet.'],
      notes: ['Neodymium magnet. Keep away from pacemakers, defibrillators, insulin pumps, cards, drives, and explosive atmospheres. Do not give children strong magnets. Wear eye protection if magnets may snap together.'] },
    { id: 'clean', title: 'Clean the printhead, platen and sensor', kw: 'printhead platen roller sensor pck-6 isopropyl offset',
      steps: ['Power off. Unlock and remove the cartridge.', 'Moisten a lint-free swab with isopropyl alcohol, or use Brady PCK-6 swabs.', 'Gently swab the printhead, then the platen (you may need to lock the lever to reach the roller).', 'Blow or swab debris off the position sensor if pre-sized labels print offset.'] },
    { id: 'recycle', title: 'Dismantle a used cartridge for recycling', kw: 'recycle smart cell housing spring washer screwdriver ppe',
      steps: ['Wear safety glasses and gloves. Use a 1/4-inch flathead screwdriver.', 'Pry the smart cell off the bottom (it is glued).', 'Twist the screwdriver in the seam to split the housing.', 'Remove leftover media, shake out parts, unwind the ribbon from its spools.', 'Bin: housings/retaining arm → #7 PC; springs/washers → #40 metals; smart cell → e-waste; plastic washers/spacers → #1 PETE.'] },
    { id: 'jam', title: 'Clear a label jam', kw: 'jam stuck feed unlock tweezers printhead scratch',
      steps: ['Unlock the lever (force it if the jam is large; unlocking retracts the platen).', 'Remove the cartridge.', 'Pull the jammed label and fragments with tweezers or needle-nose pliers.'],
      notes: ['Metal tools can scratch the printhead. Never use your fingers in the cutter.'] },
  ],

  errors: [
    ['The cutter is jammed', 'Error light on; Express Labels reports a cutter jam.', 'Follow the in-app instructions. Unlock, remove the cartridge, pick fragments with tweezers. See “Labels are jammed in the printer” in the manual (p. 25).'],
    ['The supply cartridge is not loaded correctly, missing, or not a Brady Authentic cartridge.', 'No cartridge, unlocked, damaged, or a non-Authentic cell.', 'Load a Brady Authentic M21 cartridge and lock the lever. See “Loading Cartridges” (p. 10).'],
    ['The supply cartridge is empty.', 'The smart cell reports no media left.', 'Replace the cartridge. Recycle the empty one per local rules (p. 12).'],
    ['Battery power is too low to print.', 'Pack too flat for a job.', 'Plug into the ≥15 W adapter. See “Power Adapter” (p. 5).'],
    ['The printer battery is getting low.', 'Warning before a hard stop.', 'Finish the job if you can, then charge.'],
    ['An error occurred while printing.', 'Generic print fault.', 'See Troubleshooting Scenarios (p. 24): lock, damage, jam, or hard boot (hold [Power] 15 seconds).'],
  ],
  problems: [
    ['Cutter does not cut, or cuts are rough', 'Fragments in the cutter, or the app is not set to cut. Unlock, remove the cartridge, pick fragments with tweezers, never fingers. Check the file’s cut setting.'],
    ['Labels won’t feed', 'Leading edge of the roll is torn or uneven. Cut a straight edge with scissors and reload.'],
    ['Labels are jammed', 'Unlock (force if needed), remove the cartridge, extract the jam with tweezers. Avoid scratching the printhead.'],
    ['Printer does not turn on', 'Charge with the supplied USB cable. If the pack is charged and it still stays off, hold [Power] 15 seconds.'],
    ['Printer turns off by itself', 'Low battery, or idle shutdown is shorter than you want (default 30 minutes in Express Labels).'],
    ['Print is light, fuzzy, grainy, offset, or has blank lines', 'Advance wrinkled ribbon on the take-up spool clockwise, clean the printhead/platen, try another cartridge, or feed past a crease in the app.'],
    ['First label after sitting idle has a black line', 'Cartridge was left locked. Residual heat transferred ink. Reprint, and unlock when you stop printing.'],
    ['Nothing prints', 'Lock the lever, check the cartridge, clear a jam, or hard-boot (15 seconds).'],
    ['Text is offset on pre-sized labels', 'Debris on the position sensor. Remove the cartridge and blow it off with compressed air.'],
    ['Battery not full after four hours', 'A pack that was fully drained and left unused ~four weeks can take 6–8 hours to recondition.'],
    ['Printer not in Express Labels', 'Another phone still holds the pairing. Hold [Power] 5 seconds until Bluetooth pulses, then connect.'],
  ],
  tips: [
    'Unlock the cartridge whenever you are not printing. A locked idle M211 can print a black line on the first label.',
    'Use the USB-C wall adapter that came in the box (≥15 W). USB-A ports charge more slowly.',
    'Only Brady Authentic M21 cartridges. The smart cell tells Express Labels the media and sets much of the format.',
    'One phone at a time. Hold [Power] 5 seconds to hand the printer to someone else.',
    'Hard boot is hold [Power] 15 seconds. There is no Shift+R factory reset on this machine.',
    'Cut mode (between labels vs end of job) is in the Express Labels file, not on a printer key.',
    'This pack lists only catalog cells printed in the M211 user manual. App fonts and symbols that are not in Y5067197 are not invented here.',
  ],
};
